/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T10:17:05.064+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "CodiceFiscaleObbligatorioException", messageName = "CodiceFiscaleObbligatorioException", targetNamespace = "http://autenticazione.interfacews.mudesrvextsic.mude.csi.it/")
public class CodiceFiscaleObbligatorioException_Exception extends MudeWSException {
    private it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.CodiceFiscaleObbligatorioException codiceFiscaleObbligatorioException;
    public CodiceFiscaleObbligatorioException_Exception() {
        super();
    }
	public CodiceFiscaleObbligatorioException_Exception(String message) {
		super(message);
		this.codiceFiscaleObbligatorioException = new CodiceFiscaleObbligatorioException();
	}
    public CodiceFiscaleObbligatorioException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.codiceFiscaleObbligatorioException = new CodiceFiscaleObbligatorioException();
    }
    public CodiceFiscaleObbligatorioException_Exception(String message, it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.CodiceFiscaleObbligatorioException codiceFiscaleObbligatorioException) {
        super(message);
        this.codiceFiscaleObbligatorioException = codiceFiscaleObbligatorioException;
    }
    public CodiceFiscaleObbligatorioException_Exception(String message, it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.CodiceFiscaleObbligatorioException codiceFiscaleObbligatorioException, Throwable cause) {
        super(message, cause);
        this.codiceFiscaleObbligatorioException = codiceFiscaleObbligatorioException;
    }
    public it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.CodiceFiscaleObbligatorioException getFaultInfo() {
        return this.codiceFiscaleObbligatorioException;
    }
}
