/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T10:17:05.115+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "FruitoreDisabilitatoException", messageName = "FruitoreDisabilitatoException", targetNamespace = "http://autenticazione.interfacews.mudesrvextsic.mude.csi.it/")
public class FruitoreDisabilitatoException_Exception extends MudeWSException {
    private it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.FruitoreDisabilitatoException fruitoreDisabilitatoException;
    public FruitoreDisabilitatoException_Exception() {
        super();
    }
	public FruitoreDisabilitatoException_Exception(String message) {
		super(message);
		this.fruitoreDisabilitatoException = new FruitoreDisabilitatoException();
	}
    public FruitoreDisabilitatoException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.fruitoreDisabilitatoException = new FruitoreDisabilitatoException();
    }
    public FruitoreDisabilitatoException_Exception(String message, it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.FruitoreDisabilitatoException fruitoreDisabilitatoException) {
        super(message);
        this.fruitoreDisabilitatoException = fruitoreDisabilitatoException;
    }
    public FruitoreDisabilitatoException_Exception(String message, it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.FruitoreDisabilitatoException fruitoreDisabilitatoException, Throwable cause) {
        super(message, cause);
        this.fruitoreDisabilitatoException = fruitoreDisabilitatoException;
    }
    public it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.FruitoreDisabilitatoException getFaultInfo() {
        return this.fruitoreDisabilitatoException;
    }
}
