/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T10:17:05.103+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "FruitoreNoComuniAssociatiException", messageName = "FruitoreNoComuniAssociatiException", targetNamespace = "http://autenticazione.interfacews.mudesrvextsic.mude.csi.it/")
public class FruitoreNoComuniAssociatiException_Exception extends MudeWSException {
    private it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.FruitoreNoComuniAssociatiException fruitoreNoComuniAssociatiException;
    public FruitoreNoComuniAssociatiException_Exception() {
        super();
    }
	public FruitoreNoComuniAssociatiException_Exception(String message) {
		super(message);
		this.fruitoreNoComuniAssociatiException = new FruitoreNoComuniAssociatiException();
	}
    public FruitoreNoComuniAssociatiException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.fruitoreNoComuniAssociatiException = new FruitoreNoComuniAssociatiException();
    }
    public FruitoreNoComuniAssociatiException_Exception(String message, it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.FruitoreNoComuniAssociatiException fruitoreNoComuniAssociatiException) {
        super(message);
        this.fruitoreNoComuniAssociatiException = fruitoreNoComuniAssociatiException;
    }
    public FruitoreNoComuniAssociatiException_Exception(String message, it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.FruitoreNoComuniAssociatiException fruitoreNoComuniAssociatiException, Throwable cause) {
        super(message, cause);
        this.fruitoreNoComuniAssociatiException = fruitoreNoComuniAssociatiException;
    }
    public it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.FruitoreNoComuniAssociatiException getFaultInfo() {
        return this.fruitoreNoComuniAssociatiException;
    }
}
