/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-07-14T15:53:09.220+02:00
 * Generated source version: 3.5.1
 *
 */
@WebService(targetNamespace = "urn:sigalfsrvGenerali", name = "sigalfsrvGenerali")
@XmlSeeAlso({ObjectFactory.class})
public interface SigalfsrvGenerali {

    @WebMethod
    @RequestWrapper(localName = "isComuneAventeCodiceIstatAbilitatoSigmater", targetNamespace = "urn:sigalfsrvGenerali", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali.IsComuneAventeCodiceIstatAbilitatoSigmater")
    @ResponseWrapper(localName = "isComuneAventeCodiceIstatAbilitatoSigmaterResponse", targetNamespace = "urn:sigalfsrvGenerali", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali.IsComuneAventeCodiceIstatAbilitatoSigmaterResponse")
    @WebResult(name = "isComuneAventeCodiceIstatAbilitatoSigmaterReturn", targetNamespace = "urn:sigalfsrvGenerali")
    public boolean isComuneAventeCodiceIstatAbilitatoSigmater(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvGenerali")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvGenerali")
        String in1
    ) throws UnrecoverableException_Exception, CSIException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoIdentificativiComunePerNomeComune", targetNamespace = "urn:sigalfsrvGenerali", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali.CercaElencoIdentificativiComunePerNomeComune")
    @ResponseWrapper(localName = "cercaElencoIdentificativiComunePerNomeComuneResponse", targetNamespace = "urn:sigalfsrvGenerali", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali.CercaElencoIdentificativiComunePerNomeComuneResponse")
    @WebResult(name = "cercaElencoIdentificativiComunePerNomeComuneReturn", targetNamespace = "urn:sigalfsrvGenerali")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali.IdentificativoComune> cercaElencoIdentificativiComunePerNomeComune(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvGenerali")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvGenerali")
        boolean in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvGenerali")
        String in2
    ) throws UnrecoverableException_Exception, CSIException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoComuni", targetNamespace = "urn:sigalfsrvGenerali", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali.CercaElencoComuni")
    @ResponseWrapper(localName = "cercaElencoComuniResponse", targetNamespace = "urn:sigalfsrvGenerali", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali.CercaElencoComuniResponse")
    @WebResult(name = "cercaElencoComuniReturn", targetNamespace = "urn:sigalfsrvGenerali")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali.IdentificativoComune> cercaElencoComuni(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvGenerali")
        String in0
    ) throws UnrecoverableException_Exception, CSIException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoComuniPerCodIstatProvincia", targetNamespace = "urn:sigalfsrvGenerali", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali.CercaElencoComuniPerCodIstatProvincia")
    @ResponseWrapper(localName = "cercaElencoComuniPerCodIstatProvinciaResponse", targetNamespace = "urn:sigalfsrvGenerali", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali.CercaElencoComuniPerCodIstatProvinciaResponse")
    @WebResult(name = "cercaElencoComuniPerCodIstatProvinciaReturn", targetNamespace = "urn:sigalfsrvGenerali")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali.IdentificativoComune> cercaElencoComuniPerCodIstatProvincia(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvGenerali")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvGenerali")
        String in1
    ) throws UnrecoverableException_Exception, CSIException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoIdentificativiComunePerCodiceIstat", targetNamespace = "urn:sigalfsrvGenerali", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali.CercaElencoIdentificativiComunePerCodiceIstat")
    @ResponseWrapper(localName = "cercaElencoIdentificativiComunePerCodiceIstatResponse", targetNamespace = "urn:sigalfsrvGenerali", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali.CercaElencoIdentificativiComunePerCodiceIstatResponse")
    @WebResult(name = "cercaElencoIdentificativiComunePerCodiceIstatReturn", targetNamespace = "urn:sigalfsrvGenerali")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali.IdentificativoComune> cercaElencoIdentificativiComunePerCodiceIstat(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvGenerali")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvGenerali")
        String in1
    ) throws UnrecoverableException_Exception, CSIException_Exception, SystemException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isComuneAventeCodiceBelfioreAbilitatoSigmater", targetNamespace = "urn:sigalfsrvGenerali", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali.IsComuneAventeCodiceBelfioreAbilitatoSigmater")
    @ResponseWrapper(localName = "isComuneAventeCodiceBelfioreAbilitatoSigmaterResponse", targetNamespace = "urn:sigalfsrvGenerali", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali.IsComuneAventeCodiceBelfioreAbilitatoSigmaterResponse")
    @WebResult(name = "isComuneAventeCodiceBelfioreAbilitatoSigmaterReturn", targetNamespace = "urn:sigalfsrvGenerali")
    public boolean isComuneAventeCodiceBelfioreAbilitatoSigmater(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvGenerali")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvGenerali")
        String in1
    ) throws UnrecoverableException_Exception, CSIException_Exception, SystemException_Exception;
}
