/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.generali;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-07-14T15:53:09.235+02:00
 * Generated source version: 3.5.1
 *
 */
@WebServiceClient(name = "sigalfsrvGeneraliService",
                  wsdlLocation = "file:wsdl/sigalfsrvGenerali.wsdl",
                  targetNamespace = "urn:sigalfsrvGenerali")
public class SigalfsrvGeneraliService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sigalfsrvGenerali", "sigalfsrvGeneraliService");
    public final static QName SigalfsrvGenerali = new QName("urn:sigalfsrvGenerali", "sigalfsrvGenerali");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/sigalfsrvGenerali.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SigalfsrvGeneraliService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:wsdl/sigalfsrvGenerali.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SigalfsrvGeneraliService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SigalfsrvGeneraliService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SigalfsrvGeneraliService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     *     returns SigalfsrvGenerali
     */
    @WebEndpoint(name = "sigalfsrvGenerali")
    public SigalfsrvGenerali getSigalfsrvGenerali() {
        return super.getPort(SigalfsrvGenerali, SigalfsrvGenerali.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.

     *     returns SigalfsrvGenerali
     */
    @WebEndpoint(name = "sigalfsrvGenerali")
    public SigalfsrvGenerali getSigalfsrvGenerali(WebServiceFeature... features) {
        return super.getPort(SigalfsrvGenerali, SigalfsrvGenerali.class, features);
    }

}
