/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T10:17:05.136+01:00
 * Generated source version: 3.2.2
 *
*/

package it.csi.mudeopen.mudeopensrvsoap.business.be.web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.servlet.http.HttpServletRequest;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.HttpHeaders;
import javax.ws.rs.core.SecurityContext;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.springframework.stereotype.Component;

import it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.CodiceFiscaleObbligatorioException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.FruitoreDisabilitatoException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.FruitoreNoComuniAssociatiException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.SystemException_Exception;
@WebService(targetNamespace = "http://autenticazione.interfacews.mudesrvextsic.mude.csi.it/", name = "Autenticazione")
//@XmlSeeAlso({ObjectFactory.class})
public interface Autenticazione {

    @WebMethod
    @RequestWrapper(localName = "autenticazioneMUDE", targetNamespace = "http://autenticazione.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.AutenticazioneMUDE")
    @ResponseWrapper(localName = "autenticazioneMUDEResponse", targetNamespace = "http://autenticazione.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.autenticazione.AutenticazioneMUDEResponse")
    @WebResult(name = "result", targetNamespace = "")
    public String autenticazioneMUDE(
        @WebParam(name = "codiceFiscale", targetNamespace = "")
        String codiceFiscale,
        @Context SecurityContext securityContext, @Context HttpHeaders httpHeaders, @Context HttpServletRequest httpRequest
    ) throws CodiceFiscaleObbligatorioException_Exception, FruitoreNoComuniAssociatiException_Exception, SystemException_Exception, FruitoreDisabilitatoException_Exception;
}
