/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.business.be.web;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.Allegato;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.CampoObbligatorioException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ComuneInsesistenteException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ComuneNonAbilitatoException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.DatiModificaStatoIstanza;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.DatiSintesiIstanza;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.DatiXML;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.DocumentoNonValidoException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.DocumentoPA;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.EsitoRicercaPaginata03;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.FiltroRicercaPaginata;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.FruitoreNonAbilitatoComuneException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.IdentificativoIstanza;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.InserimentoNotifica;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.IstanzaNonConsultabileException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.IstanzaNonTrovataException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.MittenteNonAbilitatoFunzioneException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.NotAuthorizedException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.Notifica;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.NotificaElenco;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.NumeroTicketInesistente_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ObjectFactory;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.PassaggioStatoImpossibileException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.Pratica;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.PraticaAssociataAdAltraIstanzaException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.PraticaDiAltroFascicoloException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.PraticaEsistenteException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaDocumentiPraticaFiltro;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaPraticheFiltro;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaStatiAmmessi;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.Ruolo;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.StatoInesistenteException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.StatoIstanza;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.StatoIstanzaConsultazioneException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.StatoIstanzaDesc;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.StatoIstanzaNonValidoModificaException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.SystemException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.TipoDocumento;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.TipoNotifica;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.TipoNotificaInesistenteException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.TipoNotificaUgualeACambiaStatoException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.UnrecoverableException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ValoreNonAmmessoException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.VisualizzazioneNotificaCerca;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-24T17:55:41.464+01:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", name = "Gestionale")
@XmlSeeAlso({ObjectFactory.class})
//@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Gestionale {
    @WebMethod
    @RequestWrapper(localName = "modificaStatoIstanza", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ModificaStatoIstanza")
    @ResponseWrapper(localName = "modificaStatoIstanzaResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ModificaStatoIstanzaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public boolean modificaStatoIstanza(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "datiModifica", targetNamespace = "")
        DatiModificaStatoIstanza datiModifica
    ) throws SystemException_Exception, PassaggioStatoImpossibileException_Exception, PraticaEsistenteException_Exception, IstanzaNonTrovataException_Exception, FruitoreNonAbilitatoComuneException_Exception, PraticaAssociataAdAltraIstanzaException_Exception, PraticaDiAltroFascicoloException_Exception, ComuneNonAbilitatoException_Exception, NumeroTicketInesistente_Exception, UnrecoverableException_Exception, ValoreNonAmmessoException_Exception, StatoInesistenteException_Exception, StatoIstanzaNonValidoModificaException_Exception, CampoObbligatorioException_Exception, NotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaElencoAllegati", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaElencoAllegati")
    @ResponseWrapper(localName = "ricercaElencoAllegatiResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaElencoAllegatiResponse")
    @WebResult(name = "result", targetNamespace = "")
    public List<Allegato> ricercaElencoAllegati(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "identificativoIstanza", targetNamespace = "")
        IdentificativoIstanza identificativoIstanza
    ) throws SystemException_Exception, ComuneNonAbilitatoException_Exception, NumeroTicketInesistente_Exception, FruitoreNonAbilitatoComuneException_Exception, CampoObbligatorioException_Exception, NotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaStatiIstanza", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaStatiIstanza")
    @ResponseWrapper(localName = "ricercaStatiIstanzaResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaStatiIstanzaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public List<StatoIstanzaDesc> ricercaStatiIstanza(
        @WebParam(name = "token", targetNamespace = "")
        String token
    ) throws SystemException_Exception, NumeroTicketInesistente_Exception, NotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaTipoNotifica", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaTipoNotifica")
    @ResponseWrapper(localName = "ricercaTipoNotificaResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaTipoNotificaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public List<TipoNotifica> ricercaTipoNotifica(
        @WebParam(name = "token", targetNamespace = "")
        String token
    ) throws SystemException_Exception, NumeroTicketInesistente_Exception, NotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaDatiSintesiIstanza", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaDatiSintesiIstanza")
    @ResponseWrapper(localName = "ricercaDatiSintesiIstanzaResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaDatiSintesiIstanzaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public DatiSintesiIstanza ricercaDatiSintesiIstanza(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "filtro", targetNamespace = "")
        IdentificativoIstanza filtro
    ) throws SystemException_Exception, ComuneNonAbilitatoException_Exception, NumeroTicketInesistente_Exception, FruitoreNonAbilitatoComuneException_Exception, CampoObbligatorioException_Exception, NotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "elencoNotificheInviate", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ElencoNotificheInviate")
    @ResponseWrapper(localName = "elencoNotificheInviateResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ElencoNotificheInviateResponse")
    @WebResult(name = "result", targetNamespace = "")
    public List<NotificaElenco> elencoNotificheInviate(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "identificativoIstanza", targetNamespace = "")
        IdentificativoIstanza identificativoIstanza
    ) throws SystemException_Exception, ComuneNonAbilitatoException_Exception, NumeroTicketInesistente_Exception, FruitoreNonAbilitatoComuneException_Exception, CampoObbligatorioException_Exception, NotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "scaricoXML", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ScaricoXML")
    @ResponseWrapper(localName = "scaricoXMLResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ScaricoXMLResponse")
    @WebResult(name = "result", targetNamespace = "")
    public DatiXML scaricoXML(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "identificativoIstanza", targetNamespace = "")
        IdentificativoIstanza identificativoIstanza,
        @WebParam(name = "codiceTipoTracciato", targetNamespace = "")
        String codiceTipoTracciato
    ) throws SystemException_Exception, ComuneNonAbilitatoException_Exception, IstanzaNonConsultabileException_Exception, NumeroTicketInesistente_Exception, IstanzaNonTrovataException_Exception, FruitoreNonAbilitatoComuneException_Exception, CampoObbligatorioException_Exception, NotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaTipoDocumento", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaTipoDocumento")
    @ResponseWrapper(localName = "ricercaTipoDocumentoResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaTipoDocumentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public List<TipoDocumento> ricercaTipoDocumento(
        @WebParam(name = "token", targetNamespace = "")
        String token
    ) throws SystemException_Exception, NumeroTicketInesistente_Exception, NotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaRuoli", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaRuoli")
    @ResponseWrapper(localName = "ricercaRuoliResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaRuoliResponse")
    @WebResult(name = "result", targetNamespace = "")
    public List<Ruolo> ricercaRuoli(
        @WebParam(name = "token", targetNamespace = "")
        String token
    ) throws SystemException_Exception, NumeroTicketInesistente_Exception, NotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaElencoDocumentiPratica", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaElencoDocumentiPratica")
    @ResponseWrapper(localName = "ricercaElencoDocumentiPraticaResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaElencoDocumentiPraticaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public List<DocumentoPA> ricercaElencoDocumentiPratica(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "filtro", targetNamespace = "")
        RicercaDocumentiPraticaFiltro filtro
    ) throws SystemException_Exception, ComuneNonAbilitatoException_Exception, NumeroTicketInesistente_Exception, FruitoreNonAbilitatoComuneException_Exception, CampoObbligatorioException_Exception, ComuneInsesistenteException_Exception, NotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "visualizzazioneNotifica", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.VisualizzazioneNotifica")
    @ResponseWrapper(localName = "visualizzazioneNotificaResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.VisualizzazioneNotificaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public Notifica visualizzazioneNotifica(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "filtro", targetNamespace = "")
        VisualizzazioneNotificaCerca filtro
    ) throws SystemException_Exception, ComuneNonAbilitatoException_Exception, NumeroTicketInesistente_Exception, FruitoreNonAbilitatoComuneException_Exception, CampoObbligatorioException_Exception, NotAuthorizedException_Exception;

    @WebMethod(operationName = "ricercaPaginataIstanze03")
    @RequestWrapper(localName = "ricercaPaginataIstanze03", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaPaginataIstanze03")
    @ResponseWrapper(localName = "ricercaPaginataIstanze03Response", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaPaginataIstanze03Response")
    @WebResult(name = "result", targetNamespace = "")
    public EsitoRicercaPaginata03 ricercaPaginataIstanze03(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "filtro", targetNamespace = "")
        FiltroRicercaPaginata filtro
    ) throws SystemException_Exception, ComuneNonAbilitatoException_Exception, NumeroTicketInesistente_Exception, ValoreNonAmmessoException_Exception, StatoInesistenteException_Exception, FruitoreNonAbilitatoComuneException_Exception, CampoObbligatorioException_Exception, NotAuthorizedException_Exception, StatoIstanzaConsultazioneException_Exception;

    @WebMethod
    @RequestWrapper(localName = "elencoAllegatiNotifica", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ElencoAllegatiNotifica")
    @ResponseWrapper(localName = "elencoAllegatiNotificaResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ElencoAllegatiNotificaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public List<DocumentoPA> elencoAllegatiNotifica(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "identificativoIstanza", targetNamespace = "")
        VisualizzazioneNotificaCerca identificativoIstanza
    ) throws SystemException_Exception, ComuneNonAbilitatoException_Exception, NumeroTicketInesistente_Exception, FruitoreNonAbilitatoComuneException_Exception, CampoObbligatorioException_Exception, NotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaStatiIstanzaAmmessi", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaStatiIstanzaAmmessi")
    @ResponseWrapper(localName = "ricercaStatiIstanzaAmmessiResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaStatiIstanzaAmmessiResponse")
    @WebResult(name = "result", targetNamespace = "")
    public List<StatoIstanza> ricercaStatiIstanzaAmmessi(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "identificativo", targetNamespace = "")
        RicercaStatiAmmessi identificativo
    ) throws SystemException_Exception, NumeroTicketInesistente_Exception, PassaggioStatoImpossibileException_Exception, StatoInesistenteException_Exception, CampoObbligatorioException_Exception, NotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaPratiche", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaPratiche")
    @ResponseWrapper(localName = "ricercaPraticheResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaPraticheResponse")
    @WebResult(name = "result", targetNamespace = "")
    public List<Pratica> ricercaPratiche(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "filtro", targetNamespace = "")
        RicercaPraticheFiltro filtro
    ) throws SystemException_Exception, ComuneNonAbilitatoException_Exception, NumeroTicketInesistente_Exception, FruitoreNonAbilitatoComuneException_Exception, CampoObbligatorioException_Exception, ComuneInsesistenteException_Exception, NotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "inserisciNotifica", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.InserisciNotifica")
    @ResponseWrapper(localName = "inserisciNotificaResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.InserisciNotificaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public long inserisciNotifica(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "notificaDaInserire", targetNamespace = "")
        InserimentoNotifica notificaDaInserire
    ) throws SystemException_Exception, DocumentoNonValidoException_Exception, IstanzaNonTrovataException_Exception, FruitoreNonAbilitatoComuneException_Exception, ComuneNonAbilitatoException_Exception, IstanzaNonConsultabileException_Exception, NumeroTicketInesistente_Exception, TipoNotificaUgualeACambiaStatoException_Exception, CampoObbligatorioException_Exception, MittenteNonAbilitatoFunzioneException_Exception, TipoNotificaInesistenteException_Exception, NotAuthorizedException_Exception;

    /*
	// ***********************************************************
	// FROM MUDE WSLD: NOT TO BE IMPLEMENTED
	// ***********************************************************
	
    @WebMethod
    @RequestWrapper(localName = "ricercaIstanze", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaIstanze")
    @ResponseWrapper(localName = "ricercaIstanzeResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaIstanzeResponse")
    @WebResult(name = "result", targetNamespace = "")
    public List<Istanza> ricercaIstanze(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "filtro", targetNamespace = "")
        RicercaIstanza filtro
    ) throws SystemException_Exception, ComuneNonAbilitatoException_Exception, NumeroTicketInesistente_Exception, ValoreNonAmmessoException_Exception, StatoInesistenteException_Exception, FruitoreNonAbilitatoComuneException_Exception, CampoObbligatorioException_Exception, NotAuthorizedException_Exception, StatoIstanzaConsultazioneException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaEstesaIstanze", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaEstesaIstanze")
    @ResponseWrapper(localName = "ricercaEstesaIstanzeResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaEstesaIstanzeResponse")
    @WebResult(name = "result", targetNamespace = "")
    public List<IstanzaEstesa> ricercaEstesaIstanze(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "filtro", targetNamespace = "")
        RicercaIstanzaEstesa filtro
    ) throws SystemException_Exception, ComuneNonAbilitatoException_Exception, NumeroTicketInesistente_Exception, ValoreNonAmmessoException_Exception, StatoInesistenteException_Exception, FruitoreNonAbilitatoComuneException_Exception, CampoObbligatorioException_Exception, NotAuthorizedException_Exception, StatoIstanzaConsultazioneException_Exception, TooManyRecordsException_Exception;

    @WebMethod
    @RequestWrapper(localName = "scaricoXMLIstanza", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ScaricoXMLIstanza")
    @ResponseWrapper(localName = "scaricoXMLIstanzaResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ScaricoXMLIstanzaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public DatiXMLIstanza scaricoXMLIstanza(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "identificativoIstanza", targetNamespace = "")
        IdentificativoIstanza identificativoIstanza
    ) throws SystemException_Exception, ComuneNonAbilitatoException_Exception, IstanzaNonConsultabileException_Exception, NumeroTicketInesistente_Exception, FruitoreNonAbilitatoComuneException_Exception, CampoObbligatorioException_Exception, NotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaPaginataIstanze", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaPaginataIstanze")
    @ResponseWrapper(localName = "ricercaPaginataIstanzeResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaPaginataIstanzeResponse")
    @WebResult(name = "result", targetNamespace = "")
    public EsitoRicercaPaginata ricercaPaginataIstanze(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "filtro", targetNamespace = "")
        FiltroRicercaPaginata filtro
    ) throws SystemException_Exception, ComuneNonAbilitatoException_Exception, NumeroTicketInesistente_Exception, ValoreNonAmmessoException_Exception, StatoInesistenteException_Exception, FruitoreNonAbilitatoComuneException_Exception, CampoObbligatorioException_Exception, NotAuthorizedException_Exception, StatoIstanzaConsultazioneException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ricercaPaginataIstanze02", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaPaginataIstanze02")
    @ResponseWrapper(localName = "ricercaPaginataIstanze02Response", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaPaginataIstanze02Response")
    @WebResult(name = "result", targetNamespace = "")
    public EsitoRicercaPaginata02 ricercaPaginataIstanze02(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "filtro", targetNamespace = "")
        FiltroRicercaPaginata filtro
    ) throws SystemException_Exception, ComuneNonAbilitatoException_Exception, NumeroTicketInesistente_Exception, ValoreNonAmmessoException_Exception, StatoInesistenteException_Exception, FruitoreNonAbilitatoComuneException_Exception, CampoObbligatorioException_Exception, NotAuthorizedException_Exception, StatoIstanzaConsultazioneException_Exception;

    @WebMethod
    @RequestWrapper(localName = "scaricoXMLUnico", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ScaricoXMLUnico")
    @ResponseWrapper(localName = "scaricoXMLUnicoResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ScaricoXMLUnicoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public DatiXMLUnico scaricoXMLUnico(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "identificativoIstanza", targetNamespace = "")
        IdentificativoIstanza identificativoIstanza
    ) throws SystemException_Exception, ComuneNonAbilitatoException_Exception, IstanzaNonConsultabileException_Exception, NumeroTicketInesistente_Exception, FruitoreNonAbilitatoComuneException_Exception, CampoObbligatorioException_Exception, NotAuthorizedException_Exception;
	// ***********************************************************
	// NOT PRESENT EVEN IN MUDE DOCUMENTS: NOT TO BE IMPLEMENTED
	// ***********************************************************
	
    @WebMethod
    @RequestWrapper(localName = "ricercaCronologiaStatiIstaza", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaCronologiaStatiIstaza")
    @ResponseWrapper(localName = "ricercaCronologiaStatiIstazaResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.RicercaCronologiaStatiIstazaResponse")
    @WebResult(name = "result", targetNamespace = "")
    public List<CronologiaStatoIstanza> ricercaCronologiaStatiIstaza(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "identificativoIstanza", targetNamespace = "")
        IdentificativoIstanza identificativoIstanza
    ) throws SystemException_Exception, ComuneNonAbilitatoException_Exception, NumeroTicketInesistente_Exception, FruitoreNonAbilitatoComuneException_Exception, CampoObbligatorioException_Exception, NotAuthorizedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "elencoGeoRiferimento", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ElencoGeoRiferimento")
    @ResponseWrapper(localName = "elencoGeoRiferimentoResponse", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale.ElencoGeoRiferimentoResponse")
    @WebResult(name = "result", targetNamespace = "")
    public List<GeoRiferimento> elencoGeoRiferimento(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "numeroMude", targetNamespace = "")
        String numeroMude
    ) throws NumeroTicketInesistente_Exception, GeoriferimentoNonTrovatoException_Exception;
	
	*/

}
