/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.business.be.web;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import it.csi.mudeopen.mudeopensrvsoap.interfacews.itfcsitorino.GeoRiferimento;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.itfcsitorino.NumeroTicketInesistente_Exception;
import it.csi.mudeopen.mudeopensrvsoap.interfacews.itfcsitorino.SystemException_Exception;
import it.csi.mudeopen.mudeopensrvsoap.vo.Allegato;
import it.csi.mudeopen.mudeopensrvsoap.vo.IstanzaMude;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.968+01:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://itfcsitorino.interfacews.mudesrvextsic.mude.csi.it/", name = "ItfCsiTorino")

public interface ItfCsiTorino {

	@Produces({ MediaType.APPLICATION_XML })
    @WebMethod(action = "")
    List<Allegato> getElencoAllegatiByNumeroIstanza (@WebParam(name = "token") String token, 
    		@WebParam(name = "numeroIstanza") String numeroIstanza
    									) throws NumeroTicketInesistente_Exception,
										SystemException_Exception;
	
	@Produces({ MediaType.APPLICATION_XML })
    @WebMethod(action = "")
	IstanzaMude estraiIstanzaMude (@WebParam(name = "token") String token, 
    		@WebParam(name = "numeroIstanza") String numeroIstanza
    									) throws NumeroTicketInesistente_Exception,
										SystemException_Exception;
	
	
	@Produces({ MediaType.APPLICATION_XML })
    @WebMethod(action = "")
	List<GeoRiferimento> getElencoGeoRiferimento (@WebParam(name = "token") String token, 
    		@WebParam(name = "numeroIstanza") String numeroIstanza
    									) throws NumeroTicketInesistente_Exception,
										SystemException_Exception;
	

}
