/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.documenti;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.090+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "AllegatoNonTrovatoException", messageName = "AllegatoNonTrovatoException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class AllegatoNonTrovatoException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private AllegatoNonTrovatoException AllegatoNonTrovatoException;
    public AllegatoNonTrovatoException_Exception() {
        super();
    }
	public AllegatoNonTrovatoException_Exception(String message) {
		super(message);
		this.AllegatoNonTrovatoException = new AllegatoNonTrovatoException();
	}
    public AllegatoNonTrovatoException_Exception(String message, Throwable cause) {
        super(message, cause);
    }
    public AllegatoNonTrovatoException_Exception(String message, AllegatoNonTrovatoException AllegatoNonTrovatoException) {
        super(message);
        this.AllegatoNonTrovatoException = AllegatoNonTrovatoException;
    }
    public AllegatoNonTrovatoException_Exception(String message, AllegatoNonTrovatoException AllegatoNonTrovatoException, Throwable cause) {
        super(message, cause);
        this.AllegatoNonTrovatoException = AllegatoNonTrovatoException;
    }
    public AllegatoNonTrovatoException getFaultInfo() {
        return this.AllegatoNonTrovatoException;
    }
}
