/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.documenti;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.067+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "PraticaEsistenteException", messageName = "PraticaEsistenteException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class PraticaEsistenteException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private PraticaEsistenteException praticaEsistenteException;
    public PraticaEsistenteException_Exception() {
        super();
    }
	public PraticaEsistenteException_Exception(String message) {
		super(message);
		this.praticaEsistenteException = new PraticaEsistenteException();
	}
    public PraticaEsistenteException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.praticaEsistenteException = new PraticaEsistenteException();
    }
    public PraticaEsistenteException_Exception(String message, PraticaEsistenteException praticaEsistenteException) {
        super(message);
        this.praticaEsistenteException = praticaEsistenteException;
    }
    public PraticaEsistenteException_Exception(String message, PraticaEsistenteException praticaEsistenteException, Throwable cause) {
        super(message, cause);
        this.praticaEsistenteException = praticaEsistenteException;
    }
    public PraticaEsistenteException getFaultInfo() {
        return this.praticaEsistenteException;
    }
}
