/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.documenti;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.090+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "StatoIstanzaNonValidoException", messageName = "StatoIstanzaNonValidoException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class StatoIstanzaNonValidoException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private StatoIstanzaNonValidoException StatoIstanzaNonValidoException;
    public StatoIstanzaNonValidoException_Exception() {
        super();
    }
	public StatoIstanzaNonValidoException_Exception(String message) {
		super(message);
		this.StatoIstanzaNonValidoException = new StatoIstanzaNonValidoException();
	}
    public StatoIstanzaNonValidoException_Exception(String message, Throwable cause) {
        super(message, cause);
    }
    public StatoIstanzaNonValidoException_Exception(String message, StatoIstanzaNonValidoException StatoIstanzaNonValidoException) {
        super(message);
        this.StatoIstanzaNonValidoException = StatoIstanzaNonValidoException;
    }
    public StatoIstanzaNonValidoException_Exception(String message, StatoIstanzaNonValidoException StatoIstanzaNonValidoException, Throwable cause) {
        super(message, cause);
        this.StatoIstanzaNonValidoException = StatoIstanzaNonValidoException;
    }
    public StatoIstanzaNonValidoException getFaultInfo() {
        return this.StatoIstanzaNonValidoException;
    }
}
