/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.documenti;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T10:17:05.109+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "SystemException", messageName = "SystemException", targetNamespace = "http://autenticazione.interfacews.mudesrvextsic.mude.csi.it/")
public class SystemException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private SystemException systemException;
    public SystemException_Exception() {
        super();
    }
	public SystemException_Exception(String message) {
		super(message);
		this.systemException = new SystemException();
	}
    public SystemException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.systemException = new SystemException();
    }
    public SystemException_Exception(String message, SystemException systemException) {
        super(message);
        this.systemException = systemException;
    }
    public SystemException_Exception(String message, SystemException systemException, Throwable cause) {
        super(message, cause);
        this.systemException = systemException;
    }
    public SystemException getFaultInfo() {
        return this.systemException;
    }
}
