/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.csi.mudeopen.mudeopensrvcommon.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

@ApiModel(description = "Informazioni per il confronto con il nodo temporaneo.")
@javax.annotation.Generated(value = "it.csi.mudeopen.mudeopensrvcommon.business.be.helper.cosmo.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class CompareDigestRequest {
    @JsonProperty("nodeInfo")
    private NodeInfo nodeInfo = null;

    @JsonProperty("tempNodeInfo")
    private NodeInfo tempNodeInfo = null;

    public CompareDigestRequest nodeInfo(NodeInfo nodeInfo) {
        this.nodeInfo = nodeInfo;
        return this;
    }

    @ApiModelProperty(value = "")
    public NodeInfo getNodeInfo() {
        return nodeInfo;
    }

    public void setNodeInfo(NodeInfo nodeInfo) {
        this.nodeInfo = nodeInfo;
    }

    public CompareDigestRequest tempNodeInfo(NodeInfo tempNodeInfo) {
        this.tempNodeInfo = tempNodeInfo;
        return this;
    }

    @ApiModelProperty(value = "")
    public NodeInfo getTempNodeInfo() {
        return tempNodeInfo;
    }

    public void setTempNodeInfo(NodeInfo tempNodeInfo) {
        this.tempNodeInfo = tempNodeInfo;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CompareDigestRequest compareDigestRequest = (CompareDigestRequest) o;
        return Objects.equals(this.nodeInfo, compareDigestRequest.nodeInfo) &&
                Objects.equals(this.tempNodeInfo, compareDigestRequest.tempNodeInfo);
    }

    @Override
    public int hashCode() {
        return Objects.hash(nodeInfo, tempNodeInfo);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CompareDigestRequest {\n");

        sb.append("    nodeInfo: ").append(toIndentedString(nodeInfo)).append("\n");
        sb.append("    tempNodeInfo: ").append(toIndentedString(tempNodeInfo)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}