/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.csi.mudeopen.mudeopensrvcommon.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

@ApiModel(description = "Modello personalizzato dei dati.")
@javax.annotation.Generated(value = "it.csi.mudeopen.mudeopensrvcommon.business.be.helper.cosmo.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class CustomModel {
    @JsonProperty("prefixedName")
    private String prefixedName = null;

    @JsonProperty("title")
    private String title = null;

    @JsonProperty("description")
    private String description = null;

    @JsonProperty("filename")
    private String filename = null;

    @JsonProperty("active")
    private Boolean active = null;

    public CustomModel prefixedName(String prefixedName) {
        this.prefixedName = prefixedName;
        return this;
    }

    @ApiModelProperty(example = "test:model", value = "Prefixed name dell'elemento.")
    public String getPrefixedName() {
        return prefixedName;
    }

    public void setPrefixedName(String prefixedName) {
        this.prefixedName = prefixedName;
    }

    public CustomModel title(String title) {
        this.title = title;
        return this;
    }

    @ApiModelProperty(example = "TEST MODEL", value = "Titolo dell'elemento.")
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public CustomModel description(String description) {
        this.description = description;
        return this;
    }

    @ApiModelProperty(example = "TEST MODEL", value = "Descrizione dell'elemento.")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public CustomModel filename(String filename) {
        this.filename = filename;
        return this;
    }

    @ApiModelProperty(example = "test.xml", value = "Nome del file del modello.")
    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public CustomModel active(Boolean active) {
        this.active = active;
        return this;
    }

    @ApiModelProperty(value = "Imposta se il modello à attivo oppure no.")
    public Boolean isActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CustomModel customModel = (CustomModel) o;
        return Objects.equals(this.prefixedName, customModel.prefixedName) &&
                Objects.equals(this.title, customModel.title) &&
                Objects.equals(this.description, customModel.description) &&
                Objects.equals(this.filename, customModel.filename) &&
                Objects.equals(this.active, customModel.active);
    }

    @Override
    public int hashCode() {
        return Objects.hash(prefixedName, title, description, filename, active);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CustomModel {\n");

        sb.append("    prefixedName: ").append(toIndentedString(prefixedName)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
        sb.append("    active: ").append(toIndentedString(active)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}