/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.csi.mudeopen.mudeopensrvcommon.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

@ApiModel(description = "Informazioni sulla destinazione della copia")
@javax.annotation.Generated(value = "it.csi.mudeopen.mudeopensrvcommon.business.be.helper.cosmo.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class DestinationInfo {
    @JsonProperty("parentDestinationUid")
    private String parentDestinationUid = null;

    @JsonProperty("operationContext")
    private OperationContext operationContext = null;

    public DestinationInfo parentDestinationUid(String parentDestinationUid) {
        this.parentDestinationUid = parentDestinationUid;
        return this;
    }

    @ApiModelProperty(example = "2bc43299-1ea4-11eb-9204-9f3a5004d33a", value = "UID del nodo padre di destinazione della copia.")
    public String getParentDestinationUid() {
        return parentDestinationUid;
    }

    public void setParentDestinationUid(String parentDestinationUid) {
        this.parentDestinationUid = parentDestinationUid;
    }

    public DestinationInfo operationContext(OperationContext operationContext) {
        this.operationContext = operationContext;
        return this;
    }

    @ApiModelProperty(value = "")
    public OperationContext getOperationContext() {
        return operationContext;
    }

    public void setOperationContext(OperationContext operationContext) {
        this.operationContext = operationContext;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DestinationInfo destinationInfo = (DestinationInfo) o;
        return Objects.equals(this.parentDestinationUid, destinationInfo.parentDestinationUid) &&
                Objects.equals(this.operationContext, destinationInfo.operationContext);
    }

    @Override
    public int hashCode() {
        return Objects.hash(parentDestinationUid, operationContext);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DestinationInfo {\n");

        sb.append("    parentDestinationUid: ").append(toIndentedString(parentDestinationUid)).append("\n");
        sb.append("    operationContext: ").append(toIndentedString(operationContext)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}