/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.csi.mudeopen.mudeopensrvcommon.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

@ApiModel(description = "Messaggio di errore dei servizi.")
@javax.annotation.Generated(value = "it.csi.mudeopen.mudeopensrvcommon.business.be.helper.cosmo.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ErrorMessage {
    @JsonProperty("status")
    private Integer status = null;

    @JsonProperty("code")
    private String code = null;

    @JsonProperty("title")
    private String title = null;

    @JsonProperty("detail")
    private List<ErrorDetail> detail = null;

    @JsonProperty("links")
    private List<String> links = null;

    public ErrorMessage status(Integer status) {
        this.status = status;
        return this;
    }

    @ApiModelProperty(value = "Codice di errore HTTP.")
    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public ErrorMessage code(String code) {
        this.code = code;
        return this;
    }

    @ApiModelProperty(value = "Codice di errore in formato stringa.")
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public ErrorMessage title(String title) {
        this.title = title;
        return this;
    }

    @ApiModelProperty(value = "Descrizione sintetica dell\\'errore.")
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public ErrorMessage detail(List<ErrorDetail> detail) {
        this.detail = detail;
        return this;
    }

    public ErrorMessage addDetailItem(ErrorDetail detailItem) {
        if (this.detail == null) {
            this.detail = new ArrayList<ErrorDetail>();
        }
        this.detail.add(detailItem);
        return this;
    }

    @ApiModelProperty(value = "Dettagli aggiuntivi sull\\'errore.")
    public List<ErrorDetail> getDetail() {
        return detail;
    }

    public void setDetail(List<ErrorDetail> detail) {
        this.detail = detail;
    }

    public ErrorMessage links(List<String> links) {
        this.links = links;
        return this;
    }

    public ErrorMessage addLinksItem(String linksItem) {
        if (this.links == null) {
            this.links = new ArrayList<String>();
        }
        this.links.add(linksItem);
        return this;
    }

    @ApiModelProperty(value = "Lista di URI per contenuti aggiuntivi sull\\'errore.")
    public List<String> getLinks() {
        return links;
    }

    public void setLinks(List<String> links) {
        this.links = links;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ErrorMessage errorMessage = (ErrorMessage) o;
        return Objects.equals(this.status, errorMessage.status) &&
                Objects.equals(this.code, errorMessage.code) &&
                Objects.equals(this.title, errorMessage.title) &&
                Objects.equals(this.detail, errorMessage.detail) &&
                Objects.equals(this.links, errorMessage.links);
    }

    @Override
    public int hashCode() {
        return Objects.hash(status, code, title, detail, links);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ErrorMessage {\n");

        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
        sb.append("    links: ").append(toIndentedString(links)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}