/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.csi.mudeopen.mudeopensrvcommon.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

@ApiModel(description = "Risultato del riconoscimento del formato di un contenuto binario.")
@javax.annotation.Generated(value = "it.csi.mudeopen.mudeopensrvcommon.business.be.helper.cosmo.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class FileFormatInfo {
    @JsonProperty("puid")
    private String puid = null;

    @JsonProperty("mimeType")
    private String mimeType = null;

    @JsonProperty("description")
    private String description = null;

    @JsonProperty("formatVersion")
    private String formatVersion = null;

    @JsonProperty("typeCode")
    private Integer typeCode = null;

    @JsonProperty("typeDescription")
    private String typeDescription = null;

    @JsonProperty("warning")
    private String warning = null;

    @JsonProperty("identificationDate")
    private String identificationDate = null;

    @JsonProperty("uid")
    private String uid = null;

    @JsonProperty("typeExtension")
    private String typeExtension = null;

    public FileFormatInfo puid(String puid) {
        this.puid = puid;
        return this;
    }

    @ApiModelProperty(example = "fmt/276", value = "PUID associato al tipo di file riconosciuto.")
    public String getPuid() {
        return puid;
    }

    public void setPuid(String puid) {
        this.puid = puid;
    }

    public FileFormatInfo mimeType(String mimeType) {
        this.mimeType = mimeType;
        return this;
    }

    @ApiModelProperty(example = "application/pdf", value = "MIME type.")
    public String getMimeType() {
        return mimeType;
    }

    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    public FileFormatInfo description(String description) {
        this.description = description;
        return this;
    }

    @ApiModelProperty(example = "Acrobat PDF 1.7 - Portable Document Format", value = "Esito del processo di identificazione.")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public FileFormatInfo formatVersion(String formatVersion) {
        this.formatVersion = formatVersion;
        return this;
    }

    @ApiModelProperty(example = "1.7", value = "Versione del formato riconosciuto.")
    public String getFormatVersion() {
        return formatVersion;
    }

    public void setFormatVersion(String formatVersion) {
        this.formatVersion = formatVersion;
    }

    public FileFormatInfo typeCode(Integer typeCode) {
        this.typeCode = typeCode;
        return this;
    }

    @ApiModelProperty(example = "10", value = "Codice di tipo associato al formato.")
    public Integer getTypeCode() {
        return typeCode;
    }

    public void setTypeCode(Integer typeCode) {
        this.typeCode = typeCode;
    }

    public FileFormatInfo typeDescription(String typeDescription) {
        this.typeDescription = typeDescription;
        return this;
    }

    @ApiModelProperty(example = "posistive-specific", value = "Esito del processo di identificazione.")
    public String getTypeDescription() {
        return typeDescription;
    }

    public void setTypeDescription(String typeDescription) {
        this.typeDescription = typeDescription;
    }

    public FileFormatInfo warning(String warning) {
        this.warning = warning;
        return this;
    }

    @ApiModelProperty(value = "Eventuali informazioni aggiuntive sul riconoscimento.")
    public String getWarning() {
        return warning;
    }

    public void setWarning(String warning) {
        this.warning = warning;
    }

    public FileFormatInfo identificationDate(String identificationDate) {
        this.identificationDate = identificationDate;
        return this;
    }

    @ApiModelProperty(example = "2020-11-19T14:32:59.163+0000", value = "Timestamp del riconoscimento.")
    public String getIdentificationDate() {
        return identificationDate;
    }

    public void setIdentificationDate(String identificationDate) {
        this.identificationDate = identificationDate;
    }

    public FileFormatInfo uid(String uid) {
        this.uid = uid;
        return this;
    }

    @ApiModelProperty(example = "1f2d08fd-2a74-11eb-9691-b7b00e8a99a0", value = "Eventuale UID del nodo associato al riconoscimento.")
    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public FileFormatInfo typeExtension(String typeExtension) {
        this.typeExtension = typeExtension;
        return this;
    }

    @ApiModelProperty(example = "pdf", value = "Estensione del formato riconosciuto.")
    public String getTypeExtension() {
        return typeExtension;
    }

    public void setTypeExtension(String typeExtension) {
        this.typeExtension = typeExtension;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FileFormatInfo fileFormatInfo = (FileFormatInfo) o;
        return Objects.equals(this.puid, fileFormatInfo.puid) &&
                Objects.equals(this.mimeType, fileFormatInfo.mimeType) &&
                Objects.equals(this.description, fileFormatInfo.description) &&
                Objects.equals(this.formatVersion, fileFormatInfo.formatVersion) &&
                Objects.equals(this.typeCode, fileFormatInfo.typeCode) &&
                Objects.equals(this.typeDescription, fileFormatInfo.typeDescription) &&
                Objects.equals(this.warning, fileFormatInfo.warning) &&
                Objects.equals(this.identificationDate, fileFormatInfo.identificationDate) &&
                Objects.equals(this.uid, fileFormatInfo.uid) &&
                Objects.equals(this.typeExtension, fileFormatInfo.typeExtension);
    }

    @Override
    public int hashCode() {
        return Objects.hash(puid, mimeType, description, formatVersion, typeCode, typeDescription, warning, identificationDate, uid, typeExtension);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class FileFormatInfo {\n");

        sb.append("    puid: ").append(toIndentedString(puid)).append("\n");
        sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    formatVersion: ").append(toIndentedString(formatVersion)).append("\n");
        sb.append("    typeCode: ").append(toIndentedString(typeCode)).append("\n");
        sb.append("    typeDescription: ").append(toIndentedString(typeDescription)).append("\n");
        sb.append("    warning: ").append(toIndentedString(warning)).append("\n");
        sb.append("    identificationDate: ").append(toIndentedString(identificationDate)).append("\n");
        sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
        sb.append("    typeExtension: ").append(toIndentedString(typeExtension)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}