/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.csi.mudeopen.mudeopensrvcommon.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

@ApiModel(description = "Dettagli sulla nuova associazione e tipo di operazione (modalità asincrona).")
@javax.annotation.Generated(value = "it.csi.mudeopen.mudeopensrvcommon.business.be.helper.cosmo.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ModifyAssociationJobRequest {

    public enum ActionEnum {
        MOVEJOB("moveJob"),

        LINKJOB("linkJob");

        private String value;

        ActionEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static ActionEnum fromValue(String text) {
            for (ActionEnum b : ActionEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }
    }

    @JsonProperty("action")
    private ActionEnum action = null;

    @JsonProperty("association")
    private Association association = null;

    public ModifyAssociationJobRequest action(ActionEnum action) {
        this.action = action;
        return this;
    }

    @ApiModelProperty(value = "valori ammessi per action:  * moveJob -  Effettua una richiesta di spostamento di un nodo asincrona.  * linkJob - Effettua una richiesta di link di un nodo asincrona. ")
    public ActionEnum getAction() {
        return action;
    }

    public void setAction(ActionEnum action) {
        this.action = action;
    }

    public ModifyAssociationJobRequest association(Association association) {
        this.association = association;
        return this;
    }

    @ApiModelProperty(value = "")
    public Association getAssociation() {
        return association;
    }

    public void setAssociation(Association association) {
        this.association = association;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ModifyAssociationJobRequest modifyAssociationJobRequest = (ModifyAssociationJobRequest) o;
        return Objects.equals(this.action, modifyAssociationJobRequest.action) &&
                Objects.equals(this.association, modifyAssociationJobRequest.association);
    }

    @Override
    public int hashCode() {
        return Objects.hash(action, association);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ModifyAssociationJobRequest {\n");

        sb.append("    action: ").append(toIndentedString(action)).append("\n");
        sb.append("    association: ").append(toIndentedString(association)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}