/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.csi.mudeopen.mudeopensrvcommon.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

@ApiModel(description = "Informazioni per il confronto tra nodi.")
@javax.annotation.Generated(value = "it.csi.mudeopen.mudeopensrvcommon.business.be.helper.cosmo.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class NodeInfo {
    @JsonProperty("uid")
    private String uid = null;

    @JsonProperty("contentPropertyName")
    private String contentPropertyName = null;

    @JsonProperty("enveloped")
    private Boolean enveloped = null;

    public NodeInfo uid(String uid) {
        this.uid = uid;
        return this;
    }

    @ApiModelProperty(value = "UUID del nodo.")
    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public NodeInfo contentPropertyName(String contentPropertyName) {
        this.contentPropertyName = contentPropertyName;
        return this;
    }

    @ApiModelProperty(value = "Il nome della proprietà di tipo cm:content che contiene il contenuto binario.")
    public String getContentPropertyName() {
        return contentPropertyName;
    }

    public void setContentPropertyName(String contentPropertyName) {
        this.contentPropertyName = contentPropertyName;
    }

    public NodeInfo enveloped(Boolean enveloped) {
        this.enveloped = enveloped;
        return this;
    }

    @ApiModelProperty(value = "Imposta se il nodo è imbustato.")
    public Boolean isEnveloped() {
        return enveloped;
    }

    public void setEnveloped(Boolean enveloped) {
        this.enveloped = enveloped;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        NodeInfo nodeInfo = (NodeInfo) o;
        return Objects.equals(this.uid, nodeInfo.uid) &&
                Objects.equals(this.contentPropertyName, nodeInfo.contentPropertyName) &&
                Objects.equals(this.enveloped, nodeInfo.enveloped);
    }

    @Override
    public int hashCode() {
        return Objects.hash(uid, contentPropertyName, enveloped);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class NodeInfo {\n");

        sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
        sb.append("    contentPropertyName: ").append(toIndentedString(contentPropertyName)).append("\n");
        sb.append("    enveloped: ").append(toIndentedString(enveloped)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}