/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.csi.mudeopen.mudeopensrvcommon.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

@ApiModel(description = "Contiene le informazioni di autenticazione da utilizzare per l'invocazione dei servizi.")
@javax.annotation.Generated(value = "it.csi.mudeopen.mudeopensrvcommon.business.be.helper.cosmo.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class OperationContext {
    @JsonProperty("username")
    private String username = null;

    @JsonProperty("password")
    private String password = null;

    @JsonProperty("repository")
    private String repository = null;

    @JsonProperty("tenant")
    private String tenant = null;

    @JsonProperty("fruitore")
    private String fruitore = null;

    @JsonProperty("nomeFisico")
    private String nomeFisico = null;

    public OperationContext username(String username) {
        this.username = username;
        return this;
    }

    @ApiModelProperty(example = "user", value = "Username dell'utente applicativo.")
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public OperationContext password(String password) {
        this.password = password;
        return this;
    }

    @ApiModelProperty(example = "12345", value = "Password dell'utente applicativo.")
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public OperationContext repository(String repository) {
        this.repository = repository;
        return this;
    }

    @ApiModelProperty(example = "primary", value = "Repository fisico (primary o secondary).")
    public String getRepository() {
        return repository;
    }

    public void setRepository(String repository) {
        this.repository = repository;
    }

    public OperationContext tenant(String tenant) {
        this.tenant = tenant;
        return this;
    }

    @ApiModelProperty(example = "test", value = "Tenant di destinazione.")
    public String getTenant() {
        return tenant;
    }

    public void setTenant(String tenant) {
        this.tenant = tenant;
    }

    public OperationContext fruitore(String fruitore) {
        this.fruitore = fruitore;
        return this;
    }

    @ApiModelProperty(example = "test", value = "")
    public String getFruitore() {
        return fruitore;
    }

    public void setFruitore(String fruitore) {
        this.fruitore = fruitore;
    }

    public OperationContext nomeFisico(String nomeFisico) {
        this.nomeFisico = nomeFisico;
        return this;
    }

    @ApiModelProperty(example = "admin@TEST", value = "")
    public String getNomeFisico() {
        return nomeFisico;
    }

    public void setNomeFisico(String nomeFisico) {
        this.nomeFisico = nomeFisico;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OperationContext operationContext = (OperationContext) o;
        return Objects.equals(this.username, operationContext.username) &&
                Objects.equals(this.password, operationContext.password) &&
                Objects.equals(this.repository, operationContext.repository) &&
                Objects.equals(this.tenant, operationContext.tenant) &&
                Objects.equals(this.fruitore, operationContext.fruitore) &&
                Objects.equals(this.nomeFisico, operationContext.nomeFisico);
    }

    @Override
    public int hashCode() {
        return Objects.hash(username, password, repository, tenant, fruitore, nomeFisico);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OperationContext {\n");

        sb.append("    username: ").append(toIndentedString(username)).append("\n");
        sb.append("    password: ").append(toIndentedString(password)).append("\n");
        sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
        sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
        sb.append("    fruitore: ").append(toIndentedString(fruitore)).append("\n");
        sb.append("    nomeFisico: ").append(toIndentedString(nomeFisico)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}