/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.csi.mudeopen.mudeopensrvcommon.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

@ApiModel(description = "Rappresenta una proprietà.")
@javax.annotation.Generated(value = "it.csi.mudeopen.mudeopensrvcommon.business.be.helper.cosmo.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Property {
    @JsonProperty("prefixedName")
    private String prefixedName = null;

    @JsonProperty("multivalue")
    private Boolean multivalue = null;

    @JsonProperty("dataType")
    private String dataType = null;

    @JsonProperty("values")
    private List<String> values = null;

    @JsonProperty("relativeAspectPrefixedName")
    private String relativeAspectPrefixedName = null;

    public Property prefixedName(String prefixedName) {
        this.prefixedName = prefixedName;
        return this;
    }

    @ApiModelProperty(example = "cm:name", value = "Prefixed name dell'eventuale aspetto che contiene la proprietà.")
    public String getPrefixedName() {
        return prefixedName;
    }

    public void setPrefixedName(String prefixedName) {
        this.prefixedName = prefixedName;
    }

    public Property multivalue(Boolean multivalue) {
        this.multivalue = multivalue;
        return this;
    }

    @ApiModelProperty(value = "Indica se la proprietà è multivalore oppure no.")
    public Boolean isMultivalue() {
        return multivalue;
    }

    public void setMultivalue(Boolean multivalue) {
        this.multivalue = multivalue;
    }

    public Property dataType(String dataType) {
        this.dataType = dataType;
        return this;
    }

    @ApiModelProperty(example = "d:text", value = "Tipo della proprietà.")
    public String getDataType() {
        return dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public Property values(List<String> values) {
        this.values = values;
        return this;
    }

    public Property addValuesItem(String valuesItem) {
        if (this.values == null) {
            this.values = new ArrayList<String>();
        }
        this.values.add(valuesItem);
        return this;
    }

    @ApiModelProperty(value = "Valori della proprietà.")
    public List<String> getValues() {
        return values;
    }

    public void setValues(List<String> values) {
        this.values = values;
    }

    public Property relativeAspectPrefixedName(String relativeAspectPrefixedName) {
        this.relativeAspectPrefixedName = relativeAspectPrefixedName;
        return this;
    }

    @ApiModelProperty(value = "Prefixed name dell'eventuale aspetto che contiene la proprietà.")
    public String getRelativeAspectPrefixedName() {
        return relativeAspectPrefixedName;
    }

    public void setRelativeAspectPrefixedName(String relativeAspectPrefixedName) {
        this.relativeAspectPrefixedName = relativeAspectPrefixedName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Property property = (Property) o;
        return Objects.equals(this.prefixedName, property.prefixedName) &&
                Objects.equals(this.multivalue, property.multivalue) &&
                Objects.equals(this.dataType, property.dataType) &&
                Objects.equals(this.values, property.values) &&
                Objects.equals(this.relativeAspectPrefixedName, property.relativeAspectPrefixedName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(prefixedName, multivalue, dataType, values, relativeAspectPrefixedName);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Property {\n");

        sb.append("    prefixedName: ").append(toIndentedString(prefixedName)).append("\n");
        sb.append("    multivalue: ").append(toIndentedString(multivalue)).append("\n");
        sb.append("    dataType: ").append(toIndentedString(dataType)).append("\n");
        sb.append("    values: ").append(toIndentedString(values)).append("\n");
        sb.append("    relativeAspectPrefixedName: ").append(toIndentedString(relativeAspectPrefixedName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}