/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.csi.mudeopen.mudeopensrvcommon.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

@ApiModel(description = "Definizione di una proprietà del modello dei dati.")
@javax.annotation.Generated(value = "it.csi.mudeopen.mudeopensrvcommon.business.be.helper.cosmo.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class PropertyMetadata {
    @JsonProperty("prefixedName")
    private String prefixedName = null;

    @JsonProperty("title")
    private String title = null;

    @JsonProperty("description")
    private String description = null;

    @JsonProperty("modelDescriptor")
    private ModelDescriptor modelDescriptor = null;

    @JsonProperty("dataType")
    private String dataType = null;

    @JsonProperty("mandatory")
    private Boolean mandatory = null;

    @JsonProperty("multiValued")
    private Boolean multiValued = null;

    @JsonProperty("modifiable")
    private Boolean modifiable = null;

    public PropertyMetadata prefixedName(String prefixedName) {
        this.prefixedName = prefixedName;
        return this;
    }

    @ApiModelProperty(example = "sys:node-uuid", value = "Prefixed name dell'elemento.")
    public String getPrefixedName() {
        return prefixedName;
    }

    public void setPrefixedName(String prefixedName) {
        this.prefixedName = prefixedName;
    }

    public PropertyMetadata title(String title) {
        this.title = title;
        return this;
    }

    @ApiModelProperty(example = "Node Identifier", value = "Titolo dell'elemento.")
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public PropertyMetadata description(String description) {
        this.description = description;
        return this;
    }

    @ApiModelProperty(value = "Descrizione dell'elemento.")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public PropertyMetadata modelDescriptor(ModelDescriptor modelDescriptor) {
        this.modelDescriptor = modelDescriptor;
        return this;
    }

    @ApiModelProperty(value = "")
    public ModelDescriptor getModelDescriptor() {
        return modelDescriptor;
    }

    public void setModelDescriptor(ModelDescriptor modelDescriptor) {
        this.modelDescriptor = modelDescriptor;
    }

    public PropertyMetadata dataType(String dataType) {
        this.dataType = dataType;
        return this;
    }

    @ApiModelProperty(example = "d:text", value = "Tipo della proprietà.")
    public String getDataType() {
        return dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public PropertyMetadata mandatory(Boolean mandatory) {
        this.mandatory = mandatory;
        return this;
    }

    @ApiModelProperty(value = "Indica se la proprietà è obbligatoria oppure no.")
    public Boolean isMandatory() {
        return mandatory;
    }

    public void setMandatory(Boolean mandatory) {
        this.mandatory = mandatory;
    }

    public PropertyMetadata multiValued(Boolean multiValued) {
        this.multiValued = multiValued;
        return this;
    }

    @ApiModelProperty(value = "Indica se la proprietà è multivalore oppure no.")
    public Boolean isMultiValued() {
        return multiValued;
    }

    public void setMultiValued(Boolean multiValued) {
        this.multiValued = multiValued;
    }

    public PropertyMetadata modifiable(Boolean modifiable) {
        this.modifiable = modifiable;
        return this;
    }

    @ApiModelProperty(value = "Indica se la proprietà è modificabile oppure no.")
    public Boolean isModifiable() {
        return modifiable;
    }

    public void setModifiable(Boolean modifiable) {
        this.modifiable = modifiable;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PropertyMetadata propertyMetadata = (PropertyMetadata) o;
        return Objects.equals(this.prefixedName, propertyMetadata.prefixedName) &&
                Objects.equals(this.title, propertyMetadata.title) &&
                Objects.equals(this.description, propertyMetadata.description) &&
                Objects.equals(this.modelDescriptor, propertyMetadata.modelDescriptor) &&
                Objects.equals(this.dataType, propertyMetadata.dataType) &&
                Objects.equals(this.mandatory, propertyMetadata.mandatory) &&
                Objects.equals(this.multiValued, propertyMetadata.multiValued) &&
                Objects.equals(this.modifiable, propertyMetadata.modifiable);
    }

    @Override
    public int hashCode() {
        return Objects.hash(prefixedName, title, description, modelDescriptor, dataType, mandatory, multiValued, modifiable);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PropertyMetadata {\n");

        sb.append("    prefixedName: ").append(toIndentedString(prefixedName)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    modelDescriptor: ").append(toIndentedString(modelDescriptor)).append("\n");
        sb.append("    dataType: ").append(toIndentedString(dataType)).append("\n");
        sb.append("    mandatory: ").append(toIndentedString(mandatory)).append("\n");
        sb.append("    multiValued: ").append(toIndentedString(multiValued)).append("\n");
        sb.append("    modifiable: ").append(toIndentedString(modifiable)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}