/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.csi.mudeopen.mudeopensrvcommon.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

@ApiModel(description = "Informazioni per la creazione di un link di condivisione di un documento.")
@javax.annotation.Generated(value = "it.csi.mudeopen.mudeopensrvcommon.business.be.helper.cosmo.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class SharingInfo {
    @JsonProperty("sharedLink")
    private String sharedLink = null;

    @JsonProperty("contentPropertyPrefixedName")
    private String contentPropertyPrefixedName = null;

    @JsonProperty("source")
    private String source = null;

    @JsonProperty("fromDate")
    private String fromDate = null;

    @JsonProperty("toDate")
    private String toDate = null;

    @JsonProperty("resultContentDisposition")
    private String resultContentDisposition = null;

    @JsonProperty("resultPropertyPrefixedName")
    private String resultPropertyPrefixedName = null;

    public SharingInfo sharedLink(String sharedLink) {
        this.sharedLink = sharedLink;
        return this;
    }

    @ApiModelProperty(example = "http://tst-jboss-01.csi.it:22310/ecmenginecxf-test/http/download/cHJpbWFyeXx0ZW1wfDhlOTcyMTNkNmM3MzExZWJiOGUyYzkwY2M3ZTBhMDZkfDE2MTMwNTI5MTQ2NTJ8MjY1NTY3Mw", value = "Url della condivisione.")
    public String getSharedLink() {
        return sharedLink;
    }

    public void setSharedLink(String sharedLink) {
        this.sharedLink = sharedLink;
    }

    public SharingInfo contentPropertyPrefixedName(String contentPropertyPrefixedName) {
        this.contentPropertyPrefixedName = contentPropertyPrefixedName;
        return this;
    }

    @ApiModelProperty(example = "cm:content", value = "Prefixed name della proprietà che rappresenta il contenuto binario del nodo.")
    public String getContentPropertyPrefixedName() {
        return contentPropertyPrefixedName;
    }

    public void setContentPropertyPrefixedName(String contentPropertyPrefixedName) {
        this.contentPropertyPrefixedName = contentPropertyPrefixedName;
    }

    public SharingInfo source(String source) {
        this.source = source;
        return this;
    }

    @ApiModelProperty(example = "intranet", value = "Origine del link Valori :    >      intranet1 esposizione interna (http)      intranet2 esposizione interna (https)      internet eposizione INTERNET (https). ")
    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public SharingInfo fromDate(String fromDate) {
        this.fromDate = fromDate;
        return this;
    }

    @ApiModelProperty(example = "2020-12-16T13:59:56.986+01:00", value = "Data di inizio validità del link.")
    public String getFromDate() {
        return fromDate;
    }

    public void setFromDate(String fromDate) {
        this.fromDate = fromDate;
    }

    public SharingInfo toDate(String toDate) {
        this.toDate = toDate;
        return this;
    }

    @ApiModelProperty(example = "2020-12-16T13:59:56.986+01:00", value = "Data di termine validita' del link.")
    public String getToDate() {
        return toDate;
    }

    public void setToDate(String toDate) {
        this.toDate = toDate;
    }

    public SharingInfo resultContentDisposition(String resultContentDisposition) {
        this.resultContentDisposition = resultContentDisposition;
        return this;
    }

    @ApiModelProperty(value = "Specifica il Content-Disposition in uscita (per uso client).")
    public String getResultContentDisposition() {
        return resultContentDisposition;
    }

    public void setResultContentDisposition(String resultContentDisposition) {
        this.resultContentDisposition = resultContentDisposition;
    }

    public SharingInfo resultPropertyPrefixedName(String resultPropertyPrefixedName) {
        this.resultPropertyPrefixedName = resultPropertyPrefixedName;
        return this;
    }

    @ApiModelProperty(value = "Prefixed name della proprietà che contenente il nome del file.")
    public String getResultPropertyPrefixedName() {
        return resultPropertyPrefixedName;
    }

    public void setResultPropertyPrefixedName(String resultPropertyPrefixedName) {
        this.resultPropertyPrefixedName = resultPropertyPrefixedName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SharingInfo sharingInfo = (SharingInfo) o;
        return Objects.equals(this.sharedLink, sharingInfo.sharedLink) &&
                Objects.equals(this.contentPropertyPrefixedName, sharingInfo.contentPropertyPrefixedName) &&
                Objects.equals(this.source, sharingInfo.source) &&
                Objects.equals(this.fromDate, sharingInfo.fromDate) &&
                Objects.equals(this.toDate, sharingInfo.toDate) &&
                Objects.equals(this.resultContentDisposition, sharingInfo.resultContentDisposition) &&
                Objects.equals(this.resultPropertyPrefixedName, sharingInfo.resultPropertyPrefixedName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(sharedLink, contentPropertyPrefixedName, source, fromDate, toDate, resultContentDisposition, resultPropertyPrefixedName);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SharingInfo {\n");

        sb.append("    sharedLink: ").append(toIndentedString(sharedLink)).append("\n");
        sb.append("    contentPropertyPrefixedName: ").append(toIndentedString(contentPropertyPrefixedName)).append("\n");
        sb.append("    source: ").append(toIndentedString(source)).append("\n");
        sb.append("    fromDate: ").append(toIndentedString(fromDate)).append("\n");
        sb.append("    toDate: ").append(toIndentedString(toDate)).append("\n");
        sb.append("    resultContentDisposition: ").append(toIndentedString(resultContentDisposition)).append("\n");
        sb.append("    resultPropertyPrefixedName: ").append(toIndentedString(resultPropertyPrefixedName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}