/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.csi.mudeopen.mudeopensrvcommon.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

@ApiModel(description = "Rappresenta una firma digitale.")
@javax.annotation.Generated(value = "it.csi.mudeopen.mudeopensrvcommon.business.be.helper.cosmo.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Signature {
  @JsonProperty("signature")
  private List<Signature> signature = null;

  @JsonProperty("annoFirma")
  private Integer annoFirma = null;

  @JsonProperty("ca")
  private String ca = null;

  @JsonProperty("cert")
  private byte[] cert = null;

  @JsonProperty("codiceFiscale")
  private String codiceFiscale = null;

  @JsonProperty("dataOra")
  private String dataOra = null;

  @JsonProperty("dataOraVerifica")
  private String dataOraVerifica = null;

  @JsonProperty("dipartimento")
  private String dipartimento = null;

  @JsonProperty("dnQualifier")
  private String dnQualifier = null;

  @JsonProperty("errorCode")
  private Integer errorCode = null;

  @JsonProperty("fineValidita")
  private String fineValidita = null;

  @JsonProperty("firmatario")
  private String firmatario = null;

  @JsonProperty("giornoFirma")
  private Integer giornoFirma = null;

  @JsonProperty("givenname")
  private String givenname = null;

  @JsonProperty("inizioValidita")
  private String inizioValidita = null;

  @JsonProperty("meseFirma")
  private Integer meseFirma = null;

  @JsonProperty("minutiFirma")
  private Integer minutiFirma = null;

  @JsonProperty("nominativoFirmatario")
  private String nominativoFirmatario = null;

  @JsonProperty("numeroControfirme")
  private Integer numeroControfirme = null;

  @JsonProperty("oraFirma")
  private Integer oraFirma = null;

  @JsonProperty("organizzazione")
  private String organizzazione = null;

  @JsonProperty("paese")
  private String paese = null;

  @JsonProperty("secondiFirma")
  private Integer secondiFirma = null;

  @JsonProperty("serialNumber")
  private String serialNumber = null;

  @JsonProperty("surname")
  private String surname = null;

  @JsonProperty("timestamped")
  private Boolean timestamped = null;

  @JsonProperty("tipoCertificato")
  private Integer tipoCertificato = null;

  @JsonProperty("tipoFirma")
  private Integer tipoFirma = null;

    public Signature signature(List<Signature> signature) {
    this.signature = signature;
    return this;
  }

    public Signature addSignatureItem(Signature signatureItem) {
    if (this.signature == null) {
      this.signature = new ArrayList<Signature>();
    }
    this.signature.add(signatureItem);
    return this;
  }

    @ApiModelProperty(value = "Elenco delle controfirme.")
  public List<Signature> getSignature() {
    return signature;
  }

    public void setSignature(List<Signature> signature) {
    this.signature = signature;
  }

    public Signature annoFirma(Integer annoFirma) {
    this.annoFirma = annoFirma;
    return this;
  }

    @ApiModelProperty(example = "2020", value = "Anno della firma.")
  public Integer getAnnoFirma() {
    return annoFirma;
  }

    public void setAnnoFirma(Integer annoFirma) {
    this.annoFirma = annoFirma;
  }

    public Signature ca(String ca) {
    this.ca = ca;
    return this;
  }

    @ApiModelProperty(example = "ArubaPEC EU Qualified Certificates CA G1", value = "Certification authority.")
  public String getCa() {
    return ca;
  }

    public void setCa(String ca) {
    this.ca = ca;
  }

    public Signature cert(byte[] cert) {
    this.cert = cert;
    return this;
  }

    @ApiModelProperty(example = "Ynl0ZXM=", value = "Certificato di firma codificato in base64.")
  public byte[] getCert() {
    return cert;
  }

    public void setCert(byte[] cert) {
    this.cert = cert;
  }

    public Signature codiceFiscale(String codiceFiscale) {
    this.codiceFiscale = codiceFiscale;
    return this;
  }

    @ApiModelProperty(example = "RSSMRA34839200039L220S", value = "Codice fiscale del firmatario.")
  public String getCodiceFiscale() {
    return codiceFiscale;
  }

    public void setCodiceFiscale(String codiceFiscale) {
    this.codiceFiscale = codiceFiscale;
  }

    public Signature dataOra(String dataOra) {
    this.dataOra = dataOra;
    return this;
  }

    @ApiModelProperty(example = "2018-04-09T14:15:29.000+0000", value = "Data e l'ora della firma.")
  public String getDataOra() {
    return dataOra;
  }

    public void setDataOra(String dataOra) {
    this.dataOra = dataOra;
  }

    public Signature dataOraVerifica(String dataOraVerifica) {
    this.dataOraVerifica = dataOraVerifica;
    return this;
  }

    @ApiModelProperty(example = "25/02/2021 15:18:20", value = "Data e ora del rapporto di verifica nel formato gg/mm/aaaa hh:mm:ss.")
  public String getDataOraVerifica() {
    return dataOraVerifica;
  }

    public void setDataOraVerifica(String dataOraVerifica) {
    this.dataOraVerifica = dataOraVerifica;
  }

    public Signature dipartimento(String dipartimento) {
    this.dipartimento = dipartimento;
    return this;
  }

    @ApiModelProperty(value = "Dipartimento.")
  public String getDipartimento() {
    return dipartimento;
  }

    public void setDipartimento(String dipartimento) {
    this.dipartimento = dipartimento;
  }

    public Signature dnQualifier(String dnQualifier) {
    this.dnQualifier = dnQualifier;
    return this;
  }

    @ApiModelProperty(example = "WSREF-69794445239940", value = "Dnqualifier del firmatario.")
  public String getDnQualifier() {
    return dnQualifier;
  }

    public void setDnQualifier(String dnQualifier) {
    this.dnQualifier = dnQualifier;
  }

    public Signature errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

    @ApiModelProperty(example = "4", value = "Eventuale codice di errore della verifica della firma.")
  public Integer getErrorCode() {
    return errorCode;
  }

    public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

    public Signature fineValidita(String fineValidita) {
    this.fineValidita = fineValidita;
    return this;
  }

    @ApiModelProperty(example = "Feb 19 17:06:55 2020", value = "Data di fine di validità della firma.")
  public String getFineValidita() {
    return fineValidita;
  }

    public void setFineValidita(String fineValidita) {
    this.fineValidita = fineValidita;
  }

    public Signature firmatario(String firmatario) {
    this.firmatario = firmatario;
    return this;
  }

    @ApiModelProperty(example = "ROSSI MARIO", value = "Firmatario.")
  public String getFirmatario() {
    return firmatario;
  }

    public void setFirmatario(String firmatario) {
    this.firmatario = firmatario;
  }

    public Signature giornoFirma(Integer giornoFirma) {
    this.giornoFirma = giornoFirma;
    return this;
  }

    @ApiModelProperty(example = "15", value = "Giorno della firma.")
  public Integer getGiornoFirma() {
    return giornoFirma;
  }

    public void setGiornoFirma(Integer giornoFirma) {
    this.giornoFirma = giornoFirma;
  }

    public Signature givenname(String givenname) {
    this.givenname = givenname;
    return this;
  }

    @ApiModelProperty(example = "Mario", value = "Nome del firmatario.")
  public String getGivenname() {
    return givenname;
  }

    public void setGivenname(String givenname) {
    this.givenname = givenname;
  }

    public Signature inizioValidita(String inizioValidita) {
    this.inizioValidita = inizioValidita;
    return this;
  }

    @ApiModelProperty(example = "Feb 19 17:06:55 2018", value = "Data di inizio di validità della firma.")
  public String getInizioValidita() {
    return inizioValidita;
  }

    public void setInizioValidita(String inizioValidita) {
    this.inizioValidita = inizioValidita;
  }

    public Signature meseFirma(Integer meseFirma) {
    this.meseFirma = meseFirma;
    return this;
  }

    @ApiModelProperty(example = "0", value = "Mese della firma.")
  public Integer getMeseFirma() {
    return meseFirma;
  }

    public void setMeseFirma(Integer meseFirma) {
    this.meseFirma = meseFirma;
  }

    public Signature minutiFirma(Integer minutiFirma) {
    this.minutiFirma = minutiFirma;
    return this;
  }

    @ApiModelProperty(example = "4", value = "Minuti della firma.")
  public Integer getMinutiFirma() {
    return minutiFirma;
  }

    public void setMinutiFirma(Integer minutiFirma) {
    this.minutiFirma = minutiFirma;
  }

    public Signature nominativoFirmatario(String nominativoFirmatario) {
    this.nominativoFirmatario = nominativoFirmatario;
    return this;
  }

    @ApiModelProperty(example = "MARIO ROSSI", value = "Nominativo del firmatario.")
  public String getNominativoFirmatario() {
    return nominativoFirmatario;
  }

    public void setNominativoFirmatario(String nominativoFirmatario) {
    this.nominativoFirmatario = nominativoFirmatario;
  }

    public Signature numeroControfirme(Integer numeroControfirme) {
    this.numeroControfirme = numeroControfirme;
    return this;
  }

    @ApiModelProperty(example = "1", value = "Numero di controfirme del file.")
  public Integer getNumeroControfirme() {
    return numeroControfirme;
  }

    public void setNumeroControfirme(Integer numeroControfirme) {
    this.numeroControfirme = numeroControfirme;
  }

    public Signature oraFirma(Integer oraFirma) {
    this.oraFirma = oraFirma;
    return this;
  }

    @ApiModelProperty(example = "23", value = "Ora della firma.")
  public Integer getOraFirma() {
    return oraFirma;
  }

    public void setOraFirma(Integer oraFirma) {
    this.oraFirma = oraFirma;
  }

    public Signature organizzazione(String organizzazione) {
    this.organizzazione = organizzazione;
    return this;
  }

    @ApiModelProperty(value = "Organizzazione del firmatario.")
  public String getOrganizzazione() {
    return organizzazione;
  }

    public void setOrganizzazione(String organizzazione) {
    this.organizzazione = organizzazione;
  }

    public Signature paese(String paese) {
    this.paese = paese;
    return this;
  }

    @ApiModelProperty(example = "IT", value = "Paese del firmatario.")
  public String getPaese() {
    return paese;
  }

    public void setPaese(String paese) {
    this.paese = paese;
  }

    public Signature secondiFirma(Integer secondiFirma) {
    this.secondiFirma = secondiFirma;
    return this;
  }

    @ApiModelProperty(example = "34", value = "Secondi della firma.")
  public Integer getSecondiFirma() {
    return secondiFirma;
  }

    public void setSecondiFirma(Integer secondiFirma) {
    this.secondiFirma = secondiFirma;
  }

    public Signature serialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
    return this;
  }

    @ApiModelProperty(example = "TINIT-ROSSMA61D15L219L", value = "Serial number del firmatario.")
  public String getSerialNumber() {
    return serialNumber;
  }

    public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }

    public Signature surname(String surname) {
    this.surname = surname;
    return this;
  }

    @ApiModelProperty(example = "ROSSI", value = "Cognome del firmatario.")
  public String getSurname() {
    return surname;
  }

    public void setSurname(String surname) {
    this.surname = surname;
  }

    public Signature timestamped(Boolean timestamped) {
    this.timestamped = timestamped;
    return this;
  }

    @ApiModelProperty(value = "Imposta se la firma è fornita di una marcatura temporale.")
  public Boolean isTimestamped() {
    return timestamped;
  }

    public void setTimestamped(Boolean timestamped) {
    this.timestamped = timestamped;
  }

    public Signature tipoCertificato(Integer tipoCertificato) {
    this.tipoCertificato = tipoCertificato;
    return this;
  }

    @ApiModelProperty(example = "1", value = "Imposta il tipo del certificato:  1 in caso di firma  2 in caso di marca temporale. ")
  public Integer getTipoCertificato() {
    return tipoCertificato;
  }

    public void setTipoCertificato(Integer tipoCertificato) {
    this.tipoCertificato = tipoCertificato;
  }

    public Signature tipoFirma(Integer tipoFirma) {
    this.tipoFirma = tipoFirma;
    return this;
  }

    @ApiModelProperty(example = "0", value = "Imposta il tipo della firma.")
  public Integer getTipoFirma() {
    return tipoFirma;
  }

    public void setTipoFirma(Integer tipoFirma) {
    this.tipoFirma = tipoFirma;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Signature signature = (Signature) o;
    return Objects.equals(this.signature, signature.signature) &&
        Objects.equals(this.annoFirma, signature.annoFirma) &&
        Objects.equals(this.ca, signature.ca) &&
        Arrays.equals(this.cert, signature.cert) &&
        Objects.equals(this.codiceFiscale, signature.codiceFiscale) &&
        Objects.equals(this.dataOra, signature.dataOra) &&
        Objects.equals(this.dataOraVerifica, signature.dataOraVerifica) &&
        Objects.equals(this.dipartimento, signature.dipartimento) &&
        Objects.equals(this.dnQualifier, signature.dnQualifier) &&
        Objects.equals(this.errorCode, signature.errorCode) &&
        Objects.equals(this.fineValidita, signature.fineValidita) &&
        Objects.equals(this.firmatario, signature.firmatario) &&
        Objects.equals(this.giornoFirma, signature.giornoFirma) &&
        Objects.equals(this.givenname, signature.givenname) &&
        Objects.equals(this.inizioValidita, signature.inizioValidita) &&
        Objects.equals(this.meseFirma, signature.meseFirma) &&
        Objects.equals(this.minutiFirma, signature.minutiFirma) &&
        Objects.equals(this.nominativoFirmatario, signature.nominativoFirmatario) &&
        Objects.equals(this.numeroControfirme, signature.numeroControfirme) &&
        Objects.equals(this.oraFirma, signature.oraFirma) &&
        Objects.equals(this.organizzazione, signature.organizzazione) &&
        Objects.equals(this.paese, signature.paese) &&
        Objects.equals(this.secondiFirma, signature.secondiFirma) &&
        Objects.equals(this.serialNumber, signature.serialNumber) &&
        Objects.equals(this.surname, signature.surname) &&
        Objects.equals(this.timestamped, signature.timestamped) &&
        Objects.equals(this.tipoCertificato, signature.tipoCertificato) &&
        Objects.equals(this.tipoFirma, signature.tipoFirma);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signature, annoFirma, ca, Arrays.hashCode(cert), codiceFiscale, dataOra, dataOraVerifica, dipartimento, dnQualifier, errorCode, fineValidita, firmatario, giornoFirma, givenname, inizioValidita, meseFirma, minutiFirma, nominativoFirmatario, numeroControfirme, oraFirma, organizzazione, paese, secondiFirma, serialNumber, surname, timestamped, tipoCertificato, tipoFirma);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Signature {\n");

    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    annoFirma: ").append(toIndentedString(annoFirma)).append("\n");
    sb.append("    ca: ").append(toIndentedString(ca)).append("\n");
    sb.append("    cert: ").append(toIndentedString(cert)).append("\n");
    sb.append("    codiceFiscale: ").append(toIndentedString(codiceFiscale)).append("\n");
    sb.append("    dataOra: ").append(toIndentedString(dataOra)).append("\n");
    sb.append("    dataOraVerifica: ").append(toIndentedString(dataOraVerifica)).append("\n");
    sb.append("    dipartimento: ").append(toIndentedString(dipartimento)).append("\n");
    sb.append("    dnQualifier: ").append(toIndentedString(dnQualifier)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    fineValidita: ").append(toIndentedString(fineValidita)).append("\n");
    sb.append("    firmatario: ").append(toIndentedString(firmatario)).append("\n");
    sb.append("    giornoFirma: ").append(toIndentedString(giornoFirma)).append("\n");
    sb.append("    givenname: ").append(toIndentedString(givenname)).append("\n");
    sb.append("    inizioValidita: ").append(toIndentedString(inizioValidita)).append("\n");
    sb.append("    meseFirma: ").append(toIndentedString(meseFirma)).append("\n");
    sb.append("    minutiFirma: ").append(toIndentedString(minutiFirma)).append("\n");
    sb.append("    nominativoFirmatario: ").append(toIndentedString(nominativoFirmatario)).append("\n");
    sb.append("    numeroControfirme: ").append(toIndentedString(numeroControfirme)).append("\n");
    sb.append("    oraFirma: ").append(toIndentedString(oraFirma)).append("\n");
    sb.append("    organizzazione: ").append(toIndentedString(organizzazione)).append("\n");
    sb.append("    paese: ").append(toIndentedString(paese)).append("\n");
    sb.append("    secondiFirma: ").append(toIndentedString(secondiFirma)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    timestamped: ").append(toIndentedString(timestamped)).append("\n");
    sb.append("    tipoCertificato: ").append(toIndentedString(tipoCertificato)).append("\n");
    sb.append("    tipoFirma: ").append(toIndentedString(tipoFirma)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}