/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.csi.mudeopen.mudeopensrvcommon.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

@ApiModel(description = "Rapporto di verifica di un certificato.")
@javax.annotation.Generated(value = "it.csi.mudeopen.mudeopensrvcommon.business.be.helper.cosmo.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class VerifyCertificateReport {
  @JsonProperty("verificationResult")
  private String verificationResult = null;

  @JsonProperty("errorCode")
  private Integer errorCode = null;

  @JsonProperty("errorDescription")
  private String errorDescription = null;

  @JsonProperty("certificationAuthority")
  private String certificationAuthority = null;

  @JsonProperty("serialNumber")
  private String serialNumber = null;

  @JsonProperty("verificationDateTime")
  private String verificationDateTime = null;

  @JsonProperty("validFrom")
  private String validFrom = null;

  @JsonProperty("validTo")
  private String validTo = null;

  @JsonProperty("keyUsage")
  private String keyUsage = null;

  @JsonProperty("revocationDate")
  private String revocationDate = null;

  @JsonProperty("invalidSince")
  private String invalidSince = null;

  @JsonProperty("holdDate")
  private String holdDate = null;

  @JsonProperty("crlExpirationDate")
  private String crlExpirationDate = null;

  @JsonProperty("caCertExpirationDate")
  private String caCertExpirationDate = null;

  @JsonProperty("caCertRevocationDate")
  private String caCertRevocationDate = null;

  @JsonProperty("expiredCertsOnCRL")
  private String expiredCertsOnCRL = null;

  @JsonProperty("subject")
  private String subject = null;

  @JsonProperty("crlDate")
  private String crlDate = null;

  @JsonProperty("issuerAltName")
  private String issuerAltName = null;

  @JsonProperty("keyUsageString")
  private String keyUsageString = null;

  @JsonProperty("uid")
  private String uid = null;

    public VerifyCertificateReport verificationResult(String verificationResult) {
    this.verificationResult = verificationResult;
    return this;
  }

    @ApiModelProperty(value = "Risultato della verifica.")
  public String getVerificationResult() {
    return verificationResult;
  }

    public void setVerificationResult(String verificationResult) {
    this.verificationResult = verificationResult;
  }

    public VerifyCertificateReport errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

    @ApiModelProperty(value = "Eventuale codice di errore.")
  public Integer getErrorCode() {
    return errorCode;
  }

    public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

    public VerifyCertificateReport errorDescription(String errorDescription) {
    this.errorDescription = errorDescription;
    return this;
  }

    @ApiModelProperty(value = "Eventuale desrizione dell'errore")
  public String getErrorDescription() {
    return errorDescription;
  }

    public void setErrorDescription(String errorDescription) {
    this.errorDescription = errorDescription;
  }

    public VerifyCertificateReport certificationAuthority(String certificationAuthority) {
    this.certificationAuthority = certificationAuthority;
    return this;
  }

    @ApiModelProperty(value = "Certification authority.")
  public String getCertificationAuthority() {
    return certificationAuthority;
  }

    public void setCertificationAuthority(String certificationAuthority) {
    this.certificationAuthority = certificationAuthority;
  }

    public VerifyCertificateReport serialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
    return this;
  }

    @ApiModelProperty(value = "Numero seriale.")
  public String getSerialNumber() {
    return serialNumber;
  }

    public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }

    public VerifyCertificateReport verificationDateTime(String verificationDateTime) {
    this.verificationDateTime = verificationDateTime;
    return this;
  }

    @ApiModelProperty(value = "Data e ora della verifica.")
  public String getVerificationDateTime() {
    return verificationDateTime;
  }

    public void setVerificationDateTime(String verificationDateTime) {
    this.verificationDateTime = verificationDateTime;
  }

    public VerifyCertificateReport validFrom(String validFrom) {
    this.validFrom = validFrom;
    return this;
  }

    @ApiModelProperty(value = "Data di inizio validità del certificato.")
  public String getValidFrom() {
    return validFrom;
  }

    public void setValidFrom(String validFrom) {
    this.validFrom = validFrom;
  }

    public VerifyCertificateReport validTo(String validTo) {
    this.validTo = validTo;
    return this;
  }

    @ApiModelProperty(value = "Data di fine validità del certificato.")
  public String getValidTo() {
    return validTo;
  }

    public void setValidTo(String validTo) {
    this.validTo = validTo;
  }

    public VerifyCertificateReport keyUsage(String keyUsage) {
    this.keyUsage = keyUsage;
    return this;
  }

    @ApiModelProperty(value = "Rappresenta la chiave.")
  public String getKeyUsage() {
    return keyUsage;
  }

    public void setKeyUsage(String keyUsage) {
    this.keyUsage = keyUsage;
  }

    public VerifyCertificateReport revocationDate(String revocationDate) {
    this.revocationDate = revocationDate;
    return this;
  }

    @ApiModelProperty(value = "Eventuale data di revoca.")
  public String getRevocationDate() {
    return revocationDate;
  }

    public void setRevocationDate(String revocationDate) {
    this.revocationDate = revocationDate;
  }

    public VerifyCertificateReport invalidSince(String invalidSince) {
    this.invalidSince = invalidSince;
    return this;
  }

    @ApiModelProperty(value = "Eventuale data di non validità.")
  public String getInvalidSince() {
    return invalidSince;
  }

    public void setInvalidSince(String invalidSince) {
    this.invalidSince = invalidSince;
  }

    public VerifyCertificateReport holdDate(String holdDate) {
    this.holdDate = holdDate;
    return this;
  }

    @ApiModelProperty(value = "Eventuale data di trattenuta.")
  public String getHoldDate() {
    return holdDate;
  }

    public void setHoldDate(String holdDate) {
    this.holdDate = holdDate;
  }

    public VerifyCertificateReport crlExpirationDate(String crlExpirationDate) {
    this.crlExpirationDate = crlExpirationDate;
    return this;
  }

    @ApiModelProperty(value = "Data di scadenza della CRL.")
  public String getCrlExpirationDate() {
    return crlExpirationDate;
  }

    public void setCrlExpirationDate(String crlExpirationDate) {
    this.crlExpirationDate = crlExpirationDate;
  }

    public VerifyCertificateReport caCertExpirationDate(String caCertExpirationDate) {
    this.caCertExpirationDate = caCertExpirationDate;
    return this;
  }

    @ApiModelProperty(value = "Data di scadenza dell'autorità certificatrice.")
  public String getCaCertExpirationDate() {
    return caCertExpirationDate;
  }

    public void setCaCertExpirationDate(String caCertExpirationDate) {
    this.caCertExpirationDate = caCertExpirationDate;
  }

    public VerifyCertificateReport caCertRevocationDate(String caCertRevocationDate) {
    this.caCertRevocationDate = caCertRevocationDate;
    return this;
  }

    @ApiModelProperty(value = "Data di revoca dell'autorità certificatrice.")
  public String getCaCertRevocationDate() {
    return caCertRevocationDate;
  }

    public void setCaCertRevocationDate(String caCertRevocationDate) {
    this.caCertRevocationDate = caCertRevocationDate;
  }

    public VerifyCertificateReport expiredCertsOnCRL(String expiredCertsOnCRL) {
    this.expiredCertsOnCRL = expiredCertsOnCRL;
    return this;
  }

    @ApiModelProperty(value = "Certificati scaduti.")
  public String getExpiredCertsOnCRL() {
    return expiredCertsOnCRL;
  }

    public void setExpiredCertsOnCRL(String expiredCertsOnCRL) {
    this.expiredCertsOnCRL = expiredCertsOnCRL;
  }

    public VerifyCertificateReport subject(String subject) {
    this.subject = subject;
    return this;
  }

    @ApiModelProperty(value = "Rappresenta il soggetto.")
  public String getSubject() {
    return subject;
  }

    public void setSubject(String subject) {
    this.subject = subject;
  }

    public VerifyCertificateReport crlDate(String crlDate) {
    this.crlDate = crlDate;
    return this;
  }

    @ApiModelProperty(value = "Data della CRL.")
  public String getCrlDate() {
    return crlDate;
  }

    public void setCrlDate(String crlDate) {
    this.crlDate = crlDate;
  }

    public VerifyCertificateReport issuerAltName(String issuerAltName) {
    this.issuerAltName = issuerAltName;
    return this;
  }

    @ApiModelProperty(value = "Nome alternativo dell'emittente.")
  public String getIssuerAltName() {
    return issuerAltName;
  }

    public void setIssuerAltName(String issuerAltName) {
    this.issuerAltName = issuerAltName;
  }

    public VerifyCertificateReport keyUsageString(String keyUsageString) {
    this.keyUsageString = keyUsageString;
    return this;
  }

    @ApiModelProperty(value = "Rappresenta la chiave")
  public String getKeyUsageString() {
    return keyUsageString;
  }

    public void setKeyUsageString(String keyUsageString) {
    this.keyUsageString = keyUsageString;
  }

    public VerifyCertificateReport uid(String uid) {
    this.uid = uid;
    return this;
  }

    @ApiModelProperty(value = "Evenutale UUID del nodo del file.")
  public String getUid() {
    return uid;
  }

    public void setUid(String uid) {
    this.uid = uid;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerifyCertificateReport verifyCertificateReport = (VerifyCertificateReport) o;
    return Objects.equals(this.verificationResult, verifyCertificateReport.verificationResult) &&
        Objects.equals(this.errorCode, verifyCertificateReport.errorCode) &&
        Objects.equals(this.errorDescription, verifyCertificateReport.errorDescription) &&
        Objects.equals(this.certificationAuthority, verifyCertificateReport.certificationAuthority) &&
        Objects.equals(this.serialNumber, verifyCertificateReport.serialNumber) &&
        Objects.equals(this.verificationDateTime, verifyCertificateReport.verificationDateTime) &&
        Objects.equals(this.validFrom, verifyCertificateReport.validFrom) &&
        Objects.equals(this.validTo, verifyCertificateReport.validTo) &&
        Objects.equals(this.keyUsage, verifyCertificateReport.keyUsage) &&
        Objects.equals(this.revocationDate, verifyCertificateReport.revocationDate) &&
        Objects.equals(this.invalidSince, verifyCertificateReport.invalidSince) &&
        Objects.equals(this.holdDate, verifyCertificateReport.holdDate) &&
        Objects.equals(this.crlExpirationDate, verifyCertificateReport.crlExpirationDate) &&
        Objects.equals(this.caCertExpirationDate, verifyCertificateReport.caCertExpirationDate) &&
        Objects.equals(this.caCertRevocationDate, verifyCertificateReport.caCertRevocationDate) &&
        Objects.equals(this.expiredCertsOnCRL, verifyCertificateReport.expiredCertsOnCRL) &&
        Objects.equals(this.subject, verifyCertificateReport.subject) &&
        Objects.equals(this.crlDate, verifyCertificateReport.crlDate) &&
        Objects.equals(this.issuerAltName, verifyCertificateReport.issuerAltName) &&
        Objects.equals(this.keyUsageString, verifyCertificateReport.keyUsageString) &&
        Objects.equals(this.uid, verifyCertificateReport.uid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(verificationResult, errorCode, errorDescription, certificationAuthority, serialNumber, verificationDateTime, validFrom, validTo, keyUsage, revocationDate, invalidSince, holdDate, crlExpirationDate, caCertExpirationDate, caCertRevocationDate, expiredCertsOnCRL, subject, crlDate, issuerAltName, keyUsageString, uid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerifyCertificateReport {\n");

    sb.append("    verificationResult: ").append(toIndentedString(verificationResult)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorDescription: ").append(toIndentedString(errorDescription)).append("\n");
    sb.append("    certificationAuthority: ").append(toIndentedString(certificationAuthority)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    verificationDateTime: ").append(toIndentedString(verificationDateTime)).append("\n");
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("    keyUsage: ").append(toIndentedString(keyUsage)).append("\n");
    sb.append("    revocationDate: ").append(toIndentedString(revocationDate)).append("\n");
    sb.append("    invalidSince: ").append(toIndentedString(invalidSince)).append("\n");
    sb.append("    holdDate: ").append(toIndentedString(holdDate)).append("\n");
    sb.append("    crlExpirationDate: ").append(toIndentedString(crlExpirationDate)).append("\n");
    sb.append("    caCertExpirationDate: ").append(toIndentedString(caCertExpirationDate)).append("\n");
    sb.append("    caCertRevocationDate: ").append(toIndentedString(caCertRevocationDate)).append("\n");
    sb.append("    expiredCertsOnCRL: ").append(toIndentedString(expiredCertsOnCRL)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    crlDate: ").append(toIndentedString(crlDate)).append("\n");
    sb.append("    issuerAltName: ").append(toIndentedString(issuerAltName)).append("\n");
    sb.append("    keyUsageString: ").append(toIndentedString(keyUsageString)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}