/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.csi.mudeopen.mudeopensrvcommon.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

@ApiModel(description = "Parametri di verifica.")
@javax.annotation.Generated(value = "it.csi.mudeopen.mudeopensrvcommon.business.be.helper.cosmo.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class VerifyParameter {
    @JsonProperty("verificationDate")
    private String verificationDate = null;

    @JsonProperty("verificationType")
    private Integer verificationType = null;

    @JsonProperty("profileType")
    private Integer profileType = null;

    @JsonProperty("verificationScope")
    private Integer verificationScope = null;

    public VerifyParameter verificationDate(String verificationDate) {
        this.verificationDate = verificationDate;
        return this;
    }

    @ApiModelProperty(example = "", value = "Data di verifica.")
    public String getVerificationDate() {
        return verificationDate;
    }

    public void setVerificationDate(String verificationDate) {
        this.verificationDate = verificationDate;
    }

    public VerifyParameter verificationType(Integer verificationType) {
        this.verificationType = verificationType;
        return this;
    }

    @ApiModelProperty(example = "1", value = "Tipo di verifica.")
    public Integer getVerificationType() {
        return verificationType;
    }

    public void setVerificationType(Integer verificationType) {
        this.verificationType = verificationType;
    }

    public VerifyParameter profileType(Integer profileType) {
        this.profileType = profileType;
        return this;
    }

    @ApiModelProperty(example = "1", value = "Tipo di profilo.")
    public Integer getProfileType() {
        return profileType;
    }

    public void setProfileType(Integer profileType) {
        this.profileType = profileType;
    }

    public VerifyParameter verificationScope(Integer verificationScope) {
        this.verificationScope = verificationScope;
        return this;
    }

    @ApiModelProperty(example = "1", value = "Tipo di certificato.")
    public Integer getVerificationScope() {
        return verificationScope;
    }

    public void setVerificationScope(Integer verificationScope) {
        this.verificationScope = verificationScope;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VerifyParameter verifyParameter = (VerifyParameter) o;
        return Objects.equals(this.verificationDate, verifyParameter.verificationDate) &&
                Objects.equals(this.verificationType, verifyParameter.verificationType) &&
                Objects.equals(this.profileType, verifyParameter.profileType) &&
                Objects.equals(this.verificationScope, verifyParameter.verificationScope);
    }

    @Override
    public int hashCode() {
        return Objects.hash(verificationDate, verificationType, profileType, verificationScope);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class VerifyParameter {\n");

        sb.append("    verificationDate: ").append(toIndentedString(verificationDate)).append("\n");
        sb.append("    verificationType: ").append(toIndentedString(verificationType)).append("\n");
        sb.append("    profileType: ").append(toIndentedString(profileType)).append("\n");
        sb.append("    verificationScope: ").append(toIndentedString(verificationScope)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}