/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.csi.mudeopen.mudeopensrvcommon.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

@ApiModel(description = "Oggetto che incapsula - tokenUuid se il numerofirme richiede una elaborazione asincrona - altrimenti VerifyReport (esito della verifica).")
@javax.annotation.Generated(value = "it.csi.mudeopen.mudeopensrvcommon.business.be.helper.cosmo.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class VerifyReportExt {
    @JsonProperty("tokenUuid")
    private String tokenUuid = null;

    @JsonProperty("signCount")
    private Integer signCount = null;

    @JsonProperty("report")
    private VerifyReport report = null;

    public VerifyReportExt tokenUuid(String tokenUuid) {
        this.tokenUuid = tokenUuid;
        return this;
    }

    @ApiModelProperty(value = "Token Uuid dell'elaborazione asincrona.")
    public String getTokenUuid() {
        return tokenUuid;
    }

    public void setTokenUuid(String tokenUuid) {
        this.tokenUuid = tokenUuid;
    }

    public VerifyReportExt signCount(Integer signCount) {
        this.signCount = signCount;
        return this;
    }

    @ApiModelProperty(example = "2", value = "Numero di firme.")
    public Integer getSignCount() {
        return signCount;
    }

    public void setSignCount(Integer signCount) {
        this.signCount = signCount;
    }

    public VerifyReportExt report(VerifyReport report) {
        this.report = report;
        return this;
    }

    @ApiModelProperty(value = "")
    public VerifyReport getReport() {
        return report;
    }

    public void setReport(VerifyReport report) {
        this.report = report;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VerifyReportExt verifyReportExt = (VerifyReportExt) o;
        return Objects.equals(this.tokenUuid, verifyReportExt.tokenUuid) &&
                Objects.equals(this.signCount, verifyReportExt.signCount) &&
                Objects.equals(this.report, verifyReportExt.report);
    }

    @Override
    public int hashCode() {
        return Objects.hash(tokenUuid, signCount, report);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class VerifyReportExt {\n");

        sb.append("    tokenUuid: ").append(toIndentedString(tokenUuid)).append("\n");
        sb.append("    signCount: ").append(toIndentedString(signCount)).append("\n");
        sb.append("    report: ").append(toIndentedString(report)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}