/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.csi.mudeopen.mudeopensrvcommon.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

@ApiModel(description = "Rapporto di verifica della firma digitale di un documento.")
@javax.annotation.Generated(value = "it.csi.mudeopen.mudeopensrvcommon.business.be.helper.cosmo.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class VerifyReport {
    @JsonProperty("child")
    private VerifyReport child = null;

    @JsonProperty("conformitaParametriInput")
    private Integer conformitaParametriInput = null;

    @JsonProperty("date")
    private String date = null;

    @JsonProperty("errorCode")
    private Integer errorCode = null;

    @JsonProperty("formatoFirma")
    private Integer formatoFirma = null;

    @JsonProperty("numCertificatiFirma")
    private Integer numCertificatiFirma = null;

    @JsonProperty("numCertificatiMarca")
    private Integer numCertificatiMarca = null;

    @JsonProperty("signature")
    private List<Signature> signature = null;

    @JsonProperty("tipoFirma")
    private Integer tipoFirma = null;

    @JsonProperty("uid")
    private List<String> uid = null;

    public VerifyReport child(VerifyReport child) {
        this.child = child;
        return this;
    }

    @ApiModelProperty(value = "")
    public VerifyReport getChild() {
        return child;
    }

    public void setChild(VerifyReport child) {
        this.child = child;
    }

    public VerifyReport conformitaParametriInput(Integer conformitaParametriInput) {
        this.conformitaParametriInput = conformitaParametriInput;
        return this;
    }

    @ApiModelProperty(example = "0", value = "Conformita dei parametri di input:  0 NON OK 1 OK ")
    public Integer getConformitaParametriInput() {
        return conformitaParametriInput;
    }

    public void setConformitaParametriInput(Integer conformitaParametriInput) {
        this.conformitaParametriInput = conformitaParametriInput;
    }

    public VerifyReport date(String date) {
        this.date = date;
        return this;
    }

    @ApiModelProperty(example = "", value = "Data in cui è stato chiesto il rapporto di verifica.")
    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public VerifyReport errorCode(Integer errorCode) {
        this.errorCode = errorCode;
        return this;
    }

    @ApiModelProperty(example = "1", value = "Eventuale codice di errore : viene restituito  0 se il processo si è concluso correttamente  altrimenti un valore da 1 a 7 in caso di fallimento di uno dei sette passi.    >      1: Verifica conformità e integrità busta crittografica.      2: Sbustamento busta crittografica.      3: Verifica consistenza firma.      4: Verifica validità certificato.      5: Verifica certification authority.      6: Verifica lista di revoca — CRL aggiornata non disponibile.      7: Verifica lista di revoca — certificato presente nella CRL. ")
    public Integer getErrorCode() {
        return errorCode;
    }

    public void setErrorCode(Integer errorCode) {
        this.errorCode = errorCode;
    }

    public VerifyReport formatoFirma(Integer formatoFirma) {
        this.formatoFirma = formatoFirma;
        return this;
    }

    @ApiModelProperty(example = "1", value = "Formato della firma:  1 in caso di firma enveloped 2 in caso di firma separata 3 in caso di marca temporale InfoCert  4 in caso di marca temporale separata ")
    public Integer getFormatoFirma() {
        return formatoFirma;
    }

    public void setFormatoFirma(Integer formatoFirma) {
        this.formatoFirma = formatoFirma;
    }

    public VerifyReport numCertificatiFirma(Integer numCertificatiFirma) {
        this.numCertificatiFirma = numCertificatiFirma;
        return this;
    }

    @ApiModelProperty(example = "5", value = "Numero dei certificati della firma.")
    public Integer getNumCertificatiFirma() {
        return numCertificatiFirma;
    }

    public void setNumCertificatiFirma(Integer numCertificatiFirma) {
        this.numCertificatiFirma = numCertificatiFirma;
    }

    public VerifyReport numCertificatiMarca(Integer numCertificatiMarca) {
        this.numCertificatiMarca = numCertificatiMarca;
        return this;
    }

    @ApiModelProperty(example = "5", value = "Numero dei certificati della marca temporale.")
    public Integer getNumCertificatiMarca() {
        return numCertificatiMarca;
    }

    public void setNumCertificatiMarca(Integer numCertificatiMarca) {
        this.numCertificatiMarca = numCertificatiMarca;
    }

    public VerifyReport signature(List<Signature> signature) {
        this.signature = signature;
        return this;
    }

    public VerifyReport addSignatureItem(Signature signatureItem) {
        if (this.signature == null) {
            this.signature = new ArrayList<Signature>();
        }
        this.signature.add(signatureItem);
        return this;
    }

    @ApiModelProperty(value = "Firme del file.")
    public List<Signature> getSignature() {
        return signature;
    }

    public void setSignature(List<Signature> signature) {
        this.signature = signature;
    }

    public VerifyReport tipoFirma(Integer tipoFirma) {
        this.tipoFirma = tipoFirma;
        return this;
    }

    @ApiModelProperty(example = "1", value = "Tipologia di firma o marca temporale:  0 in caso di marca temporale 1 in caso di firma semplice 2 in caso di firma multipla parallela  3 in caso di firma multipla controfirma 4 in caso di firma multipla a catena ")
    public Integer getTipoFirma() {
        return tipoFirma;
    }

    public void setTipoFirma(Integer tipoFirma) {
        this.tipoFirma = tipoFirma;
    }

    public VerifyReport uid(List<String> uid) {
        this.uid = uid;
        return this;
    }

    public VerifyReport addUidItem(String uidItem) {
        if (this.uid == null) {
            this.uid = new ArrayList<String>();
        }
        this.uid.add(uidItem);
        return this;
    }

    @ApiModelProperty(value = "Eventuale UID del file.")
    public List<String> getUid() {
        return uid;
    }

    public void setUid(List<String> uid) {
        this.uid = uid;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VerifyReport verifyReport = (VerifyReport) o;
        return Objects.equals(this.child, verifyReport.child) &&
                Objects.equals(this.conformitaParametriInput, verifyReport.conformitaParametriInput) &&
                Objects.equals(this.date, verifyReport.date) &&
                Objects.equals(this.errorCode, verifyReport.errorCode) &&
                Objects.equals(this.formatoFirma, verifyReport.formatoFirma) &&
                Objects.equals(this.numCertificatiFirma, verifyReport.numCertificatiFirma) &&
                Objects.equals(this.numCertificatiMarca, verifyReport.numCertificatiMarca) &&
                Objects.equals(this.signature, verifyReport.signature) &&
                Objects.equals(this.tipoFirma, verifyReport.tipoFirma) &&
                Objects.equals(this.uid, verifyReport.uid);
    }

    @Override
    public int hashCode() {
        return Objects.hash(child, conformitaParametriInput, date, errorCode, formatoFirma, numCertificatiFirma, numCertificatiMarca, signature, tipoFirma, uid);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class VerifyReport {\n");

        sb.append("    child: ").append(toIndentedString(child)).append("\n");
        sb.append("    conformitaParametriInput: ").append(toIndentedString(conformitaParametriInput)).append("\n");
        sb.append("    date: ").append(toIndentedString(date)).append("\n");
        sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
        sb.append("    formatoFirma: ").append(toIndentedString(formatoFirma)).append("\n");
        sb.append("    numCertificatiFirma: ").append(toIndentedString(numCertificatiFirma)).append("\n");
        sb.append("    numCertificatiMarca: ").append(toIndentedString(numCertificatiMarca)).append("\n");
        sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
        sb.append("    tipoFirma: ").append(toIndentedString(tipoFirma)).append("\n");
        sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}