/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.itfcsitorino;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.127+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "GeoriferimentoNonTrovatoException", messageName = "GeoriferimentoNonTrovatoException", targetNamespace = "http://itfcsitorino.interfacews.mudesrvextsic.mude.csi.it/")
public class GeoriferimentoNonTrovatoException_Exception extends MudeWSException {
    private GeoriferimentoNonTrovatoException georiferimentoNonTrovatoException;
    public GeoriferimentoNonTrovatoException_Exception() {
        super();
    }
	public GeoriferimentoNonTrovatoException_Exception(String message) {
		super(message);
		this.georiferimentoNonTrovatoException = new GeoriferimentoNonTrovatoException();
	}
    public GeoriferimentoNonTrovatoException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.georiferimentoNonTrovatoException = new GeoriferimentoNonTrovatoException();
    }
    public GeoriferimentoNonTrovatoException_Exception(String message, GeoriferimentoNonTrovatoException georiferimentoNonTrovatoException) {
        super(message);
        this.georiferimentoNonTrovatoException = georiferimentoNonTrovatoException;
    }
    public GeoriferimentoNonTrovatoException_Exception(String message, GeoriferimentoNonTrovatoException georiferimentoNonTrovatoException, Throwable cause) {
        super(message, cause);
        this.georiferimentoNonTrovatoException = georiferimentoNonTrovatoException;
    }
    public GeoriferimentoNonTrovatoException getFaultInfo() {
        return this.georiferimentoNonTrovatoException;
    }
}
