/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.115+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "CampoObbligatorioException", messageName = "CampoObbligatorioException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class CampoObbligatorioException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private CampoObbligatorioException campoObbligatorioException;
    public CampoObbligatorioException_Exception() {
        super();
    }
	public CampoObbligatorioException_Exception(String message) {
		super(message);
		this.campoObbligatorioException = new CampoObbligatorioException();
	}
    public CampoObbligatorioException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.campoObbligatorioException = new CampoObbligatorioException();
    }
    public CampoObbligatorioException_Exception(String message, CampoObbligatorioException campoObbligatorioException) {
        super(message);
        this.campoObbligatorioException = campoObbligatorioException;
    }
    public CampoObbligatorioException_Exception(String message, CampoObbligatorioException campoObbligatorioException, Throwable cause) {
        super(message, cause);
        this.campoObbligatorioException = campoObbligatorioException;
    }
    public CampoObbligatorioException getFaultInfo() {
        return this.campoObbligatorioException;
    }
}
