/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.090+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "ComuneNonAbilitatoException", messageName = "ComuneNonAbilitatoException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class ComuneNonAbilitatoException_Exception extends MudeWSException {
	private static final long serialVersionUID = 384356883489L;
    private ComuneNonAbilitatoException comuneNonAbilitatoException;
    public ComuneNonAbilitatoException_Exception() {
        super();
    }
	public ComuneNonAbilitatoException_Exception(String message) {
		super(message);
		this.comuneNonAbilitatoException = new ComuneNonAbilitatoException();
	}
    public ComuneNonAbilitatoException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.comuneNonAbilitatoException = new ComuneNonAbilitatoException();
    }
    public ComuneNonAbilitatoException_Exception(String message, ComuneNonAbilitatoException comuneNonAbilitatoException) {
        super(message);
        this.comuneNonAbilitatoException = comuneNonAbilitatoException;
    }
    public ComuneNonAbilitatoException_Exception(String message, ComuneNonAbilitatoException comuneNonAbilitatoException, Throwable cause) {
        super(message, cause);
        this.comuneNonAbilitatoException = comuneNonAbilitatoException;
    }
    public ComuneNonAbilitatoException getFaultInfo() {
        return this.comuneNonAbilitatoException;
    }
}
