/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.138+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "ComuneInsesistenteException", messageName = "ComuneInsesistenteException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class ComuneInsesistenteException_Exception extends MudeWSException {
    /**
	 * 
	 */
	private static final long serialVersionUID = 569998876L;
	private ComuneInsesistenteException comuneInsesistenteException;
    public ComuneInsesistenteException_Exception() {
        super();
    }
	public ComuneInsesistenteException_Exception(String message) {
		super(message);
		this.comuneInsesistenteException = new ComuneInsesistenteException();
	}
    public ComuneInsesistenteException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.comuneInsesistenteException = new ComuneInsesistenteException();
    }
    public ComuneInsesistenteException_Exception(String message, ComuneInsesistenteException comuneInsesistenteException) {
        super(message);
        this.comuneInsesistenteException = comuneInsesistenteException;
    }
    public ComuneInsesistenteException_Exception(String message, ComuneInsesistenteException comuneInsesistenteException, Throwable cause) {
        super(message, cause);
        this.comuneInsesistenteException = comuneInsesistenteException;
    }
    public ComuneInsesistenteException getFaultInfo() {
        return this.comuneInsesistenteException;
    }
}
