/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.142+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "DocumentoNonValidoException", messageName = "DocumentoNonValidoException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class DocumentoNonValidoException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private DocumentoNonValidoException documentoNonValidoException;
    public DocumentoNonValidoException_Exception() {
        super();
    }
	public DocumentoNonValidoException_Exception(String message) {
		super(message);
		this.documentoNonValidoException = new DocumentoNonValidoException();
	}
    public DocumentoNonValidoException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.documentoNonValidoException = new DocumentoNonValidoException();
    }
    public DocumentoNonValidoException_Exception(String message, DocumentoNonValidoException documentoNonValidoException) {
        super(message);
        this.documentoNonValidoException = documentoNonValidoException;
    }
    public DocumentoNonValidoException_Exception(String message, DocumentoNonValidoException documentoNonValidoException, Throwable cause) {
        super(message, cause);
        this.documentoNonValidoException = documentoNonValidoException;
    }
    public DocumentoNonValidoException getFaultInfo() {
        return this.documentoNonValidoException;
    }
}
