/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.072+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "IstanzaNonTrovataException", messageName = "IstanzaNonTrovataException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class IstanzaNonTrovataException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private IstanzaNonTrovataException istanzaNonTrovataException;
    public IstanzaNonTrovataException_Exception() {
        super();
    }
	public IstanzaNonTrovataException_Exception(String message) {
		super(message);
		this.istanzaNonTrovataException = new IstanzaNonTrovataException();
	}
    public IstanzaNonTrovataException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.istanzaNonTrovataException = new IstanzaNonTrovataException();
    }
    public IstanzaNonTrovataException_Exception(String message, IstanzaNonTrovataException istanzaNonTrovataException) {
        super(message);
        this.istanzaNonTrovataException = istanzaNonTrovataException;
    }
    public IstanzaNonTrovataException_Exception(String message, IstanzaNonTrovataException istanzaNonTrovataException, Throwable cause) {
        super(message, cause);
        this.istanzaNonTrovataException = istanzaNonTrovataException;
    }
    public IstanzaNonTrovataException getFaultInfo() {
        return this.istanzaNonTrovataException;
    }
}
