/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.149+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "MittenteNonAbilitatoFunzioneException", messageName = "MittenteNonAbilitatoFunzioneException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class MittenteNonAbilitatoFunzioneException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private MittenteNonAbilitatoFunzioneException mittenteNonAbilitatoFunzioneException;
    public MittenteNonAbilitatoFunzioneException_Exception() {
        super();
    }
	public MittenteNonAbilitatoFunzioneException_Exception(String message) {
		super(message);
		this.mittenteNonAbilitatoFunzioneException = new MittenteNonAbilitatoFunzioneException();
	}
    public MittenteNonAbilitatoFunzioneException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.mittenteNonAbilitatoFunzioneException = new MittenteNonAbilitatoFunzioneException();
    }
    public MittenteNonAbilitatoFunzioneException_Exception(String message, MittenteNonAbilitatoFunzioneException mittenteNonAbilitatoFunzioneException) {
        super(message);
        this.mittenteNonAbilitatoFunzioneException = mittenteNonAbilitatoFunzioneException;
    }
    public MittenteNonAbilitatoFunzioneException_Exception(String message, MittenteNonAbilitatoFunzioneException mittenteNonAbilitatoFunzioneException, Throwable cause) {
        super(message, cause);
        this.mittenteNonAbilitatoFunzioneException = mittenteNonAbilitatoFunzioneException;
    }
    public MittenteNonAbilitatoFunzioneException getFaultInfo() {
        return this.mittenteNonAbilitatoFunzioneException;
    }
}
