/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.118+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "NotAuthorizedException", messageName = "NotAuthorizedException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class NotAuthorizedException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private NotAuthorizedException notAuthorizedException;
    public NotAuthorizedException_Exception() {
        super();
    }
	public NotAuthorizedException_Exception(String message) {
		super(message);
		this.notAuthorizedException = new NotAuthorizedException();
	}
    public NotAuthorizedException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.notAuthorizedException = new NotAuthorizedException();
    }
    public NotAuthorizedException_Exception(String message, NotAuthorizedException notAuthorizedException) {
        super(message);
        this.notAuthorizedException = notAuthorizedException;
    }
    public NotAuthorizedException_Exception(String message, NotAuthorizedException notAuthorizedException, Throwable cause) {
        super(message, cause);
        this.notAuthorizedException = notAuthorizedException;
    }
    public NotAuthorizedException getFaultInfo() {
        return this.notAuthorizedException;
    }
}
