/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.061+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "PassaggioStatoImpossibileException", messageName = "PassaggioStatoImpossibileException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class PassaggioStatoImpossibileException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private PassaggioStatoImpossibileException passaggioStatoImpossibileException;
    public PassaggioStatoImpossibileException_Exception() {
        super();
    }
	public PassaggioStatoImpossibileException_Exception(String message) {
		super(message);
		this.passaggioStatoImpossibileException = new PassaggioStatoImpossibileException();
	}
    public PassaggioStatoImpossibileException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.passaggioStatoImpossibileException = new PassaggioStatoImpossibileException();
    }
    public PassaggioStatoImpossibileException_Exception(String message, PassaggioStatoImpossibileException passaggioStatoImpossibileException) {
        super(message);
        this.passaggioStatoImpossibileException = passaggioStatoImpossibileException;
    }
    public PassaggioStatoImpossibileException_Exception(String message, PassaggioStatoImpossibileException passaggioStatoImpossibileException, Throwable cause) {
        super(message, cause);
        this.passaggioStatoImpossibileException = passaggioStatoImpossibileException;
    }
    public PassaggioStatoImpossibileException getFaultInfo() {
        return this.passaggioStatoImpossibileException;
    }
}
