/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.082+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "PraticaAssociataAdAltraIstanzaException", messageName = "PraticaAssociataAdAltraIstanzaException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class PraticaAssociataAdAltraIstanzaException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private PraticaAssociataAdAltraIstanzaException praticaAssociataAdAltraIstanzaException;
    public PraticaAssociataAdAltraIstanzaException_Exception() {
        super();
    }
	public PraticaAssociataAdAltraIstanzaException_Exception(String message) {
		super(message);
		this.praticaAssociataAdAltraIstanzaException = new PraticaAssociataAdAltraIstanzaException();
	}
    public PraticaAssociataAdAltraIstanzaException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.praticaAssociataAdAltraIstanzaException = new PraticaAssociataAdAltraIstanzaException();
    }
    public PraticaAssociataAdAltraIstanzaException_Exception(String message, PraticaAssociataAdAltraIstanzaException praticaAssociataAdAltraIstanzaException) {
        super(message);
        this.praticaAssociataAdAltraIstanzaException = praticaAssociataAdAltraIstanzaException;
    }
    public PraticaAssociataAdAltraIstanzaException_Exception(String message, PraticaAssociataAdAltraIstanzaException praticaAssociataAdAltraIstanzaException, Throwable cause) {
        super(message, cause);
        this.praticaAssociataAdAltraIstanzaException = praticaAssociataAdAltraIstanzaException;
    }
    public PraticaAssociataAdAltraIstanzaException getFaultInfo() {
        return this.praticaAssociataAdAltraIstanzaException;
    }
}
