/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.086+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "PraticaDiAltroFascicoloException", messageName = "PraticaDiAltroFascicoloException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class PraticaDiAltroFascicoloException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private PraticaDiAltroFascicoloException praticaDiAltroFascicoloException;
    public PraticaDiAltroFascicoloException_Exception() {
        super();
    }
	public PraticaDiAltroFascicoloException_Exception(String message) {
		super(message);
		this.praticaDiAltroFascicoloException = new PraticaDiAltroFascicoloException();
	}
    public PraticaDiAltroFascicoloException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.praticaDiAltroFascicoloException = new PraticaDiAltroFascicoloException();
    }
    public PraticaDiAltroFascicoloException_Exception(String message, PraticaDiAltroFascicoloException praticaDiAltroFascicoloException) {
        super(message);
        this.praticaDiAltroFascicoloException = praticaDiAltroFascicoloException;
    }
    public PraticaDiAltroFascicoloException_Exception(String message, PraticaDiAltroFascicoloException praticaDiAltroFascicoloException, Throwable cause) {
        super(message, cause);
        this.praticaDiAltroFascicoloException = praticaDiAltroFascicoloException;
    }
    public PraticaDiAltroFascicoloException getFaultInfo() {
        return this.praticaDiAltroFascicoloException;
    }
}
