/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.111+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "StatoIstanzaNonValidoModificaException", messageName = "StatoIstanzaNonValidoModificaException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class StatoIstanzaNonValidoModificaException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private StatoIstanzaNonValidoModificaException statoIstanzaNonValidoModificaException;
    public StatoIstanzaNonValidoModificaException_Exception() {
        super();
    }
	public StatoIstanzaNonValidoModificaException_Exception(String message) {
		super(message);
		this.statoIstanzaNonValidoModificaException = new StatoIstanzaNonValidoModificaException();
	}
    public StatoIstanzaNonValidoModificaException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.statoIstanzaNonValidoModificaException = new StatoIstanzaNonValidoModificaException();
    }
    public StatoIstanzaNonValidoModificaException_Exception(String message, StatoIstanzaNonValidoModificaException statoIstanzaNonValidoModificaException) {
        super(message);
        this.statoIstanzaNonValidoModificaException = statoIstanzaNonValidoModificaException;
    }
    public StatoIstanzaNonValidoModificaException_Exception(String message, StatoIstanzaNonValidoModificaException statoIstanzaNonValidoModificaException, Throwable cause) {
        super(message, cause);
        this.statoIstanzaNonValidoModificaException = statoIstanzaNonValidoModificaException;
    }
    public StatoIstanzaNonValidoModificaException getFaultInfo() {
        return this.statoIstanzaNonValidoModificaException;
    }
}
