/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.108+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "StatoInesistenteException", messageName = "StatoInesistenteException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class StatoInesistenteException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private StatoInesistenteException statoInesistenteException;
    public StatoInesistenteException_Exception() {
        super();
    }
	public StatoInesistenteException_Exception(String message) {
		super(message);
		this.statoInesistenteException = new StatoInesistenteException();
	}
    public StatoInesistenteException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.statoInesistenteException = new StatoInesistenteException();
    }
    public StatoInesistenteException_Exception(String message, StatoInesistenteException statoInesistenteException) {
        super(message);
        this.statoInesistenteException = statoInesistenteException;
    }
    public StatoInesistenteException_Exception(String message, StatoInesistenteException statoInesistenteException, Throwable cause) {
        super(message, cause);
        this.statoInesistenteException = statoInesistenteException;
    }
    public StatoInesistenteException getFaultInfo() {
        return this.statoInesistenteException;
    }
}
