/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.131+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "StatoIstanzaConsultazioneException", messageName = "StatoIstanzaConsultazioneException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class StatoIstanzaConsultazioneException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private StatoIstanzaConsultazioneException statoIstanzaConsultazioneException;
    public StatoIstanzaConsultazioneException_Exception() {
        super();
    }
	public StatoIstanzaConsultazioneException_Exception(String message) {
		super(message);
		this.statoIstanzaConsultazioneException = new StatoIstanzaConsultazioneException();
	}
    public StatoIstanzaConsultazioneException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.statoIstanzaConsultazioneException = new StatoIstanzaConsultazioneException();
    }
    public StatoIstanzaConsultazioneException_Exception(String message, StatoIstanzaConsultazioneException statoIstanzaConsultazioneException) {
        super(message);
        this.statoIstanzaConsultazioneException = statoIstanzaConsultazioneException;
    }
    public StatoIstanzaConsultazioneException_Exception(String message, StatoIstanzaConsultazioneException statoIstanzaConsultazioneException, Throwable cause) {
        super(message, cause);
        this.statoIstanzaConsultazioneException = statoIstanzaConsultazioneException;
    }
    public StatoIstanzaConsultazioneException getFaultInfo() {
        return this.statoIstanzaConsultazioneException;
    }
}
