/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.152+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "TipoNotificaInesistenteException", messageName = "TipoNotificaInesistenteException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class TipoNotificaInesistenteException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private TipoNotificaInesistenteException tipoNotificaInesistenteException;
    public TipoNotificaInesistenteException_Exception() {
        super();
    }
	public TipoNotificaInesistenteException_Exception(String message) {
		super(message);
		this.tipoNotificaInesistenteException = new TipoNotificaInesistenteException();
	}
    public TipoNotificaInesistenteException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.tipoNotificaInesistenteException = new TipoNotificaInesistenteException();
    }
    public TipoNotificaInesistenteException_Exception(String message, TipoNotificaInesistenteException tipoNotificaInesistenteException) {
        super(message);
        this.tipoNotificaInesistenteException = tipoNotificaInesistenteException;
    }
    public TipoNotificaInesistenteException_Exception(String message, TipoNotificaInesistenteException tipoNotificaInesistenteException, Throwable cause) {
        super(message, cause);
        this.tipoNotificaInesistenteException = tipoNotificaInesistenteException;
    }
    public TipoNotificaInesistenteException getFaultInfo() {
        return this.tipoNotificaInesistenteException;
    }
}
