/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.gestionale;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2022-12-26T18:19:05.135+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "TooManyRecordsException", messageName = "TooManyRecordsException", targetNamespace = "http://gestionale.interfacews.mudesrvextsic.mude.csi.it/")
public class TooManyRecordsException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private TooManyRecordsException tooManyRecordsException;
    public TooManyRecordsException_Exception() {
        super();
    }
	public TooManyRecordsException_Exception(String message) {
		super(message);
		this.tooManyRecordsException = new TooManyRecordsException();
	}
    public TooManyRecordsException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.tooManyRecordsException = new TooManyRecordsException();
    }
    public TooManyRecordsException_Exception(String message, TooManyRecordsException tooManyRecordsException) {
        super(message);
        this.tooManyRecordsException = tooManyRecordsException;
    }
    public TooManyRecordsException_Exception(String message, TooManyRecordsException tooManyRecordsException, Throwable cause) {
        super(message, cause);
        this.tooManyRecordsException = tooManyRecordsException;
    }
    public TooManyRecordsException getFaultInfo() {
        return this.tooManyRecordsException;
    }
}
