/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-07-14T15:53:38.479+02:00
 * Generated source version: 3.5.1
 *
 */
@WebService(targetNamespace = "urn:sigalfsrvTitolari", name = "sigalfsrvTitolari")
@XmlSeeAlso({ObjectFactory.class})
public interface SigalfsrvTitolari {

    @WebMethod
    @RequestWrapper(localName = "cercaTitolaritaESoggettiAssociatiDiUnIdentificativoCatastaleTerreno", targetNamespace = "urn:sigalfsrvTitolari", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.CercaTitolaritaESoggettiAssociatiDiUnIdentificativoCatastaleTerreno")
    @ResponseWrapper(localName = "cercaTitolaritaESoggettiAssociatiDiUnIdentificativoCatastaleTerrenoResponse", targetNamespace = "urn:sigalfsrvTitolari", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.CercaTitolaritaESoggettiAssociatiDiUnIdentificativoCatastaleTerrenoResponse")
    @WebResult(name = "cercaTitolaritaESoggettiAssociatiDiUnIdentificativoCatastaleTerrenoReturn", targetNamespace = "urn:sigalfsrvTitolari")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.Titolarita> cercaTitolaritaESoggettiAssociatiDiUnIdentificativoCatastaleTerreno(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTitolari")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.IdentificativoCatastaleTerreno in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTitolari")
        String in1
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaIntervalloValiditaUltimaTitolaritaSuFabbricato", targetNamespace = "urn:sigalfsrvTitolari", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.CercaIntervalloValiditaUltimaTitolaritaSuFabbricato")
    @ResponseWrapper(localName = "cercaIntervalloValiditaUltimaTitolaritaSuFabbricatoResponse", targetNamespace = "urn:sigalfsrvTitolari", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.CercaIntervalloValiditaUltimaTitolaritaSuFabbricatoResponse")
    @WebResult(name = "cercaIntervalloValiditaUltimaTitolaritaSuFabbricatoReturn", targetNamespace = "urn:sigalfsrvTitolari")
    public it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.IntervalloValiditaTitolarita cercaIntervalloValiditaUltimaTitolaritaSuFabbricato(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTitolari")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.IdentitaPersonaFisica in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTitolari")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.IdentificativoCatastaleFabbricato in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvTitolari")
        String in2
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaTitolaritaESoggettiAssociatiDiUnIdentificativoCatastaleFabbricato", targetNamespace = "urn:sigalfsrvTitolari", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.CercaTitolaritaESoggettiAssociatiDiUnIdentificativoCatastaleFabbricato")
    @ResponseWrapper(localName = "cercaTitolaritaESoggettiAssociatiDiUnIdentificativoCatastaleFabbricatoResponse", targetNamespace = "urn:sigalfsrvTitolari", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.CercaTitolaritaESoggettiAssociatiDiUnIdentificativoCatastaleFabbricatoResponse")
    @WebResult(name = "cercaTitolaritaESoggettiAssociatiDiUnIdentificativoCatastaleFabbricatoReturn", targetNamespace = "urn:sigalfsrvTitolari")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.Titolarita> cercaTitolaritaESoggettiAssociatiDiUnIdentificativoCatastaleFabbricato(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTitolari")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.IdentificativoCatastaleFabbricato in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTitolari")
        String in1
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaIntervalloValiditaUltimaTitolaritaSuTerreno", targetNamespace = "urn:sigalfsrvTitolari", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.CercaIntervalloValiditaUltimaTitolaritaSuTerreno")
    @ResponseWrapper(localName = "cercaIntervalloValiditaUltimaTitolaritaSuTerrenoResponse", targetNamespace = "urn:sigalfsrvTitolari", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.CercaIntervalloValiditaUltimaTitolaritaSuTerrenoResponse")
    @WebResult(name = "cercaIntervalloValiditaUltimaTitolaritaSuTerrenoReturn", targetNamespace = "urn:sigalfsrvTitolari")
    public it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.IntervalloValiditaTitolarita cercaIntervalloValiditaUltimaTitolaritaSuTerreno(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTitolari")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.IdentitaPersonaFisica in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTitolari")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.IdentificativoCatastaleTerreno in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvTitolari")
        String in2
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;
}
