/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-07-14T15:53:38.492+02:00
 * Generated source version: 3.5.1
 *
 */
@WebServiceClient(name = "sigalfsrvTitolariService",
                  wsdlLocation = "file:wsdl/sigalfsrvTitolari.wsdl",
                  targetNamespace = "urn:sigalfsrvTitolari")
public class SigalfsrvTitolariService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sigalfsrvTitolari", "sigalfsrvTitolariService");
    public final static QName SigalfsrvTitolari = new QName("urn:sigalfsrvTitolari", "sigalfsrvTitolari");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/sigalfsrvTitolari.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SigalfsrvTitolariService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:wsdl/sigalfsrvTitolari.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SigalfsrvTitolariService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SigalfsrvTitolariService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SigalfsrvTitolariService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     *     returns SigalfsrvTitolari
     */
    @WebEndpoint(name = "sigalfsrvTitolari")
    public SigalfsrvTitolari getSigalfsrvTitolari() {
        return super.getPort(SigalfsrvTitolari, SigalfsrvTitolari.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.

     *     returns SigalfsrvTitolari
     */
    @WebEndpoint(name = "sigalfsrvTitolari")
    public SigalfsrvTitolari getSigalfsrvTitolari(WebServiceFeature... features) {
        return super.getPort(SigalfsrvTitolari, SigalfsrvTitolari.class, features);
    }

}
