/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari;

import javax.xml.ws.WebFault;
/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-07-14T15:53:38.473+02:00
 * Generated source version: 3.5.1
 */

@WebFault(name = "fault2", targetNamespace = "urn:sigalfsrvTitolari")
public class UnrecoverableException_Exception extends Exception {

    private it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.UnrecoverableException faultInfo;

    public UnrecoverableException_Exception() {
        super();
    }

    public UnrecoverableException_Exception(String message) {
        super(message);
    }

    public UnrecoverableException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnrecoverableException_Exception(String message, it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.UnrecoverableException fault2) {
        super(message);
        this.faultInfo = fault2;
    }

    public UnrecoverableException_Exception(String message, it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.UnrecoverableException fault2, Throwable cause) {
        super(message, cause);
        this.faultInfo = fault2;
    }

    public it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.titolari.UnrecoverableException getFaultInfo() {
        return this.faultInfo;
    }
}
