/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu;

import javax.xml.ws.WebFault;
/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-07-14T15:53:54.568+02:00
 * Generated source version: 3.5.1
 */

@WebFault(name = "fault3", targetNamespace = "urn:sigalfsrvUiu")
public class AutorizzMancanteEnteException_Exception extends Exception {

    private it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.AutorizzMancanteEnteException faultInfo;

    public AutorizzMancanteEnteException_Exception() {
        super();
    }

    public AutorizzMancanteEnteException_Exception(String message) {
        super(message);
    }

    public AutorizzMancanteEnteException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AutorizzMancanteEnteException_Exception(String message, it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.AutorizzMancanteEnteException fault3) {
        super(message);
        this.faultInfo = fault3;
    }

    public AutorizzMancanteEnteException_Exception(String message, it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.AutorizzMancanteEnteException fault3, Throwable cause) {
        super(message, cause);
        this.faultInfo = fault3;
    }

    public it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.AutorizzMancanteEnteException getFaultInfo() {
        return this.faultInfo;
    }
}
