/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu;

import javax.xml.ws.WebFault;
/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-07-14T15:53:54.561+02:00
 * Generated source version: 3.5.1
 */

@WebFault(name = "fault", targetNamespace = "urn:sigalfsrvUiu")
public class CSIException_Exception extends Exception {

    private it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CSIException faultInfo;

    public CSIException_Exception() {
        super();
    }

    public CSIException_Exception(String message) {
        super(message);
    }

    public CSIException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CSIException_Exception(String message, it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CSIException fault) {
        super(message);
        this.faultInfo = fault;
    }

    public CSIException_Exception(String message, it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CSIException fault, Throwable cause) {
        super(message, cause);
        this.faultInfo = fault;
    }

    public it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CSIException getFaultInfo() {
        return this.faultInfo;
    }
}
