/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu;

import javax.xml.ws.WebFault;
/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-07-14T15:53:54.588+02:00
 * Generated source version: 3.5.1
 */

@WebFault(name = "fault4", targetNamespace = "urn:sigalfsrvUiu")
public class OutputException_Exception extends Exception {

    private it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.OutputException faultInfo;

    public OutputException_Exception() {
        super();
    }

    public OutputException_Exception(String message) {
        super(message);
    }

    public OutputException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public OutputException_Exception(String message, it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.OutputException fault4) {
        super(message);
        this.faultInfo = fault4;
    }

    public OutputException_Exception(String message, it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.OutputException fault4, Throwable cause) {
        super(message, cause);
        this.faultInfo = fault4;
    }

    public it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.OutputException getFaultInfo() {
        return this.faultInfo;
    }
}
