/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu;

import javax.xml.ws.WebFault;
/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-07-14T15:53:54.522+02:00
 * Generated source version: 3.5.1
 */

@WebFault(name = "fault5", targetNamespace = "urn:sigalfsrvUiu")
public class ParInputObblMancantiException_Exception extends Exception {

    private it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.ParInputObblMancantiException faultInfo;

    public ParInputObblMancantiException_Exception() {
        super();
    }

    public ParInputObblMancantiException_Exception(String message) {
        super(message);
    }

    public ParInputObblMancantiException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ParInputObblMancantiException_Exception(String message, it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.ParInputObblMancantiException fault5) {
        super(message);
        this.faultInfo = fault5;
    }

    public ParInputObblMancantiException_Exception(String message, it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.ParInputObblMancantiException fault5, Throwable cause) {
        super(message, cause);
        this.faultInfo = fault5;
    }

    public it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.ParInputObblMancantiException getFaultInfo() {
        return this.faultInfo;
    }
}
