/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu;

import javax.xml.ws.WebFault;
/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-07-14T15:53:54.581+02:00
 * Generated source version: 3.5.1
 */

@WebFault(name = "fault7", targetNamespace = "urn:sigalfsrvUiu")
public class PermissionException_Exception extends Exception {

    private it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.PermissionException faultInfo;

    public PermissionException_Exception() {
        super();
    }

    public PermissionException_Exception(String message) {
        super(message);
    }

    public PermissionException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public PermissionException_Exception(String message, it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.PermissionException fault7) {
        super(message);
        this.faultInfo = fault7;
    }

    public PermissionException_Exception(String message, it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.PermissionException fault7, Throwable cause) {
        super(message, cause);
        this.faultInfo = fault7;
    }

    public it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.PermissionException getFaultInfo() {
        return this.faultInfo;
    }
}
