/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-07-14T15:53:54.608+02:00
 * Generated source version: 3.5.1
 *
 */
@WebService(targetNamespace = "urn:sigalfsrvUiu", name = "sigalfsrvUiu")
@XmlSeeAlso({ObjectFactory.class})
public interface SigalfsrvUiu {

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniGraffatiConBelfioreESezione", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniGraffatiConBelfioreESezione")
    @ResponseWrapper(localName = "cercaElencoSubalterniGraffatiConBelfioreESezioneResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniGraffatiConBelfioreESezioneResponse")
    @WebResult(name = "cercaElencoSubalterniGraffatiConBelfioreESezioneReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.Graffato> cercaElencoSubalterniGraffatiConBelfioreESezione(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvUiu")
        String in2,
        @WebParam(name = "in3", targetNamespace = "urn:sigalfsrvUiu")
        String in3,
        @WebParam(name = "in4", targetNamespace = "urn:sigalfsrvUiu")
        String in4
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniGraffatiConBelfiore", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniGraffatiConBelfiore")
    @ResponseWrapper(localName = "cercaElencoSubalterniGraffatiConBelfioreResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniGraffatiConBelfioreResponse")
    @WebResult(name = "cercaElencoSubalterniGraffatiConBelfioreReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.Graffato> cercaElencoSubalterniGraffatiConBelfiore(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvUiu")
        String in2,
        @WebParam(name = "in3", targetNamespace = "urn:sigalfsrvUiu")
        String in3
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniGraffatiPerIdentitaPersonaGiuridica", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniGraffatiPerIdentitaPersonaGiuridica")
    @ResponseWrapper(localName = "cercaElencoSubalterniGraffatiPerIdentitaPersonaGiuridicaResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniGraffatiPerIdentitaPersonaGiuridicaResponse")
    @WebResult(name = "cercaElencoSubalterniGraffatiPerIdentitaPersonaGiuridicaReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.Graffato> cercaElencoSubalterniGraffatiPerIdentitaPersonaGiuridica(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentitaPersonaGiuridica in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniConBelfioreESezione", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniConBelfioreESezione")
    @ResponseWrapper(localName = "cercaElencoSubalterniConBelfioreESezioneResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniConBelfioreESezioneResponse")
    @WebResult(name = "cercaElencoSubalterniConBelfioreESezioneReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentificativoCatastaleFabbricato> cercaElencoSubalterniConBelfioreESezione(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvUiu")
        String in2,
        @WebParam(name = "in3", targetNamespace = "urn:sigalfsrvUiu")
        String in3,
        @WebParam(name = "in4", targetNamespace = "urn:sigalfsrvUiu")
        String in4
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniConBelfioreSezioneESezioneUrbana", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniConBelfioreSezioneESezioneUrbana")
    @ResponseWrapper(localName = "cercaElencoSubalterniConBelfioreSezioneESezioneUrbanaResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniConBelfioreSezioneESezioneUrbanaResponse")
    @WebResult(name = "cercaElencoSubalterniConBelfioreSezioneESezioneUrbanaReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentificativoCatastaleFabbricato> cercaElencoSubalterniConBelfioreSezioneESezioneUrbana(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvUiu")
        String in2,
        @WebParam(name = "in3", targetNamespace = "urn:sigalfsrvUiu")
        String in3,
        @WebParam(name = "in4", targetNamespace = "urn:sigalfsrvUiu")
        String in4,
        @WebParam(name = "in5", targetNamespace = "urn:sigalfsrvUiu")
        String in5
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSezioniUrbaneDiUnComuneByIstat", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSezioniUrbaneDiUnComuneByIstat")
    @ResponseWrapper(localName = "cercaElencoSezioniUrbaneDiUnComuneByIstatResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSezioniUrbaneDiUnComuneByIstatResponse")
    @WebResult(name = "cercaElencoSezioniUrbaneDiUnComuneByIstatReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.SezioneUrbana> cercaElencoSezioniUrbaneDiUnComuneByIstat(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniGraffatiPerIdentitaPersonaFisica", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniGraffatiPerIdentitaPersonaFisica")
    @ResponseWrapper(localName = "cercaElencoSubalterniGraffatiPerIdentitaPersonaFisicaResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniGraffatiPerIdentitaPersonaFisicaResponse")
    @WebResult(name = "cercaElencoSubalterniGraffatiPerIdentitaPersonaFisicaReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.Graffato> cercaElencoSubalterniGraffatiPerIdentitaPersonaFisica(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentitaPersonaFisica in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoGraffatiDiUnIdentificativoCatastaleFabbricato", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoGraffatiDiUnIdentificativoCatastaleFabbricato")
    @ResponseWrapper(localName = "cercaElencoGraffatiDiUnIdentificativoCatastaleFabbricatoResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoGraffatiDiUnIdentificativoCatastaleFabbricatoResponse")
    @WebResult(name = "cercaElencoGraffatiDiUnIdentificativoCatastaleFabbricatoReturn", targetNamespace = "urn:sigalfsrvUiu")
    public it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.Graffato cercaElencoGraffatiDiUnIdentificativoCatastaleFabbricato(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentificativoCatastaleFabbricato in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniPerIdentitaPersonaGiuridica", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniPerIdentitaPersonaGiuridica")
    @ResponseWrapper(localName = "cercaElencoSubalterniPerIdentitaPersonaGiuridicaResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniPerIdentitaPersonaGiuridicaResponse")
    @WebResult(name = "cercaElencoSubalterniPerIdentitaPersonaGiuridicaReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentificativoCatastaleFabbricato> cercaElencoSubalterniPerIdentitaPersonaGiuridica(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentitaPersonaGiuridica in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniGraffatiConBelfioreSezioneESezioneUrbana", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniGraffatiConBelfioreSezioneESezioneUrbana")
    @ResponseWrapper(localName = "cercaElencoSubalterniGraffatiConBelfioreSezioneESezioneUrbanaResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniGraffatiConBelfioreSezioneESezioneUrbanaResponse")
    @WebResult(name = "cercaElencoSubalterniGraffatiConBelfioreSezioneESezioneUrbanaReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.Graffato> cercaElencoSubalterniGraffatiConBelfioreSezioneESezioneUrbana(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvUiu")
        String in2,
        @WebParam(name = "in3", targetNamespace = "urn:sigalfsrvUiu")
        String in3,
        @WebParam(name = "in4", targetNamespace = "urn:sigalfsrvUiu")
        String in4,
        @WebParam(name = "in5", targetNamespace = "urn:sigalfsrvUiu")
        String in5
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniPerIdentitaPersonaFisica", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniPerIdentitaPersonaFisica")
    @ResponseWrapper(localName = "cercaElencoSubalterniPerIdentitaPersonaFisicaResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniPerIdentitaPersonaFisicaResponse")
    @WebResult(name = "cercaElencoSubalterniPerIdentitaPersonaFisicaReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentificativoCatastaleFabbricato> cercaElencoSubalterniPerIdentitaPersonaFisica(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentitaPersonaFisica in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoIndirizziPerIdentificativoCatastale", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoIndirizziPerIdentificativoCatastale")
    @ResponseWrapper(localName = "cercaElencoIndirizziPerIdentificativoCatastaleResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoIndirizziPerIdentificativoCatastaleResponse")
    @WebResult(name = "cercaElencoIndirizziPerIdentificativoCatastaleReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.Indirizzo> cercaElencoIndirizziPerIdentificativoCatastale(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentificativoCatastaleFabbricato in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniConIstat", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniConIstat")
    @ResponseWrapper(localName = "cercaElencoSubalterniConIstatResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniConIstatResponse")
    @WebResult(name = "cercaElencoSubalterniConIstatReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentificativoCatastaleFabbricato> cercaElencoSubalterniConIstat(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvUiu")
        String in2,
        @WebParam(name = "in3", targetNamespace = "urn:sigalfsrvUiu")
        String in3
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniGraffatiConIstatSezioneESezioneUrbana", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniGraffatiConIstatSezioneESezioneUrbana")
    @ResponseWrapper(localName = "cercaElencoSubalterniGraffatiConIstatSezioneESezioneUrbanaResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniGraffatiConIstatSezioneESezioneUrbanaResponse")
    @WebResult(name = "cercaElencoSubalterniGraffatiConIstatSezioneESezioneUrbanaReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.Graffato> cercaElencoSubalterniGraffatiConIstatSezioneESezioneUrbana(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvUiu")
        String in2,
        @WebParam(name = "in3", targetNamespace = "urn:sigalfsrvUiu")
        String in3,
        @WebParam(name = "in4", targetNamespace = "urn:sigalfsrvUiu")
        String in4,
        @WebParam(name = "in5", targetNamespace = "urn:sigalfsrvUiu")
        String in5
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniGraffatiConIstatESezione", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniGraffatiConIstatESezione")
    @ResponseWrapper(localName = "cercaElencoSubalterniGraffatiConIstatESezioneResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniGraffatiConIstatESezioneResponse")
    @WebResult(name = "cercaElencoSubalterniGraffatiConIstatESezioneReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.Graffato> cercaElencoSubalterniGraffatiConIstatESezione(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvUiu")
        String in2,
        @WebParam(name = "in3", targetNamespace = "urn:sigalfsrvUiu")
        String in3,
        @WebParam(name = "in4", targetNamespace = "urn:sigalfsrvUiu")
        String in4
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaDettaglioDatiFabbricato", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaDettaglioDatiFabbricato")
    @ResponseWrapper(localName = "cercaDettaglioDatiFabbricatoResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaDettaglioDatiFabbricatoResponse")
    @WebResult(name = "cercaDettaglioDatiFabbricatoReturn", targetNamespace = "urn:sigalfsrvUiu")
    public it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.DettaglioDatiFabbricato cercaDettaglioDatiFabbricato(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentificativoCatastaleFabbricato in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "estraiPlanimetriaPerBelfioreEdIdImmaginePiantina", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.EstraiPlanimetriaPerBelfioreEdIdImmaginePiantina")
    @ResponseWrapper(localName = "estraiPlanimetriaPerBelfioreEdIdImmaginePiantinaResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.EstraiPlanimetriaPerBelfioreEdIdImmaginePiantinaResponse")
    @WebResult(name = "estraiPlanimetriaPerBelfioreEdIdImmaginePiantinaReturn", targetNamespace = "urn:sigalfsrvUiu")
    public byte[] estraiPlanimetriaPerBelfioreEdIdImmaginePiantina(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        Long in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvUiu")
        String in2
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniGraffatiConIstat", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniGraffatiConIstat")
    @ResponseWrapper(localName = "cercaElencoSubalterniGraffatiConIstatResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniGraffatiConIstatResponse")
    @WebResult(name = "cercaElencoSubalterniGraffatiConIstatReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.Graffato> cercaElencoSubalterniGraffatiConIstat(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvUiu")
        String in2,
        @WebParam(name = "in3", targetNamespace = "urn:sigalfsrvUiu")
        String in3
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSezioniUrbaneDiUnComuneByBelfiore", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSezioniUrbaneDiUnComuneByBelfiore")
    @ResponseWrapper(localName = "cercaElencoSezioniUrbaneDiUnComuneByBelfioreResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSezioniUrbaneDiUnComuneByBelfioreResponse")
    @WebResult(name = "cercaElencoSezioniUrbaneDiUnComuneByBelfioreReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.SezioneUrbana> cercaElencoSezioniUrbaneDiUnComuneByBelfiore(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaSchedePlanimetrichePerIdentificativoCatastale", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaSchedePlanimetrichePerIdentificativoCatastale")
    @ResponseWrapper(localName = "cercaSchedePlanimetrichePerIdentificativoCatastaleResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaSchedePlanimetrichePerIdentificativoCatastaleResponse")
    @WebResult(name = "cercaSchedePlanimetrichePerIdentificativoCatastaleReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.Planimetria> cercaSchedePlanimetrichePerIdentificativoCatastale(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentificativoCatastaleFabbricato in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaIndirizziPerIdentificativoCatastaleFabbricato", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaIndirizziPerIdentificativoCatastaleFabbricato")
    @ResponseWrapper(localName = "cercaIndirizziPerIdentificativoCatastaleFabbricatoResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaIndirizziPerIdentificativoCatastaleFabbricatoResponse")
    @WebResult(name = "cercaIndirizziPerIdentificativoCatastaleFabbricatoReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.Indirizzo> cercaIndirizziPerIdentificativoCatastaleFabbricato(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentificativoCatastaleFabbricato in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaDettaglioDatiRiserveFabbricato", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaDettaglioDatiRiserveFabbricato")
    @ResponseWrapper(localName = "cercaDettaglioDatiRiserveFabbricatoResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaDettaglioDatiRiserveFabbricatoResponse")
    @WebResult(name = "cercaDettaglioDatiRiserveFabbricatoReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.DettaglioDatiRiserva> cercaDettaglioDatiRiserveFabbricato(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentificativoCatastaleFabbricato in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniConIstatESezione", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniConIstatESezione")
    @ResponseWrapper(localName = "cercaElencoSubalterniConIstatESezioneResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniConIstatESezioneResponse")
    @WebResult(name = "cercaElencoSubalterniConIstatESezioneReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentificativoCatastaleFabbricato> cercaElencoSubalterniConIstatESezione(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvUiu")
        String in2,
        @WebParam(name = "in3", targetNamespace = "urn:sigalfsrvUiu")
        String in3,
        @WebParam(name = "in4", targetNamespace = "urn:sigalfsrvUiu")
        String in4
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniConBelfiore", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniConBelfiore")
    @ResponseWrapper(localName = "cercaElencoSubalterniConBelfioreResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniConBelfioreResponse")
    @WebResult(name = "cercaElencoSubalterniConBelfioreReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentificativoCatastaleFabbricato> cercaElencoSubalterniConBelfiore(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvUiu")
        String in2,
        @WebParam(name = "in3", targetNamespace = "urn:sigalfsrvUiu")
        String in3
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniConIstatSezioneESezioneUrbana", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniConIstatSezioneESezioneUrbana")
    @ResponseWrapper(localName = "cercaElencoSubalterniConIstatSezioneESezioneUrbanaResponse", targetNamespace = "urn:sigalfsrvUiu", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.CercaElencoSubalterniConIstatSezioneESezioneUrbanaResponse")
    @WebResult(name = "cercaElencoSubalterniConIstatSezioneESezioneUrbanaReturn", targetNamespace = "urn:sigalfsrvUiu")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.IdentificativoCatastaleFabbricato> cercaElencoSubalterniConIstatSezioneESezioneUrbana(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvUiu")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvUiu")
        String in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvUiu")
        String in2,
        @WebParam(name = "in3", targetNamespace = "urn:sigalfsrvUiu")
        String in3,
        @WebParam(name = "in4", targetNamespace = "urn:sigalfsrvUiu")
        String in4,
        @WebParam(name = "in5", targetNamespace = "urn:sigalfsrvUiu")
        String in5
    ) throws ParInputObblMancantiException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception;
}
