/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-07-14T15:53:54.632+02:00
 * Generated source version: 3.5.1
 *
 */
@WebServiceClient(name = "sigalfsrvUiuService",
                  wsdlLocation = "file:wsdl/sigalfsrvUiu.wsdl",
                  targetNamespace = "urn:sigalfsrvUiu")
public class SigalfsrvUiuService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sigalfsrvUiu", "sigalfsrvUiuService");
    public final static QName SigalfsrvUiu = new QName("urn:sigalfsrvUiu", "sigalfsrvUiu");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/sigalfsrvUiu.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SigalfsrvUiuService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:wsdl/sigalfsrvUiu.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SigalfsrvUiuService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SigalfsrvUiuService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SigalfsrvUiuService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     *     returns SigalfsrvUiu
     */
    @WebEndpoint(name = "sigalfsrvUiu")
    public SigalfsrvUiu getSigalfsrvUiu() {
        return super.getPort(SigalfsrvUiu, SigalfsrvUiu.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.

     *     returns SigalfsrvUiu
     */
    @WebEndpoint(name = "sigalfsrvUiu")
    public SigalfsrvUiu getSigalfsrvUiu(WebServiceFeature... features) {
        return super.getPort(SigalfsrvUiu, SigalfsrvUiu.class, features);
    }

}
