/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu;

import javax.xml.ws.WebFault;
/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-07-14T15:53:54.594+02:00
 * Generated source version: 3.5.1
 */

@WebFault(name = "fault1", targetNamespace = "urn:sigalfsrvUiu")
public class SystemException_Exception extends Exception {

    private it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.SystemException faultInfo;

    public SystemException_Exception() {
        super();
    }

    public SystemException_Exception(String message) {
        super(message);
    }

    public SystemException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SystemException_Exception(String message, it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.SystemException fault1) {
        super(message);
        this.faultInfo = fault1;
    }

    public SystemException_Exception(String message, it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.SystemException fault1, Throwable cause) {
        super(message, cause);
        this.faultInfo = fault1;
    }

    public it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.uiu.SystemException getFaultInfo() {
        return this.faultInfo;
    }
}
