export enum USER_PROFILE {
  CREATORE_IST_PM_OBB = "CREATORE_IST_PM_OBB",
  CREATORE_IST_PM_OPZ = "CREATORE_IST_PM_OPZ",
  PM_RUP_PM_OBB = "PM_RUP_PM_OBB",
  PM_RUP_PM_OPZ = "PM_RUP_PM_OPZ",
  PROF_SPEC = "PROF_SPEC",
  CONSULTATORE = "CONSULTATORE",
  FASCIC_CREATORE = "FASCIC_CREATORE",
  FASCIC_CONSULTATORE = "FASCIC_CONSULTATORE",
  FASCIC_CREATORE_IST = "FASCIC_CREATORE_IST",
  COLLAB_PM_RUP_PM_OBB = "COLLAB_PM_RUP_PM_OBB",
  COLLAB_PM_RUP_PM_OPZ = "COLLAB_PM_RUP_PM_OPZ"
}
