/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni;

import javax.xml.ws.WebFault;
/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-07-14T15:53:25.025+02:00
 * Generated source version: 3.5.1
 */

@WebFault(name = "fault6", targetNamespace = "urn:sigalfsrvTerreni")
public class ParInputValNonCorrettoException_Exception extends Exception {

    private it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.ParInputValNonCorrettoException faultInfo;

    public ParInputValNonCorrettoException_Exception() {
        super();
    }

    public ParInputValNonCorrettoException_Exception(String message) {
        super(message);
    }

    public ParInputValNonCorrettoException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ParInputValNonCorrettoException_Exception(String message, it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.ParInputValNonCorrettoException fault6) {
        super(message);
        this.faultInfo = fault6;
    }

    public ParInputValNonCorrettoException_Exception(String message, it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.ParInputValNonCorrettoException fault6, Throwable cause) {
        super(message, cause);
        this.faultInfo = fault6;
    }

    public it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.ParInputValNonCorrettoException getFaultInfo() {
        return this.faultInfo;
    }
}
