/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-07-14T15:53:25.065+02:00
 * Generated source version: 3.5.1
 *
 */
@WebServiceClient(name = "sigalfsrvTerreniService",
                  wsdlLocation = "file:wsdl/sigalfsrvTerreni.wsdl",
                  targetNamespace = "urn:sigalfsrvTerreni")
public class SigalfsrvTerreniService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sigalfsrvTerreni", "sigalfsrvTerreniService");
    public final static QName SigalfsrvTerreni = new QName("urn:sigalfsrvTerreni", "sigalfsrvTerreni");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/sigalfsrvTerreni.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SigalfsrvTerreniService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:wsdl/sigalfsrvTerreni.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SigalfsrvTerreniService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SigalfsrvTerreniService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SigalfsrvTerreniService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     *     returns SigalfsrvTerreni
     */
    @WebEndpoint(name = "sigalfsrvTerreni")
    public SigalfsrvTerreni getSigalfsrvTerreni() {
        return super.getPort(SigalfsrvTerreni, SigalfsrvTerreni.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.

     *     returns SigalfsrvTerreni
     */
    @WebEndpoint(name = "sigalfsrvTerreni")
    public SigalfsrvTerreni getSigalfsrvTerreni(WebServiceFeature... features) {
        return super.getPort(SigalfsrvTerreni, SigalfsrvTerreni.class, features);
    }

}
