/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-07-14T15:53:25.049+02:00
 * Generated source version: 3.5.1
 *
 */
@WebService(targetNamespace = "urn:sigalfsrvTerreni", name = "sigalfsrvTerreni")
@XmlSeeAlso({ObjectFactory.class})
public interface SigalfsrvTerreni {

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniTerreniConIstat", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaElencoSubalterniTerreniConIstat")
    @ResponseWrapper(localName = "cercaElencoSubalterniTerreniConIstatResponse", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaElencoSubalterniTerreniConIstatResponse")
    @WebResult(name = "cercaElencoSubalterniTerreniConIstatReturn", targetNamespace = "urn:sigalfsrvTerreni")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.IdentificativoCatastaleTerreno> cercaElencoSubalterniTerreniConIstat(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTerreni")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTerreni")
        long in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvTerreni")
        String in2,
        @WebParam(name = "in3", targetNamespace = "urn:sigalfsrvTerreni")
        String in3
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaDettaglioDatiRiserveTerreno", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaDettaglioDatiRiserveTerreno")
    @ResponseWrapper(localName = "cercaDettaglioDatiRiserveTerrenoResponse", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaDettaglioDatiRiserveTerrenoResponse")
    @WebResult(name = "cercaDettaglioDatiRiserveTerrenoReturn", targetNamespace = "urn:sigalfsrvTerreni")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.DettaglioDatiRiservaTerreno> cercaDettaglioDatiRiserveTerreno(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTerreni")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.IdentificativoCatastaleTerreno in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTerreni")
        String in1
    ) throws OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, ParInputObblMancantiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "determinaRedditoDominicalePerIdentificativoCatastaleTerreno", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.DeterminaRedditoDominicalePerIdentificativoCatastaleTerreno")
    @ResponseWrapper(localName = "determinaRedditoDominicalePerIdentificativoCatastaleTerrenoResponse", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.DeterminaRedditoDominicalePerIdentificativoCatastaleTerrenoResponse")
    @WebResult(name = "determinaRedditoDominicalePerIdentificativoCatastaleTerrenoReturn", targetNamespace = "urn:sigalfsrvTerreni")
    public double determinaRedditoDominicalePerIdentificativoCatastaleTerreno(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTerreni")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.IdentificativoCatastaleTerreno in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTerreni")
        String in1
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaDettaglioDatiPorzioni", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaDettaglioDatiPorzioni")
    @ResponseWrapper(localName = "cercaDettaglioDatiPorzioniResponse", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaDettaglioDatiPorzioniResponse")
    @WebResult(name = "cercaDettaglioDatiPorzioniReturn", targetNamespace = "urn:sigalfsrvTerreni")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.DettaglioDatiPorzione> cercaDettaglioDatiPorzioni(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTerreni")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.IdentificativoCatastaleTerreno in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTerreni")
        String in1
    ) throws OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, ParInputObblMancantiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniTerreniPerIdentitaPersonaGiuridica", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaElencoSubalterniTerreniPerIdentitaPersonaGiuridica")
    @ResponseWrapper(localName = "cercaElencoSubalterniTerreniPerIdentitaPersonaGiuridicaResponse", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaElencoSubalterniTerreniPerIdentitaPersonaGiuridicaResponse")
    @WebResult(name = "cercaElencoSubalterniTerreniPerIdentitaPersonaGiuridicaReturn", targetNamespace = "urn:sigalfsrvTerreni")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.IdentificativoCatastaleTerreno> cercaElencoSubalterniTerreniPerIdentitaPersonaGiuridica(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTerreni")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.IdentitaPersonaGiuridica in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTerreni")
        String in1
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniTerreniPerIdentitaPersonaFisica", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaElencoSubalterniTerreniPerIdentitaPersonaFisica")
    @ResponseWrapper(localName = "cercaElencoSubalterniTerreniPerIdentitaPersonaFisicaResponse", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaElencoSubalterniTerreniPerIdentitaPersonaFisicaResponse")
    @WebResult(name = "cercaElencoSubalterniTerreniPerIdentitaPersonaFisicaReturn", targetNamespace = "urn:sigalfsrvTerreni")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.IdentificativoCatastaleTerreno> cercaElencoSubalterniTerreniPerIdentitaPersonaFisica(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTerreni")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.IdentitaPersonaFisica in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTerreni")
        String in1
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaDettaglioDatiDeduzioniPorzione", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaDettaglioDatiDeduzioniPorzione")
    @ResponseWrapper(localName = "cercaDettaglioDatiDeduzioniPorzioneResponse", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaDettaglioDatiDeduzioniPorzioneResponse")
    @WebResult(name = "cercaDettaglioDatiDeduzioniPorzioneReturn", targetNamespace = "urn:sigalfsrvTerreni")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.DettaglioDatiDeduzione> cercaDettaglioDatiDeduzioniPorzione(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTerreni")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.IdentificativoCatastaleTerreno in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTerreni")
        String in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvTerreni")
        String in2
    ) throws OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, ParInputObblMancantiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniTerreniConBelfiore", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaElencoSubalterniTerreniConBelfiore")
    @ResponseWrapper(localName = "cercaElencoSubalterniTerreniConBelfioreResponse", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaElencoSubalterniTerreniConBelfioreResponse")
    @WebResult(name = "cercaElencoSubalterniTerreniConBelfioreReturn", targetNamespace = "urn:sigalfsrvTerreni")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.IdentificativoCatastaleTerreno> cercaElencoSubalterniTerreniConBelfiore(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTerreni")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTerreni")
        long in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvTerreni")
        String in2,
        @WebParam(name = "in3", targetNamespace = "urn:sigalfsrvTerreni")
        String in3
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniTerreniConIstatESezione", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaElencoSubalterniTerreniConIstatESezione")
    @ResponseWrapper(localName = "cercaElencoSubalterniTerreniConIstatESezioneResponse", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaElencoSubalterniTerreniConIstatESezioneResponse")
    @WebResult(name = "cercaElencoSubalterniTerreniConIstatESezioneReturn", targetNamespace = "urn:sigalfsrvTerreni")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.IdentificativoCatastaleTerreno> cercaElencoSubalterniTerreniConIstatESezione(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTerreni")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTerreni")
        String in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvTerreni")
        long in2,
        @WebParam(name = "in3", targetNamespace = "urn:sigalfsrvTerreni")
        String in3,
        @WebParam(name = "in4", targetNamespace = "urn:sigalfsrvTerreni")
        String in4
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSezioniCensuarieDiUnComuneByIstat", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaElencoSezioniCensuarieDiUnComuneByIstat")
    @ResponseWrapper(localName = "cercaElencoSezioniCensuarieDiUnComuneByIstatResponse", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaElencoSezioniCensuarieDiUnComuneByIstatResponse")
    @WebResult(name = "cercaElencoSezioniCensuarieDiUnComuneByIstatReturn", targetNamespace = "urn:sigalfsrvTerreni")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.SezioneCensuaria> cercaElencoSezioniCensuarieDiUnComuneByIstat(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTerreni")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTerreni")
        String in1
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaDettaglioDatiDeduzioniTerreno", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaDettaglioDatiDeduzioniTerreno")
    @ResponseWrapper(localName = "cercaDettaglioDatiDeduzioniTerrenoResponse", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaDettaglioDatiDeduzioniTerrenoResponse")
    @WebResult(name = "cercaDettaglioDatiDeduzioniTerrenoReturn", targetNamespace = "urn:sigalfsrvTerreni")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.DettaglioDatiDeduzione> cercaDettaglioDatiDeduzioniTerreno(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTerreni")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.IdentificativoCatastaleTerreno in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTerreni")
        String in1
    ) throws OutputException_Exception, SystemException_Exception, ParInputValNonCorrettoException_Exception, CSIException_Exception, AutorizzMancanteEnteException_Exception, UnrecoverableException_Exception, PermissionException_Exception, ParInputObblMancantiException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSezioniCensuarieDiUnComuneByBelfiore", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaElencoSezioniCensuarieDiUnComuneByBelfiore")
    @ResponseWrapper(localName = "cercaElencoSezioniCensuarieDiUnComuneByBelfioreResponse", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaElencoSezioniCensuarieDiUnComuneByBelfioreResponse")
    @WebResult(name = "cercaElencoSezioniCensuarieDiUnComuneByBelfioreReturn", targetNamespace = "urn:sigalfsrvTerreni")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.SezioneCensuaria> cercaElencoSezioniCensuarieDiUnComuneByBelfiore(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTerreni")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTerreni")
        String in1
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaDettaglioDatiTerreno", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaDettaglioDatiTerreno")
    @ResponseWrapper(localName = "cercaDettaglioDatiTerrenoResponse", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaDettaglioDatiTerrenoResponse")
    @WebResult(name = "cercaDettaglioDatiTerrenoReturn", targetNamespace = "urn:sigalfsrvTerreni")
    public it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.DettaglioDatiTerreno cercaDettaglioDatiTerreno(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTerreni")
        it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.IdentificativoCatastaleTerreno in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTerreni")
        String in1
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "cercaElencoSubalterniTerreniConBelfioreESezione", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaElencoSubalterniTerreniConBelfioreESezione")
    @ResponseWrapper(localName = "cercaElencoSubalterniTerreniConBelfioreESezioneResponse", targetNamespace = "urn:sigalfsrvTerreni", className = "it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.CercaElencoSubalterniTerreniConBelfioreESezioneResponse")
    @WebResult(name = "cercaElencoSubalterniTerreniConBelfioreESezioneReturn", targetNamespace = "urn:sigalfsrvTerreni")
    public java.util.List<it.csi.mudeopen.mudeopensrvapi.business.be.helper.sigmater.terreni.IdentificativoCatastaleTerreno> cercaElencoSubalterniTerreniConBelfioreESezione(

        @WebParam(name = "in0", targetNamespace = "urn:sigalfsrvTerreni")
        String in0,
        @WebParam(name = "in1", targetNamespace = "urn:sigalfsrvTerreni")
        String in1,
        @WebParam(name = "in2", targetNamespace = "urn:sigalfsrvTerreni")
        long in2,
        @WebParam(name = "in3", targetNamespace = "urn:sigalfsrvTerreni")
        String in3,
        @WebParam(name = "in4", targetNamespace = "urn:sigalfsrvTerreni")
        String in4
    ) throws SystemException_Exception, CSIException_Exception, UnrecoverableException_Exception;
}
