/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.documenti;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-03-06T09:18:52.783+01:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://documenti.interfacews.mudesrvextsic.mude.csi.it/", name = "Documenti")
@XmlSeeAlso({ObjectFactory.class})
public interface Documenti {
    @WebMethod
    @RequestWrapper(localName = "estraiFileIstanza", targetNamespace = "http://documenti.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.documenti.EstraiFileIstanza")
    @ResponseWrapper(localName = "estraiFileIstanzaResponse", targetNamespace = "http://documenti.interfacews.mudesrvextsic.mude.csi.it/", className = "it.csi.mudeopen.mudeopensrvsoap.interfacews.documenti.EstraiFileIstanzaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.csi.mudeopen.mudeopensrvsoap.interfacews.documenti.FileOutput estraiFileIstanza(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "numeroIstanza", targetNamespace = "")
        java.lang.String numeroIstanza
    );
}
