/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.documenti;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-03-06T09:18:52.729+01:00
 * Generated source version: 3.2.2
 *
 */
@javax.jws.WebService(
                      serviceName = "DocumentiSrvService",
                      portName = "DocumentiSrvPort",
                      targetNamespace = "http://documenti.business.mudesrvextsic.mude.csi.it/",
                      wsdlLocation = "file:../_DOCS/_ANALISI/API/WSDL/DocumentiSrvService.wsdl",
                      endpointInterface = "it.csi.mudeopen.mudeopensrvsoap.interfacews.documenti.Documenti")
public class DocumentiSrvPortImpl implements Documenti {
    private static final Logger LOG = Logger.getLogger(DocumentiSrvPortImpl.class.getName());
    /* (non-Javadoc)
     * @see it.csi.mudeopen.mudeopensrvsoap.interfacews.documenti.Documenti#estraiFileIstanza(java.lang.String token, java.lang.String numeroIstanza)*
     */
    public it.csi.mudeopen.mudeopensrvsoap.interfacews.documenti.FileOutput estraiFileIstanza(java.lang.String token, java.lang.String numeroIstanza) {
        LOG.info("Executing operation estraiFileIstanza");
        try {
            it.csi.mudeopen.mudeopensrvsoap.interfacews.documenti.FileOutput _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
}
