/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.931+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "CognomeIntestatarioPersoneFisicheException", messageName = "CognomeIntestatarioPersoneFisicheException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class CognomeIntestatarioPersoneFisicheException_Exception extends MudeWSException {
    /**
	 * 
	 */
	private static final long serialVersionUID = 78936539433778L;
	private CognomeIntestatarioPersoneFisicheException cognomeIntestatarioPersoneFisicheException;
    public CognomeIntestatarioPersoneFisicheException_Exception() {
        super();
    }
    public CognomeIntestatarioPersoneFisicheException_Exception(String message) {
        super(message);
        this.cognomeIntestatarioPersoneFisicheException = new CognomeIntestatarioPersoneFisicheException();
    }
    public CognomeIntestatarioPersoneFisicheException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.cognomeIntestatarioPersoneFisicheException = new CognomeIntestatarioPersoneFisicheException();
    }
    public CognomeIntestatarioPersoneFisicheException_Exception(String message, CognomeIntestatarioPersoneFisicheException cognomeIntestatarioPersoneFisicheException) {
        super(message);
        this.cognomeIntestatarioPersoneFisicheException = cognomeIntestatarioPersoneFisicheException;
    }
    public CognomeIntestatarioPersoneFisicheException_Exception(String message, CognomeIntestatarioPersoneFisicheException cognomeIntestatarioPersoneFisicheException, Throwable cause) {
        super(message, cause);
        this.cognomeIntestatarioPersoneFisicheException = cognomeIntestatarioPersoneFisicheException;
    }
    public CognomeIntestatarioPersoneFisicheException getFaultInfo() {
        return this.cognomeIntestatarioPersoneFisicheException;
    }
}
