/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.854+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "DataNonValidaException", messageName = "DataNonValidaException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class DataNonValidaException_Exception extends MudeWSException {
	private static final long serialVersionUID = 19742956905L;
    private DataNonValidaException dataNonValidaException;
    public DataNonValidaException_Exception() {
        super();
    }
    public DataNonValidaException_Exception(String message) {
        super(message);
        this.dataNonValidaException = new DataNonValidaException();
    }
    public DataNonValidaException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.dataNonValidaException = new DataNonValidaException();
    }
    public DataNonValidaException_Exception(String message, DataNonValidaException dataNonValidaException) {
        super(message);
        this.dataNonValidaException = dataNonValidaException;
    }
    public DataNonValidaException_Exception(String message, DataNonValidaException dataNonValidaException, Throwable cause) {
        super(message, cause);
        this.dataNonValidaException = dataNonValidaException;
    }
    public DataNonValidaException getFaultInfo() {
        return this.dataNonValidaException;
    }
}
