/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.939+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "DocumentoPraticaInesistenteException", messageName = "DocumentoPraticaInesistenteException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class DocumentoPraticaInesistenteException_Exception extends MudeWSException {
 	private static final long serialVersionUID = 19747956905L;
    private DocumentoPraticaInesistenteException documentoPraticaInesistenteException;
    public DocumentoPraticaInesistenteException_Exception() {
        super();
    }
    public DocumentoPraticaInesistenteException_Exception(String message) {
        super(message);
        this.documentoPraticaInesistenteException = new DocumentoPraticaInesistenteException();
    }
    public DocumentoPraticaInesistenteException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.documentoPraticaInesistenteException = new DocumentoPraticaInesistenteException();
    }
    public DocumentoPraticaInesistenteException_Exception(String message, DocumentoPraticaInesistenteException documentoPraticaInesistenteException) {
        super(message);
        this.documentoPraticaInesistenteException = documentoPraticaInesistenteException;
    }
    public DocumentoPraticaInesistenteException_Exception(String message, DocumentoPraticaInesistenteException documentoPraticaInesistenteException, Throwable cause) {
        super(message, cause);
        this.documentoPraticaInesistenteException = documentoPraticaInesistenteException;
    }
    public DocumentoPraticaInesistenteException getFaultInfo() {
        return this.documentoPraticaInesistenteException;
    }
}
