/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.816+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "FruitoreNoComuniAssociatiException", messageName = "FruitoreNoComuniAssociatiException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class FruitoreNoComuniAssociatiException_Exception extends MudeWSException {
 	private static final long serialVersionUID = 2979956905L;
    private FruitoreNoComuniAssociatiException fruitoreNoComuniAssociatiException;
    public FruitoreNoComuniAssociatiException_Exception() {
        super();
    }
    public FruitoreNoComuniAssociatiException_Exception(String message) {
        super(message);
        this.fruitoreNoComuniAssociatiException = new FruitoreNoComuniAssociatiException();
    }
    public FruitoreNoComuniAssociatiException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.fruitoreNoComuniAssociatiException = new FruitoreNoComuniAssociatiException();
    }
    public FruitoreNoComuniAssociatiException_Exception(String message, FruitoreNoComuniAssociatiException fruitoreNoComuniAssociatiException) {
        super(message);
        this.fruitoreNoComuniAssociatiException = fruitoreNoComuniAssociatiException;
    }
    public FruitoreNoComuniAssociatiException_Exception(String message, FruitoreNoComuniAssociatiException fruitoreNoComuniAssociatiException, Throwable cause) {
        super(message, cause);
        this.fruitoreNoComuniAssociatiException = fruitoreNoComuniAssociatiException;
    }
    public FruitoreNoComuniAssociatiException getFaultInfo() {
        return this.fruitoreNoComuniAssociatiException;
    }
}
