/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.802+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "FruitoreNoModelliAssociatiException", messageName = "FruitoreNoModelliAssociatiException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class FruitoreNoModelliAssociatiException_Exception extends MudeWSException {
 	private static final long serialVersionUID = 9756749065901L;
    private FruitoreNoModelliAssociatiException fruitoreNoModelliAssociatiException;
    public FruitoreNoModelliAssociatiException_Exception() {
        super();
    }
    public FruitoreNoModelliAssociatiException_Exception(String message) {
        super(message);
        this.fruitoreNoModelliAssociatiException = new FruitoreNoModelliAssociatiException();
    }
    public FruitoreNoModelliAssociatiException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.fruitoreNoModelliAssociatiException = new FruitoreNoModelliAssociatiException();
    }
    public FruitoreNoModelliAssociatiException_Exception(String message, FruitoreNoModelliAssociatiException fruitoreNoModelliAssociatiException) {
        super(message);
        this.fruitoreNoModelliAssociatiException = fruitoreNoModelliAssociatiException;
    }
    public FruitoreNoModelliAssociatiException_Exception(String message, FruitoreNoModelliAssociatiException fruitoreNoModelliAssociatiException, Throwable cause) {
        super(message, cause);
        this.fruitoreNoModelliAssociatiException = fruitoreNoModelliAssociatiException;
    }
    public FruitoreNoModelliAssociatiException getFaultInfo() {
        return this.fruitoreNoModelliAssociatiException;
    }
}
