/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.797+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "FruitoreNonAbilitatoOperazioneException", messageName = "FruitoreNonAbilitatoOperazioneException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class FruitoreNonAbilitatoOperazioneException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private FruitoreNonAbilitatoOperazioneException fruitoreNonAbilitatoOperazioneException;
    public FruitoreNonAbilitatoOperazioneException_Exception() {
        super();
    }
    public FruitoreNonAbilitatoOperazioneException_Exception(String message) {
        super(message);
        this.fruitoreNonAbilitatoOperazioneException = new FruitoreNonAbilitatoOperazioneException();
    }
    public FruitoreNonAbilitatoOperazioneException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.fruitoreNonAbilitatoOperazioneException = new FruitoreNonAbilitatoOperazioneException();
    }
    public FruitoreNonAbilitatoOperazioneException_Exception(String message, FruitoreNonAbilitatoOperazioneException fruitoreNonAbilitatoOperazioneException) {
        super(message);
        this.fruitoreNonAbilitatoOperazioneException = fruitoreNonAbilitatoOperazioneException;
    }
    public FruitoreNonAbilitatoOperazioneException_Exception(String message, FruitoreNonAbilitatoOperazioneException fruitoreNonAbilitatoOperazioneException, Throwable cause) {
        super(message, cause);
        this.fruitoreNonAbilitatoOperazioneException = fruitoreNonAbilitatoOperazioneException;
    }
    public FruitoreNonAbilitatoOperazioneException getFaultInfo() {
        return this.fruitoreNonAbilitatoOperazioneException;
    }
}
