/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.785+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "FruitoreNonAbilitatoComuneException", messageName = "FruitoreNonAbilitatoComuneException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class FruitoreNonAbilitatoComuneException_Exception extends MudeWSException {
 	private static final long serialVersionUID = 1367956901L;
    private FruitoreNonAbilitatoComuneException fruitoreNonAbilitatoComuneException;
    public FruitoreNonAbilitatoComuneException_Exception() {
        super();
    }
    public FruitoreNonAbilitatoComuneException_Exception(String message) {
        super(message);
        this.fruitoreNonAbilitatoComuneException = new FruitoreNonAbilitatoComuneException();
    }
    public FruitoreNonAbilitatoComuneException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.fruitoreNonAbilitatoComuneException = new FruitoreNonAbilitatoComuneException();
    }
    public FruitoreNonAbilitatoComuneException_Exception(String message, FruitoreNonAbilitatoComuneException fruitoreNonAbilitatoComuneException) {
        super(message);
        this.fruitoreNonAbilitatoComuneException = fruitoreNonAbilitatoComuneException;
    }
    public FruitoreNonAbilitatoComuneException_Exception(String message, FruitoreNonAbilitatoComuneException fruitoreNonAbilitatoComuneException, Throwable cause) {
        super(message, cause);
        this.fruitoreNonAbilitatoComuneException = fruitoreNonAbilitatoComuneException;
    }
    public FruitoreNonAbilitatoComuneException getFaultInfo() {
        return this.fruitoreNonAbilitatoComuneException;
    }
}
