/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.746+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "FruitoreNonAbilitatoTipologiaIstanzaException", messageName = "FruitoreNonAbilitatoTipologiaIstanzaException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class FruitoreNonAbilitatoTipologiaIstanzaException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1l;
	
    private FruitoreNonAbilitatoTipologiaIstanzaException fruitoreNonAbilitatoTipologiaIstanzaException;
    public FruitoreNonAbilitatoTipologiaIstanzaException_Exception() {
        super();
    }
    public FruitoreNonAbilitatoTipologiaIstanzaException_Exception(String message) {
        super(message);
        this.fruitoreNonAbilitatoTipologiaIstanzaException = new FruitoreNonAbilitatoTipologiaIstanzaException();
    }
    public FruitoreNonAbilitatoTipologiaIstanzaException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.fruitoreNonAbilitatoTipologiaIstanzaException = new FruitoreNonAbilitatoTipologiaIstanzaException();
    }
    public FruitoreNonAbilitatoTipologiaIstanzaException_Exception(String message, FruitoreNonAbilitatoTipologiaIstanzaException fruitoreNonAbilitatoTipologiaIstanzaException) {
        super(message);
        this.fruitoreNonAbilitatoTipologiaIstanzaException = fruitoreNonAbilitatoTipologiaIstanzaException;
    }
    public FruitoreNonAbilitatoTipologiaIstanzaException_Exception(String message, FruitoreNonAbilitatoTipologiaIstanzaException fruitoreNonAbilitatoTipologiaIstanzaException, Throwable cause) {
        super(message, cause);
        this.fruitoreNonAbilitatoTipologiaIstanzaException = fruitoreNonAbilitatoTipologiaIstanzaException;
    }
    public FruitoreNonAbilitatoTipologiaIstanzaException getFaultInfo() {
        return this.fruitoreNonAbilitatoTipologiaIstanzaException;
    }
}
