/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.833+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "FruitoreNonAbilitatoModelloException", messageName = "FruitoreNonAbilitatoModelloException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class FruitoreNonAbilitatoModelloException_Exception extends MudeWSException {
 	private static final long serialVersionUID = 974295483902L;
    private FruitoreNonAbilitatoModelloException fruitoreNonAbilitatoModelloException;
    public FruitoreNonAbilitatoModelloException_Exception() {
        super();
    }
    public FruitoreNonAbilitatoModelloException_Exception(String message) {
        super(message);
        this.fruitoreNonAbilitatoModelloException = new FruitoreNonAbilitatoModelloException();
    }
    public FruitoreNonAbilitatoModelloException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.fruitoreNonAbilitatoModelloException = new FruitoreNonAbilitatoModelloException();
    }
    public FruitoreNonAbilitatoModelloException_Exception(String message, FruitoreNonAbilitatoModelloException fruitoreNonAbilitatoModelloException) {
        super(message);
        this.fruitoreNonAbilitatoModelloException = fruitoreNonAbilitatoModelloException;
    }
    public FruitoreNonAbilitatoModelloException_Exception(String message, FruitoreNonAbilitatoModelloException fruitoreNonAbilitatoModelloException, Throwable cause) {
        super(message, cause);
        this.fruitoreNonAbilitatoModelloException = fruitoreNonAbilitatoModelloException;
    }
    public FruitoreNonAbilitatoModelloException getFaultInfo() {
        return this.fruitoreNonAbilitatoModelloException;
    }
}
