/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.825+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "FunzioneNonAbilitataException", messageName = "FunzioneNonAbilitataException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class FunzioneNonAbilitataException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private FunzioneNonAbilitataException funzioneNonAbilitataException;
    public FunzioneNonAbilitataException_Exception() {
        super();
    }
    public FunzioneNonAbilitataException_Exception(String message) {
        super(message);
        this.funzioneNonAbilitataException = new FunzioneNonAbilitataException();
    }
    public FunzioneNonAbilitataException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.funzioneNonAbilitataException = new FunzioneNonAbilitataException();
    }
    public FunzioneNonAbilitataException_Exception(String message, FunzioneNonAbilitataException funzioneNonAbilitataException) {
        super(message);
        this.funzioneNonAbilitataException = funzioneNonAbilitataException;
    }
    public FunzioneNonAbilitataException_Exception(String message, FunzioneNonAbilitataException funzioneNonAbilitataException, Throwable cause) {
        super(message, cause);
        this.funzioneNonAbilitataException = funzioneNonAbilitataException;
    }
    public FunzioneNonAbilitataException getFaultInfo() {
        return this.funzioneNonAbilitataException;
    }
}
