/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.915+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "IntestatarioNonPresenteException", messageName = "IntestatarioNonPresenteException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class IntestatarioNonPresenteException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private IntestatarioNonPresenteException intestatarioNonPresenteException;
    public IntestatarioNonPresenteException_Exception() {
        super();
    }
    public IntestatarioNonPresenteException_Exception(String message) {
        super(message);
        this.intestatarioNonPresenteException = new IntestatarioNonPresenteException();
    }
    public IntestatarioNonPresenteException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.intestatarioNonPresenteException = new IntestatarioNonPresenteException();
    }
    public IntestatarioNonPresenteException_Exception(String message, IntestatarioNonPresenteException intestatarioNonPresenteException) {
        super(message);
        this.intestatarioNonPresenteException = intestatarioNonPresenteException;
    }
    public IntestatarioNonPresenteException_Exception(String message, IntestatarioNonPresenteException intestatarioNonPresenteException, Throwable cause) {
        super(message, cause);
        this.intestatarioNonPresenteException = intestatarioNonPresenteException;
    }
    public IntestatarioNonPresenteException getFaultInfo() {
        return this.intestatarioNonPresenteException;
    }
}
