/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.925+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "IstanzaInviataException", messageName = "IstanzaInviataException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class IstanzaInviataException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private IstanzaInviataException istanzaInviataException;
    public IstanzaInviataException_Exception() {
        super();
    }
    public IstanzaInviataException_Exception(String message) {
        super(message);
        this.istanzaInviataException = new IstanzaInviataException();
    }
    public IstanzaInviataException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.istanzaInviataException = new IstanzaInviataException();
    }
    public IstanzaInviataException_Exception(String message, IstanzaInviataException istanzaInviataException) {
        super(message);
        this.istanzaInviataException = istanzaInviataException;
    }
    public IstanzaInviataException_Exception(String message, IstanzaInviataException istanzaInviataException, Throwable cause) {
        super(message, cause);
        this.istanzaInviataException = istanzaInviataException;
    }
    public IstanzaInviataException getFaultInfo() {
        return this.istanzaInviataException;
    }
}
