/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.881+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "IstanzaNonConsultabileException", messageName = "IstanzaNonConsultabileException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class IstanzaNonConsultabileException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private IstanzaNonConsultabileException istanzaNonConsultabileException;
    public IstanzaNonConsultabileException_Exception() {
        super();
    }
    public IstanzaNonConsultabileException_Exception(String message) {
        super(message);
        this.istanzaNonConsultabileException = new IstanzaNonConsultabileException();
    }
    public IstanzaNonConsultabileException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.istanzaNonConsultabileException = new IstanzaNonConsultabileException();
    }
    public IstanzaNonConsultabileException_Exception(String message, IstanzaNonConsultabileException istanzaNonConsultabileException) {
        super(message);
        this.istanzaNonConsultabileException = istanzaNonConsultabileException;
    }
    public IstanzaNonConsultabileException_Exception(String message, IstanzaNonConsultabileException istanzaNonConsultabileException, Throwable cause) {
        super(message, cause);
        this.istanzaNonConsultabileException = istanzaNonConsultabileException;
    }
    public IstanzaNonConsultabileException getFaultInfo() {
        return this.istanzaNonConsultabileException;
    }
}
