/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.948+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "IstanzaNonRegistrataPAException", messageName = "IstanzaNonRegistrataPAException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class IstanzaNonRegistrataPAException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private IstanzaNonRegistrataPAException istanzaNonRegistrataPAException;
    public IstanzaNonRegistrataPAException_Exception() {
        super();
    }
    public IstanzaNonRegistrataPAException_Exception(String message) {
        super(message);
        this.istanzaNonRegistrataPAException = new IstanzaNonRegistrataPAException();
    }
    public IstanzaNonRegistrataPAException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.istanzaNonRegistrataPAException = new IstanzaNonRegistrataPAException();
    }
    public IstanzaNonRegistrataPAException_Exception(String message, IstanzaNonRegistrataPAException istanzaNonRegistrataPAException) {
        super(message);
        this.istanzaNonRegistrataPAException = istanzaNonRegistrataPAException;
    }
    public IstanzaNonRegistrataPAException_Exception(String message, IstanzaNonRegistrataPAException istanzaNonRegistrataPAException, Throwable cause) {
        super(message, cause);
        this.istanzaNonRegistrataPAException = istanzaNonRegistrataPAException;
    }
    public IstanzaNonRegistrataPAException getFaultInfo() {
        return this.istanzaNonRegistrataPAException;
    }
}
