/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.844+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "NomeIntestatarioPersoneFisicheException", messageName = "NomeIntestatarioPersoneFisicheException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class NomeIntestatarioPersoneFisicheException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private NomeIntestatarioPersoneFisicheException nomeIntestatarioPersoneFisicheException;
    public NomeIntestatarioPersoneFisicheException_Exception() {
        super();
    }
    public NomeIntestatarioPersoneFisicheException_Exception(String message) {
        super(message);
        this.nomeIntestatarioPersoneFisicheException = new NomeIntestatarioPersoneFisicheException();
    }
    public NomeIntestatarioPersoneFisicheException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.nomeIntestatarioPersoneFisicheException = new NomeIntestatarioPersoneFisicheException();
    }
    public NomeIntestatarioPersoneFisicheException_Exception(String message, NomeIntestatarioPersoneFisicheException nomeIntestatarioPersoneFisicheException) {
        super(message);
        this.nomeIntestatarioPersoneFisicheException = nomeIntestatarioPersoneFisicheException;
    }
    public NomeIntestatarioPersoneFisicheException_Exception(String message, NomeIntestatarioPersoneFisicheException nomeIntestatarioPersoneFisicheException, Throwable cause) {
        super(message, cause);
        this.nomeIntestatarioPersoneFisicheException = nomeIntestatarioPersoneFisicheException;
    }
    public NomeIntestatarioPersoneFisicheException getFaultInfo() {
        return this.nomeIntestatarioPersoneFisicheException;
    }
}
