/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.919+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "NumeroIstanzaNonCorrettoException", messageName = "NumeroIstanzaNonCorrettoException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class NumeroIstanzaNonCorrettoException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private NumeroIstanzaNonCorrettoException numeroIstanzaNonCorrettoException;
    public NumeroIstanzaNonCorrettoException_Exception() {
        super();
    }
    public NumeroIstanzaNonCorrettoException_Exception(String message) {
        super(message);
        this.numeroIstanzaNonCorrettoException = new NumeroIstanzaNonCorrettoException();
    }
    public NumeroIstanzaNonCorrettoException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.numeroIstanzaNonCorrettoException = new NumeroIstanzaNonCorrettoException();
    }
    public NumeroIstanzaNonCorrettoException_Exception(String message, NumeroIstanzaNonCorrettoException numeroIstanzaNonCorrettoException) {
        super(message);
        this.numeroIstanzaNonCorrettoException = numeroIstanzaNonCorrettoException;
    }
    public NumeroIstanzaNonCorrettoException_Exception(String message, NumeroIstanzaNonCorrettoException numeroIstanzaNonCorrettoException, Throwable cause) {
        super(message, cause);
        this.numeroIstanzaNonCorrettoException = numeroIstanzaNonCorrettoException;
    }
    public NumeroIstanzaNonCorrettoException getFaultInfo() {
        return this.numeroIstanzaNonCorrettoException;
    }
}
