/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.812+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "NumeroTicketInesistente", messageName = "NumeroTicketInesistente", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class NumeroTicketInesistente_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private NumeroTicketInesistente numeroTicketInesistente;
    public NumeroTicketInesistente_Exception() {
        super();
    }
    public NumeroTicketInesistente_Exception(String message) {
        super(message);
        this.numeroTicketInesistente = new NumeroTicketInesistente();
    }
    public NumeroTicketInesistente_Exception(String message, Throwable cause) {
        super(message, cause);
        this.numeroTicketInesistente = new NumeroTicketInesistente();
    }
    public NumeroTicketInesistente_Exception(String message, NumeroTicketInesistente numeroTicketInesistente) {
        super(message);
        this.numeroTicketInesistente = numeroTicketInesistente;
    }
    public NumeroTicketInesistente_Exception(String message, NumeroTicketInesistente numeroTicketInesistente, Throwable cause) {
        super(message, cause);
        this.numeroTicketInesistente = numeroTicketInesistente;
    }
    public NumeroTicketInesistente getFaultInfo() {
        return this.numeroTicketInesistente;
    }
}
