/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.888+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "NumeroFascicoloNonCorrettoException", messageName = "NumeroFascicoloNonCorrettoException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class NumeroFascicoloNonCorrettoException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private NumeroFascicoloNonCorrettoException numeroFascicoloNonCorrettoException;
    public NumeroFascicoloNonCorrettoException_Exception() {
        super();
    }
    public NumeroFascicoloNonCorrettoException_Exception(String message) {
        super(message);
        this.numeroFascicoloNonCorrettoException = new NumeroFascicoloNonCorrettoException();
    }
    public NumeroFascicoloNonCorrettoException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.numeroFascicoloNonCorrettoException = new NumeroFascicoloNonCorrettoException();
    }
    public NumeroFascicoloNonCorrettoException_Exception(String message, NumeroFascicoloNonCorrettoException numeroFascicoloNonCorrettoException) {
        super(message);
        this.numeroFascicoloNonCorrettoException = numeroFascicoloNonCorrettoException;
    }
    public NumeroFascicoloNonCorrettoException_Exception(String message, NumeroFascicoloNonCorrettoException numeroFascicoloNonCorrettoException, Throwable cause) {
        super(message, cause);
        this.numeroFascicoloNonCorrettoException = numeroFascicoloNonCorrettoException;
    }
    public NumeroFascicoloNonCorrettoException getFaultInfo() {
        return this.numeroFascicoloNonCorrettoException;
    }
}
