/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.922+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "NumeroFascicoloComuneNonCoerentiException", messageName = "NumeroFascicoloComuneNonCoerentiException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class NumeroFascicoloComuneNonCoerentiException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private NumeroFascicoloComuneNonCoerentiException numeroFascicoloComuneNonCoerentiException;
    public NumeroFascicoloComuneNonCoerentiException_Exception() {
        super();
    }
    public NumeroFascicoloComuneNonCoerentiException_Exception(String message) {
        super(message);
        this.numeroFascicoloComuneNonCoerentiException = new NumeroFascicoloComuneNonCoerentiException();
    }
    public NumeroFascicoloComuneNonCoerentiException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.numeroFascicoloComuneNonCoerentiException = new NumeroFascicoloComuneNonCoerentiException();
    }
    public NumeroFascicoloComuneNonCoerentiException_Exception(String message, NumeroFascicoloComuneNonCoerentiException numeroFascicoloComuneNonCoerentiException) {
        super(message);
        this.numeroFascicoloComuneNonCoerentiException = numeroFascicoloComuneNonCoerentiException;
    }
    public NumeroFascicoloComuneNonCoerentiException_Exception(String message, NumeroFascicoloComuneNonCoerentiException numeroFascicoloComuneNonCoerentiException, Throwable cause) {
        super(message, cause);
        this.numeroFascicoloComuneNonCoerentiException = numeroFascicoloComuneNonCoerentiException;
    }
    public NumeroFascicoloComuneNonCoerentiException getFaultInfo() {
        return this.numeroFascicoloComuneNonCoerentiException;
    }
}
