/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.934+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "NumeroIstanzaObbligatorioException", messageName = "NumeroIstanzaObbligatorioException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class NumeroIstanzaObbligatorioException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private NumeroIstanzaObbligatorioException numeroIstanzaObbligatorioException;
    public NumeroIstanzaObbligatorioException_Exception() {
        super();
    }
    public NumeroIstanzaObbligatorioException_Exception(String message) {
        super(message);
        this.numeroIstanzaObbligatorioException = new NumeroIstanzaObbligatorioException();
    }
    public NumeroIstanzaObbligatorioException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.numeroIstanzaObbligatorioException = new NumeroIstanzaObbligatorioException();
    }
    public NumeroIstanzaObbligatorioException_Exception(String message, NumeroIstanzaObbligatorioException numeroIstanzaObbligatorioException) {
        super(message);
        this.numeroIstanzaObbligatorioException = numeroIstanzaObbligatorioException;
    }
    public NumeroIstanzaObbligatorioException_Exception(String message, NumeroIstanzaObbligatorioException numeroIstanzaObbligatorioException, Throwable cause) {
        super(message, cause);
        this.numeroIstanzaObbligatorioException = numeroIstanzaObbligatorioException;
    }
    public NumeroIstanzaObbligatorioException getFaultInfo() {
        return this.numeroIstanzaObbligatorioException;
    }
}
