/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.877+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "NumeroIstanzaRiferimentoInesistenteException", messageName = "NumeroIstanzaRiferimentoInesistenteException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class NumeroIstanzaRiferimentoInesistenteException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private NumeroIstanzaRiferimentoInesistenteException numeroIstanzaRiferimentoInesistenteException;
    public NumeroIstanzaRiferimentoInesistenteException_Exception() {
        super();
    }
    public NumeroIstanzaRiferimentoInesistenteException_Exception(String message) {
        super(message);
        this.numeroIstanzaRiferimentoInesistenteException = new NumeroIstanzaRiferimentoInesistenteException();
    }
    public NumeroIstanzaRiferimentoInesistenteException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.numeroIstanzaRiferimentoInesistenteException = new NumeroIstanzaRiferimentoInesistenteException();
    }
    public NumeroIstanzaRiferimentoInesistenteException_Exception(String message, NumeroIstanzaRiferimentoInesistenteException numeroIstanzaRiferimentoInesistenteException) {
        super(message);
        this.numeroIstanzaRiferimentoInesistenteException = numeroIstanzaRiferimentoInesistenteException;
    }
    public NumeroIstanzaRiferimentoInesistenteException_Exception(String message, NumeroIstanzaRiferimentoInesistenteException numeroIstanzaRiferimentoInesistenteException, Throwable cause) {
        super(message, cause);
        this.numeroIstanzaRiferimentoInesistenteException = numeroIstanzaRiferimentoInesistenteException;
    }
    public NumeroIstanzaRiferimentoInesistenteException getFaultInfo() {
        return this.numeroIstanzaRiferimentoInesistenteException;
    }
}
