/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.927+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "PraticaNonConsultabileException", messageName = "PraticaNonConsultabileException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class PraticaNonConsultabileException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private PraticaNonConsultabileException praticaNonConsultabileException;
    public PraticaNonConsultabileException_Exception() {
        super();
    }
    public PraticaNonConsultabileException_Exception(String message) {
        super(message);
        this.praticaNonConsultabileException = new PraticaNonConsultabileException();
    }
    public PraticaNonConsultabileException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.praticaNonConsultabileException = new PraticaNonConsultabileException();
    }
    public PraticaNonConsultabileException_Exception(String message, PraticaNonConsultabileException praticaNonConsultabileException) {
        super(message);
        this.praticaNonConsultabileException = praticaNonConsultabileException;
    }
    public PraticaNonConsultabileException_Exception(String message, PraticaNonConsultabileException praticaNonConsultabileException, Throwable cause) {
        super(message, cause);
        this.praticaNonConsultabileException = praticaNonConsultabileException;
    }
    public PraticaNonConsultabileException getFaultInfo() {
        return this.praticaNonConsultabileException;
    }
}
