/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.944+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "RagioneSocialeIntestatarioPersoneGiuridicheException", messageName = "RagioneSocialeIntestatarioPersoneGiuridicheException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class RagioneSocialeIntestatarioPersoneGiuridicheException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private RagioneSocialeIntestatarioPersoneGiuridicheException ragioneSocialeIntestatarioPersoneGiuridicheException;
    public RagioneSocialeIntestatarioPersoneGiuridicheException_Exception() {
        super();
    }
    public RagioneSocialeIntestatarioPersoneGiuridicheException_Exception(String message) {
        super(message);
        this.ragioneSocialeIntestatarioPersoneGiuridicheException = new RagioneSocialeIntestatarioPersoneGiuridicheException();
    }
    public RagioneSocialeIntestatarioPersoneGiuridicheException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.ragioneSocialeIntestatarioPersoneGiuridicheException = new RagioneSocialeIntestatarioPersoneGiuridicheException();
    }
    public RagioneSocialeIntestatarioPersoneGiuridicheException_Exception(String message, RagioneSocialeIntestatarioPersoneGiuridicheException ragioneSocialeIntestatarioPersoneGiuridicheException) {
        super(message);
        this.ragioneSocialeIntestatarioPersoneGiuridicheException = ragioneSocialeIntestatarioPersoneGiuridicheException;
    }
    public RagioneSocialeIntestatarioPersoneGiuridicheException_Exception(String message, RagioneSocialeIntestatarioPersoneGiuridicheException ragioneSocialeIntestatarioPersoneGiuridicheException, Throwable cause) {
        super(message, cause);
        this.ragioneSocialeIntestatarioPersoneGiuridicheException = ragioneSocialeIntestatarioPersoneGiuridicheException;
    }
    public RagioneSocialeIntestatarioPersoneGiuridicheException getFaultInfo() {
        return this.ragioneSocialeIntestatarioPersoneGiuridicheException;
    }
}
