/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.848+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "RuoloUtenteNonValidoException", messageName = "RuoloUtenteNonValidoException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class RuoloUtenteNonValidoException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private RuoloUtenteNonValidoException ruoloUtenteNonValidoException;
    public RuoloUtenteNonValidoException_Exception() {
        super();
    }
    public RuoloUtenteNonValidoException_Exception(String message) {
        super(message);
        this.ruoloUtenteNonValidoException = new RuoloUtenteNonValidoException();
    }
    public RuoloUtenteNonValidoException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.ruoloUtenteNonValidoException = new RuoloUtenteNonValidoException();
    }
    public RuoloUtenteNonValidoException_Exception(String message, RuoloUtenteNonValidoException ruoloUtenteNonValidoException) {
        super(message);
        this.ruoloUtenteNonValidoException = ruoloUtenteNonValidoException;
    }
    public RuoloUtenteNonValidoException_Exception(String message, RuoloUtenteNonValidoException ruoloUtenteNonValidoException, Throwable cause) {
        super(message, cause);
        this.ruoloUtenteNonValidoException = ruoloUtenteNonValidoException;
    }
    public RuoloUtenteNonValidoException getFaultInfo() {
        return this.ruoloUtenteNonValidoException;
    }
}
