/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.942+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "SpeciePraticaNonAbilitataException", messageName = "SpeciePraticaNonAbilitataException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class SpeciePraticaNonAbilitataException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private SpeciePraticaNonAbilitataException speciePraticaNonAbilitataException;
    public SpeciePraticaNonAbilitataException_Exception() {
        super();
    }
    public SpeciePraticaNonAbilitataException_Exception(String message) {
        super(message);
        this.speciePraticaNonAbilitataException = new SpeciePraticaNonAbilitataException();
    }
    public SpeciePraticaNonAbilitataException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.speciePraticaNonAbilitataException = new SpeciePraticaNonAbilitataException();
    }
    public SpeciePraticaNonAbilitataException_Exception(String message, SpeciePraticaNonAbilitataException speciePraticaNonAbilitataException) {
        super(message);
        this.speciePraticaNonAbilitataException = speciePraticaNonAbilitataException;
    }
    public SpeciePraticaNonAbilitataException_Exception(String message, SpeciePraticaNonAbilitataException speciePraticaNonAbilitataException, Throwable cause) {
        super(message, cause);
        this.speciePraticaNonAbilitataException = speciePraticaNonAbilitataException;
    }
    public SpeciePraticaNonAbilitataException getFaultInfo() {
        return this.speciePraticaNonAbilitataException;
    }
}
