/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.906+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "SpeciePraticaNonRiferitaModelloException", messageName = "SpeciePraticaNonRiferitaModelloException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class SpeciePraticaNonRiferitaModelloException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private SpeciePraticaNonRiferitaModelloException speciePraticaNonRiferitaModelloException;
    public SpeciePraticaNonRiferitaModelloException_Exception() {
        super();
    }
    public SpeciePraticaNonRiferitaModelloException_Exception(String message) {
        super(message);
        this.speciePraticaNonRiferitaModelloException = new SpeciePraticaNonRiferitaModelloException();
    }
    public SpeciePraticaNonRiferitaModelloException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.speciePraticaNonRiferitaModelloException = new SpeciePraticaNonRiferitaModelloException();
    }
    public SpeciePraticaNonRiferitaModelloException_Exception(String message, SpeciePraticaNonRiferitaModelloException speciePraticaNonRiferitaModelloException) {
        super(message);
        this.speciePraticaNonRiferitaModelloException = speciePraticaNonRiferitaModelloException;
    }
    public SpeciePraticaNonRiferitaModelloException_Exception(String message, SpeciePraticaNonRiferitaModelloException speciePraticaNonRiferitaModelloException, Throwable cause) {
        super(message, cause);
        this.speciePraticaNonRiferitaModelloException = speciePraticaNonRiferitaModelloException;
    }
    public SpeciePraticaNonRiferitaModelloException getFaultInfo() {
        return this.speciePraticaNonRiferitaModelloException;
    }
}
