/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.869+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "TipoTracciatoNonPrevistoTipoIstanzaException", messageName = "TipoTracciatoNonPrevistoTipoIstanzaException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class TipoTracciatoNonPrevistoTipoIstanzaException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private TipoTracciatoNonPrevistoTipoIstanzaException tipoTracciatoNonPrevistoTipoIstanzaException;
    public TipoTracciatoNonPrevistoTipoIstanzaException_Exception() {
        super();
    }
    public TipoTracciatoNonPrevistoTipoIstanzaException_Exception(String message) {
        super(message);
        this.tipoTracciatoNonPrevistoTipoIstanzaException = new TipoTracciatoNonPrevistoTipoIstanzaException();
    }
    public TipoTracciatoNonPrevistoTipoIstanzaException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.tipoTracciatoNonPrevistoTipoIstanzaException = new TipoTracciatoNonPrevistoTipoIstanzaException();
    }
    public TipoTracciatoNonPrevistoTipoIstanzaException_Exception(String message, TipoTracciatoNonPrevistoTipoIstanzaException tipoTracciatoNonPrevistoTipoIstanzaException) {
        super(message);
        this.tipoTracciatoNonPrevistoTipoIstanzaException = tipoTracciatoNonPrevistoTipoIstanzaException;
    }
    public TipoTracciatoNonPrevistoTipoIstanzaException_Exception(String message, TipoTracciatoNonPrevistoTipoIstanzaException tipoTracciatoNonPrevistoTipoIstanzaException, Throwable cause) {
        super(message, cause);
        this.tipoTracciatoNonPrevistoTipoIstanzaException = tipoTracciatoNonPrevistoTipoIstanzaException;
    }
    public TipoTracciatoNonPrevistoTipoIstanzaException getFaultInfo() {
        return this.tipoTracciatoNonPrevistoTipoIstanzaException;
    }
}
