/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.892+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "TipoTracciatoNonAbilitatoException", messageName = "TipoTracciatoNonAbilitatoException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class TipoTracciatoNonAbilitatoException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private TipoTracciatoNonAbilitatoException tipoTracciatoNonAbilitatoException;
    public TipoTracciatoNonAbilitatoException_Exception() {
        super();
    }
    public TipoTracciatoNonAbilitatoException_Exception(String message) {
        super(message);
        this.tipoTracciatoNonAbilitatoException = new TipoTracciatoNonAbilitatoException();
    }
    public TipoTracciatoNonAbilitatoException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.tipoTracciatoNonAbilitatoException = new TipoTracciatoNonAbilitatoException();
    }
    public TipoTracciatoNonAbilitatoException_Exception(String message, TipoTracciatoNonAbilitatoException tipoTracciatoNonAbilitatoException) {
        super(message);
        this.tipoTracciatoNonAbilitatoException = tipoTracciatoNonAbilitatoException;
    }
    public TipoTracciatoNonAbilitatoException_Exception(String message, TipoTracciatoNonAbilitatoException tipoTracciatoNonAbilitatoException, Throwable cause) {
        super(message, cause);
        this.tipoTracciatoNonAbilitatoException = tipoTracciatoNonAbilitatoException;
    }
    public TipoTracciatoNonAbilitatoException getFaultInfo() {
        return this.tipoTracciatoNonAbilitatoException;
    }
}
