/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.902+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "TipologiaIstanzaNonAbilitataFruitoreException", messageName = "TipologiaIstanzaNonAbilitataFruitoreException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class TipologiaIstanzaNonAbilitataFruitoreException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private TipologiaIstanzaNonAbilitataFruitoreException tipologiaIstanzaNonAbilitataFruitoreException;
    public TipologiaIstanzaNonAbilitataFruitoreException_Exception() {
        super();
    }
    public TipologiaIstanzaNonAbilitataFruitoreException_Exception(String message) {
        super(message);
        this.tipologiaIstanzaNonAbilitataFruitoreException = new TipologiaIstanzaNonAbilitataFruitoreException();
    }
    public TipologiaIstanzaNonAbilitataFruitoreException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.tipologiaIstanzaNonAbilitataFruitoreException = new TipologiaIstanzaNonAbilitataFruitoreException();
    }
    public TipologiaIstanzaNonAbilitataFruitoreException_Exception(String message, TipologiaIstanzaNonAbilitataFruitoreException tipologiaIstanzaNonAbilitataFruitoreException) {
        super(message);
        this.tipologiaIstanzaNonAbilitataFruitoreException = tipologiaIstanzaNonAbilitataFruitoreException;
    }
    public TipologiaIstanzaNonAbilitataFruitoreException_Exception(String message, TipologiaIstanzaNonAbilitataFruitoreException tipologiaIstanzaNonAbilitataFruitoreException, Throwable cause) {
        super(message, cause);
        this.tipologiaIstanzaNonAbilitataFruitoreException = tipologiaIstanzaNonAbilitataFruitoreException;
    }
    public TipologiaIstanzaNonAbilitataFruitoreException getFaultInfo() {
        return this.tipologiaIstanzaNonAbilitataFruitoreException;
    }
}
