/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.861+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "TipologiaIstanzaInesistenteException", messageName = "TipologiaIstanzaInesistenteException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class TipologiaIstanzaInesistenteException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private TipologiaIstanzaInesistenteException tipologiaIstanzaInesistenteException;
    public TipologiaIstanzaInesistenteException_Exception() {
        super();
    }
    public TipologiaIstanzaInesistenteException_Exception(String message) {
        super(message);
        this.tipologiaIstanzaInesistenteException = new TipologiaIstanzaInesistenteException();
    }
    public TipologiaIstanzaInesistenteException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.tipologiaIstanzaInesistenteException = new TipologiaIstanzaInesistenteException();
    }
    public TipologiaIstanzaInesistenteException_Exception(String message, TipologiaIstanzaInesistenteException tipologiaIstanzaInesistenteException) {
        super(message);
        this.tipologiaIstanzaInesistenteException = tipologiaIstanzaInesistenteException;
    }
    public TipologiaIstanzaInesistenteException_Exception(String message, TipologiaIstanzaInesistenteException tipologiaIstanzaInesistenteException, Throwable cause) {
        super(message, cause);
        this.tipologiaIstanzaInesistenteException = tipologiaIstanzaInesistenteException;
    }
    public TipologiaIstanzaInesistenteException getFaultInfo() {
        return this.tipologiaIstanzaInesistenteException;
    }
}
