/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.936+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "TracciatoVersioneNonCoerentiException", messageName = "TracciatoVersioneNonCoerentiException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class TracciatoVersioneNonCoerentiException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private TracciatoVersioneNonCoerentiException tracciatoVersioneNonCoerentiException;
    public TracciatoVersioneNonCoerentiException_Exception() {
        super();
    }
    public TracciatoVersioneNonCoerentiException_Exception(String message) {
        super(message);
        this.tracciatoVersioneNonCoerentiException = new TracciatoVersioneNonCoerentiException();
    }
    public TracciatoVersioneNonCoerentiException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.tracciatoVersioneNonCoerentiException = new TracciatoVersioneNonCoerentiException();
    }
    public TracciatoVersioneNonCoerentiException_Exception(String message, TracciatoVersioneNonCoerentiException tracciatoVersioneNonCoerentiException) {
        super(message);
        this.tracciatoVersioneNonCoerentiException = tracciatoVersioneNonCoerentiException;
    }
    public TracciatoVersioneNonCoerentiException_Exception(String message, TracciatoVersioneNonCoerentiException tracciatoVersioneNonCoerentiException, Throwable cause) {
        super(message, cause);
        this.tracciatoVersioneNonCoerentiException = tracciatoVersioneNonCoerentiException;
    }
    public TracciatoVersioneNonCoerentiException getFaultInfo() {
        return this.tracciatoVersioneNonCoerentiException;
    }
}
