/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.821+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "UnrecoverableException", messageName = "UnrecoverableException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class UnrecoverableException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private UnrecoverableException unrecoverableException;
    public UnrecoverableException_Exception() {
        super();
    }
    public UnrecoverableException_Exception(String message) {
        super(message);
        this.unrecoverableException = new UnrecoverableException();
    }
    public UnrecoverableException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.unrecoverableException = new UnrecoverableException();
    }
    public UnrecoverableException_Exception(String message, UnrecoverableException unrecoverableException) {
        super(message);
        this.unrecoverableException = unrecoverableException;
    }
    public UnrecoverableException_Exception(String message, UnrecoverableException unrecoverableException, Throwable cause) {
        super(message, cause);
        this.unrecoverableException = unrecoverableException;
    }
    public UnrecoverableException getFaultInfo() {
        return this.unrecoverableException;
    }
}
