/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.828+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "ValoreNonAmmessoException", messageName = "ValoreNonAmmessoException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class ValoreNonAmmessoException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private ValoreNonAmmessoException valoreNonAmmessoException;
    public ValoreNonAmmessoException_Exception() {
        super();
    }
    public ValoreNonAmmessoException_Exception(String message) {
        super(message);
        this.valoreNonAmmessoException = new ValoreNonAmmessoException();
    }
    public ValoreNonAmmessoException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.valoreNonAmmessoException = new ValoreNonAmmessoException();
    }
    public ValoreNonAmmessoException_Exception(String message, ValoreNonAmmessoException valoreNonAmmessoException) {
        super(message);
        this.valoreNonAmmessoException = valoreNonAmmessoException;
    }
    public ValoreNonAmmessoException_Exception(String message, ValoreNonAmmessoException valoreNonAmmessoException, Throwable cause) {
        super(message, cause);
        this.valoreNonAmmessoException = valoreNonAmmessoException;
    }
    public ValoreNonAmmessoException getFaultInfo() {
        return this.valoreNonAmmessoException;
    }
}
