/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.885+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "VersioneTracciatoInesistenteException", messageName = "VersioneTracciatoInesistenteException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class VersioneTracciatoInesistenteException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private VersioneTracciatoInesistenteException versioneTracciatoInesistenteException;
    public VersioneTracciatoInesistenteException_Exception() {
        super();
    }
    public VersioneTracciatoInesistenteException_Exception(String message) {
        super(message);
        this.versioneTracciatoInesistenteException = new VersioneTracciatoInesistenteException();
    }
    public VersioneTracciatoInesistenteException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.versioneTracciatoInesistenteException = new VersioneTracciatoInesistenteException();
    }
    public VersioneTracciatoInesistenteException_Exception(String message, VersioneTracciatoInesistenteException versioneTracciatoInesistenteException) {
        super(message);
        this.versioneTracciatoInesistenteException = versioneTracciatoInesistenteException;
    }
    public VersioneTracciatoInesistenteException_Exception(String message, VersioneTracciatoInesistenteException versioneTracciatoInesistenteException, Throwable cause) {
        super(message, cause);
        this.versioneTracciatoInesistenteException = versioneTracciatoInesistenteException;
    }
    public VersioneTracciatoInesistenteException getFaultInfo() {
        return this.versioneTracciatoInesistenteException;
    }
}
