/*
 *  SPDX-FileCopyrightText: Copyright 2020 - 2021 | CSI Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 */
package it.csi.mudeopen.mudeopensrvsoap.interfacews.acquisizione;
import javax.xml.ws.WebFault;
import it.csi.mudeopen.mudeopensrvsoap.business.be.exception.MudeWSException;
/**
 * This class was generated by Apache CXF 3.2.2
 * 2023-01-25T18:38:23.899+01:00
 * Generated source version: 3.2.2
 */
@WebFault(name = "VersioneTracciatoNonAttivaException", messageName = "VersioneTracciatoNonAttivaException", targetNamespace = "http://acquisizione.interfacews.mudesrvextsic.mude.csi.it/")
public class VersioneTracciatoNonAttivaException_Exception extends MudeWSException {
	private static final long serialVersionUID = 1L;
    private VersioneTracciatoNonAttivaException versioneTracciatoNonAttivaException;
    public VersioneTracciatoNonAttivaException_Exception() {
        super();
    }
    public VersioneTracciatoNonAttivaException_Exception(String message) {
        super(message);
        this.versioneTracciatoNonAttivaException = new VersioneTracciatoNonAttivaException();
    }
    public VersioneTracciatoNonAttivaException_Exception(String message, Throwable cause) {
        super(message, cause);
        this.versioneTracciatoNonAttivaException = new VersioneTracciatoNonAttivaException();
    }
    public VersioneTracciatoNonAttivaException_Exception(String message, VersioneTracciatoNonAttivaException versioneTracciatoNonAttivaException) {
        super(message);
        this.versioneTracciatoNonAttivaException = versioneTracciatoNonAttivaException;
    }
    public VersioneTracciatoNonAttivaException_Exception(String message, VersioneTracciatoNonAttivaException versioneTracciatoNonAttivaException, Throwable cause) {
        super(message, cause);
        this.versioneTracciatoNonAttivaException = versioneTracciatoNonAttivaException;
    }
    public VersioneTracciatoNonAttivaException getFaultInfo() {
        return this.versioneTracciatoNonAttivaException;
    }
}
